### ISSUE TITLE
Add support for Tag Expressions

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-ruby#1003]
## Summary

[Tag Expressions](http://docs.cucumber.io/tag-expressions/) is a more intuitive way to specify tags in tagged hooks and on the command line's `--tags` argument.
## Expected Behavior

Tagged Hooks should accept a single string:

``` ruby
Before("@foo and not @bar") do
end
```

Likewise, the `--tags` command line argument should allow the same. (Specifying it more than once should cause an error)

```
--tags "@foo and not @bar"
```
## Context & Motivation

The current mechanism to specify `or` with comma and `and` with multiple `--tags` is incredibly awkward. Tag Expressions are intuitive!

**Comment by nodo** [comment]
@aslakhellesoy I am quite new to the project, but I would be happy to give this feature a try. What do you think?

**Comment by aslakhellesoy** [comment]
That would be fantastic! Here is how I would do it:

First, fork the cucumber/cucumber repo and add a ruby implementation for tag expressions, porting the JavaScript or Java code. When that's done, send a PR and I'll create a mirror of it at https://github.com/cucumber/tag-expressions-ruby

Then, it's time to update Cucumber-Ruby to use it:

* First make sure you can run all tests successfully
* Locate all the old tag expression code and delete it
* Update existing tests
* Make them pass by using the new library

How does that sound?

**Comment by nodo** [comment]
Sounds good, thanks a lot @aslakhellesoy :) I am planning to dedicate some times next week and keep you updated here.

**Comment by aslakhellesoy** [comment]
That's great @nodo - let us know if you have any questions. You can also try the [contributors](https://gitter.im/cucumber/contributors) chat room.

**Comment by mattwynne** [comment]
If someone wants to take a crack at integrating @nodo's work in https://github.com/cucumber/cucumber/issues/67, I'd like to ask that they help us to stay backwards-compatible for one major release by making the choice of old / new tag expression syntax a configuration option. That will enable us to transition users over to the new syntax gradually. We can make it opt-in first, then make it the default for the next major release.

**Comment by aslakhellesoy** [comment]
Great work so far @nodo! I have released [cucumber-tag_expressions 1.0.0](https://rubygems.org/gems/cucumber-tag_expressions)!

**Comment by aslakhellesoy** [comment]
I second @mattwynne's comment about backwards compatibility.

In the next version, use the new `tag-expression` library only if:

* Only one `--tags` option is used on the CLI or only one string is passed to a tagged hook.
* Its value doesn't contain any commas (that's old school)

Also, print a deprecation warning in the other case, telling people that:

* They should start using the new tag expressions (link to http://docs.cucumber.io/tag-expressions/)
  * We might need to add a migration guide here with some examples
* Old school tag expressions will go away in the next major version
  * No more multiple `--tags` on the CLI or multiple strings passed to tagged hooks - that's an error
  * No more commas in tag strings (that's a tag expression parse error)

WDYT?

**Comment by nodo** [comment]
Sounds good @aslakhellesoy , I will give it a try and keep you updated.

Thanks for the hints.

**Comment by mattwynne** [comment]
Automatic identification of legacy tag expressions (with a deprecation warning) would be awesome UX if we can achieve that.

Remember tags are used in hooks as well as on the CLI.

**Comment by aslakhellesoy** [comment]
Hi @nodo did you make any progress on this?

**Comment by nodo** [comment]
@aslakhellesoy not yet, after seeing added to milestone 4.0 I thought to concentrate on https://github.com/cucumber/cucumber-ruby/pull/954. I would like to pick it up asap though.
