### ISSUE TITLE
Fix unicode scenario for JRuby

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-ruby#1010]
## Summary

On JRuby, we have a failing scenario. For now, [it's been excluded from the build](https://github.com/cucumber/cucumber-ruby/pull/1009/commits/5aef6076ed511b41c8cc503bb93cbb1bae6270ec) with a `@wip-jruby` tag.
## Expected Behavior

This scenario should pass on JRuby.
## Current Behavior

example:
https://travis-ci.org/cucumber/cucumber-ruby/jobs/142149508
## Possible Solution

Either the test is wrong, or we have a bug. It needs investigation.
## Steps to Reproduce (for bugs)

Install JRuby, run `bundle exec cucumber  features/docs/gherkin/unicode_table.feature`

**Comment by brasmusson** [comment]
I did find this the last time I looked into the problem: http://www.jillesvangurp.com/2013/06/14/jruby-utf-8/

Therefore I added [this](https://github.com/cucumber/cucumber-ruby/blob/master/.travis.yml#L15-L19) to `.travis.yml`, to see if it would help, but no.
