### ISSUE TITLE
Add rubocop to check the style of the codebase

### ISSUE THREAD

**Issue by nodo** [cucumber/cucumber-ruby#1014]
What do you think about adding `rubocop` (http://rubocop.readthedocs.io/en/latest/) to check the style of the codebase? 

It doesn't necessarily mean that we need to agree with all the rules enforced by `rubocop`. However, I find useful to have a consistent style in the codebase after we agree on which rules to use.

I would suggest to add some basic configuration and the run `rubocop --auto-gen-config`. This will generate a `.rubocop_todo.yml` which tracks the offences. Then we could gradually fix them.

WDYT?

**Comment by mattwynne** [comment]
Agreed, great idea. It will also present great opportunities for [first timers](http://www.firsttimersonly.com/) contributions to correct the style violations.
