### ISSUE TITLE
Fix style violations

### ISSUE THREAD

**Issue by nodo** [cucumber/cucumber-ruby#1021]
At the moment, the codebase has several style violations. It would be great to refactor the code, such that we are up to date with the community best practices https://github.com/bbatsov/ruby-style-guide.

The list of the violations is in two files:
- https://github.com/cucumber/cucumber-ruby/blob/master/.rubocop_todo.yml (auto generated)
- https://github.com/cucumber/cucumber-ruby/blob/master/.rubocop.yml

These files specify the ignored violations. It would be great to remove some of the violations from the files and fix them progressively in order to keep the PRs small.

**Comment by pmatsinopoulos** [comment]
I will now deal with this: https://github.com/cucumber/cucumber-ruby/blob/master/.rubocop_todo.yml#L20

**Comment by pmatsinopoulos** [comment]
I will deal with this:

```
# Offense count: 1205
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Enabled: false
```

**Comment by bv** [comment]
@jaysonesmith, you are assigned to this issue currently. Do you have any commits to pull-request? I was about to get back to fixing the violations. We could synchronize and push changes to a single branch and then create PR.
What do you think?

**Comment by jaysonesmith** [comment]
Hey @br, I don't currently have anything in the works other than what's open right now. I'm mobile right now also, so I can't look as easily.

Go ahead and start wherever makes sense. :)

**Comment by jaysonesmith** [comment]
@br Unfortunately I can't work on getting things merged today, are you fine with going based off of what's in this ticket?

**Comment by bv** [comment]
Yes, @jaysonesmith I will be able to continue, just wanted to make sure we can avoid fixing same violations.
P.S. I believe "Bleacher Report", you are tagging in the comments, should get surprised :)

**Comment by jaysonesmith** [comment]
@bv I had trouble with that earlier too but for some reason, my brain was so set on br! Sorry! I'll fix and totally understand the worry about duplicate work. Thanks for helping out!

**Comment by jaysonesmith** [comment]
Once my remaining PRs are merged I'm going to update our Rubocop version and also regenerate the todo yaml to bring us up to date.

**Comment by jaysonesmith** [comment]
I've only got two more to get merged and then will be able to under take updating Rubocop and regenerating our todo file! 👍

**Comment by jaysonesmith** [comment]
@bv I've remade the todo file and am working my way through it from the top. Wherever my open tickets have stopped is where I have. Perhaps pick a spot further down and start or start from the bottom? Thanks! 👍

**Comment by bv** [comment]
Thank you @jaysonesmith, would start from the bottom when I get back to it

**Comment by xtrasimplicity** [comment]
Reopened. :)

**Comment by jaysonesmith** [comment]
Thanks, @xtrasimplicity !

**Comment by jaysonesmith** [comment]
I will get back to this eventually!

**Comment by jaysonesmith** [comment]
Aaaand keeping open again! (Sorry all!)

**Comment by jaysonesmith** [comment]
32 commits with more fixes have been made. (Many more to come)

**Comment by jaysonesmith** [comment]
Another 23 commits/cops down!

**Comment by jaysonesmith** [comment]
I should add that all the auto-correctable cops are now done. The next ones will require some more work and others I'll need to make some style decisions around things like line lengths and complexities. I may just leave the complexity counters where they're at as the repo has some pretty monstrous module/classes in it. Part of that size may simply be necessitated by the work we're doing, and that's a-okay. :)

23 cops left!

**Comment by jaysonesmith** [comment]
Alrighty! Down to the final 8 cops left in the todo file! These are going to be tough to address as they'll require some serious refactoring to handle.

**Comment by jaysonesmith** [comment]
With a85672c, I'm calling this issue **FINALLY** complete! I'll leave it open for a day for feedback/changes. 

For some of the limit based cops, I chose a number that would handle the bulk of cases and then either inline disabled some or refactored. There were some scenarios where I wasn't sure how to address them and instead inline disabled. One of the main ones to point out would be setting up a `responds_to_method_missing?` method [here](https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/rspec/disable_option_parser.rb). If anyone wants to take a crack at it or wants to let me know the best way to handle it, feel free. :)

Thanks!

**Comment by jaysonesmith** [comment]
Turns out that the code changes made aren't suitable for use with older Ruby versions so I need to spend some time fixing that. It's mainly just updating the uses of `.match?` to use something supported by those versions.

**Comment by jaysonesmith** [comment]
With @brasmusson 's changes to the match usage, this can now be considered complete! Rubocop has been a part of the rake task for a bit now, so any new development should conform to the rules. If anyone would like to go over the current rubocop file's settings, feel free to reach out or tag me in an issue!

**Comment by nodo** [comment]
🎉
