### ISSUE TITLE
Cucumber does not go to AfterStep if the step is failed!

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-ruby#1026]
## Summary

Originally raised in https://github.com/cucumber/cucumber/issues/26#issuecomment-247807756 by @hangnguyenthuy

I'm using Cucumber 2.3.3
I want to print some log after each step so I have my code like this:

```
AfterStep do
  print_log_for_step(@current_step)
end
```

But in case the step is failed, it never goes to AfterStep, it move to After scenario so I cannot print log of the failed step.
Right now I have to work around in this case.

Anybody has same problem to me?

**Comment by mattwynne** [comment]
@hangnguyenthuy this is by design. AfterStep hooks are compiled in as extra test steps, and run as part of the scenario.

In 3.0.0, you'll be able to use an an [event](http://www.rubydoc.info/github/cucumber/cucumber-ruby/Cucumber/Events), specifically the [AfterTestStep](http://www.rubydoc.info/github/cucumber/cucumber-ruby/Cucumber/Events/AfterTestStep) event.

I'm working on the documentation for this now, and would love to have you try it out to see if it makes sense. I'll leave this ticket open and ping you when I have something.

**Comment by mattwynne** [comment]
This is now documented here: https://app.cucumber.pro/projects/cucumber-ruby/documents/master/features/docs/events/test_step_finished_event.feature

**Comment by Lupeipei** [comment]
@mattwynne I have used  test_step_finished event. Now I can capture page screenshot of every step even the step is failed, it is so cool! Thanks a lot.

**Comment by mattwynne** [comment]
👍 nice one @Lupeipei!

**Comment by sandhusatnam** [comment]
@mattwynne I am trying the same thing as @Lupeipei did capturing screenshot of every step even the step is failed but it didn't work for me. Here's my piece of code.

AfterConfiguration do |config|
  config.on_event :test_step_finished do |event|
      puts "Failed at URL: '#{@browser.current_url}'" 
      embed("data:image/png;base64,#{@browser.screenshot_as(:base64)}",'image/png') 
  end
end

Any suggestions ?

**Comment by mattwynne** [comment]
@sandhusatnam it's hard to say... what didn't work? Did you see the `puts` output? What version of Cucumber are you running?

**Comment by sandhusatnam** [comment]
@mattwynne Thanks for your reply.
I am using version 3.1.1.
I am not able to see even the puts output when the test case finished, looks to me the event doesn't get triggered.

**Comment by aslakhellesoy** [comment]
@sandhusatnam try replacing `puts` with `Kernel.puts`.

I think the bug here is that Cucumber’s own `puts` doesn’t print what’s printed in `AfterStep`, not that the hook doesn’t run.

**Comment by FedericoHenze** [comment]
@sandhusatnam @mattwynne I'm having the same problem. In my case, the problem is that there is that **self** instance is **nil**, therefore, **@browser** is **nil** and that raise a "**nil:NilClass (NoMethodError)**" exception.
any suggestions?

**Comment by sandhusatnam** [comment]
@aslakhellesoy I am not using the AfterStep hook, I am trying to add a event in AfterConfiguration hook.
Though I tried Kernel.puts in this but doesn't work.

**Comment by sandhusatnam** [comment]
@FedericoHenze can you share the code snippet ?

**Comment by sandhusatnam** [comment]
@FedericoHenze try defining your webdriver instance in env.rb file.

**Comment by FedericoHenze** [comment]
@sandhusatnam same result, I guess is not a @driver problem because everything is nil also the self instance

**Comment by aslakhellesoy** [comment]
> I tried Kernel.puts in this but doesn't work.

Can you please be more specific than "doesn't work"? Whnat are you seeing and what did you expect to see instead?

**Comment by sandhusatnam** [comment]
@aslakhellesoy well I am not able to see anything neither with **puts** nor with **Kernel.puts.** 
I am expecting puts or Kernel.puts to print a string.

**Comment by mattwynne** [comment]
@sandhusatnam here are the scenarios for this feature:

https://app.cucumber.pro/projects/cucumber-ruby/documents/branch/master/features/docs/events/test_step_finished_event.feature

these are tested and passing. Can you see what's different between your code and the examples?

**Comment by sandhusatnam** [comment]
@mattwynne well I am able to print puts statement using the code snippet you mentioned above, but the test_step_results are weird.  

![1](https://user-images.githubusercontent.com/26750105/42646890-33587de8-85d0-11e8-91ee-f996c6bd39fc.PNG)

Also I am not able to attach the screenshot.

**Comment by mattwynne** [comment]
Ha! I think that's because they use unicode characters for check-marks and crosses to indicate passes or failure. They're probably not coming through on your terminal for some reason. Try printing `result.class.name` instead.

**Comment by sandhusatnam** [comment]
@mattwynne Great that works but what about the screenshot ?
I am to trying to capture a screenshot and embedd it into the cucumber report but the json report doesn't have anything in there related to screenshot.

Any suggestion ?

**Comment by sandhusatnam** [comment]
@mattwynne I got it its not able to add screenshot because the web driver instance is nil, not sure why so as I am able to run the test case.

**Comment by RameshGhk** [comment]
Hi @mattwynne
I want to print the error message after the step failed. Is there way to capture the error by using AfterConfiguration hook?

Below is the example.
AfterConfiguration do |config|
  config.on_event :test_step_finished do |event|
      if event.result.failed?
      $logger.error("Exception received as #{How can I log the error message?}")
      end
  end
end
Any suggestions ?

**Comment by mattwynne** [comment]
Hi @RameshGhk. Please try not to use GitHub issues for support. Asking in [Slack](https://cucumber.io/support#slack) is a much better choice in future for faster response.

The `event.result` is a https://www.rubydoc.info/github/cucumber/cucumber-ruby-core/Cucumber/Core/Test/Result

If it's a `Failed` you can look at the `exception` property.

**Comment by RameshGhk** [comment]
Hi @mattwynne ,
Thanks a lot for your quick response. Working now..  Yes I will follow slack going forward.
