### ISSUE TITLE
Retry option not working from profiles

### ISSUE THREAD

**Issue by alvaroemmanuel** [cucumber/cucumber-ruby#1050]
## Summary

Retry option not working from profiles
## Expected Behavior

When adding --retry option to a profile, cucumber should use it and retry the given number of times the failing steps.
## Current Behavior

```
Retry option seems to be ignored in profiles.
For instance, if I have a profile like this:

test_profile: --format pretty --retry 2

When running `cucumber -p test_profile`, all steps are executed only once, even if they fail.
```
## Steps to Reproduce (for bugs)

1. Add --retry option to any profile
2. Run cucumber with the given profile
3. See it runs all steps only once, even if they fail
## Context & Motivation

It would be useful to include retry into profiles and not have to write `--retry` on each execution.
## Your Environment

- Version used: 3.0.0.pre.1
- Operating System and version: macOS 10.11.6 "El Capitan"

**Comment by bojingo** [comment]
After banging our heads on the wall for a couple days, I came across this issue to explain why we weren't getting this --retry flag working. We am having the same issues, except we tried it with versions 3.0.0 and I just now also tried with 3.0.1 with no luck.

For convenience, we pretty much exclusively use profiles so this is highly frustrating.

**Comment by jroger2908** [comment]
I unfortunately am having the same problem. I can do the retry from the command line but the exact same syntax will not trigger a retry from a profile. Anyone find what the issue is?

**Comment by bojingo** [comment]
I haven't seen an update to the gem beyond 3.0.1 yet. Any ETA for releasing a version that includes this fix?
