### ISSUE TITLE
pretty formatter, print out step name before it is executed ?

### ISSUE THREAD

**Issue by djwgit** [cucumber/cucumber-ruby#1051]
when using pretty formatter, 
- have some messages printed out in step definition,  
- the output is kind of mismatched with the step name and scenario name.  (see below ...)

it will nicer if could print out step name before the step is executed.
 searched the repo, did not find similar issues reported...  or maybe there is a different way handling this...
thanks..  

```
# test.feature
Feature: test feature

  Scenario: test feature scenario
    Given test step 1
    Then test step 2
    Then test step 3
```

```
#test_step.rb
Given(/^test step 1$/) do
    print("      in step 1\n")
end

Given(/^test step 2$/) do
  print("      in step 2\n")
end

Given(/^test step 3$/) do
  print("      in step 3\n")
end
```

```
# currently, with pretty formatter, the output is like this
cucumber -f pretty ./features/test.feature

Feature: test feature

      in step 1
  Scenario: test feature scenario # ./features/test.feature:5
    Given test step 1             # features/step_definitions/test_steps.rb:1
      in step 2
    Then test step 2              # features/step_definitions/test_steps.rb:6
      in step 3
    Then test step 3              # features/step_definitions/test_steps.rb:11
```

it will be nicer if output could be like this

```
# output 
cucumber -f pretty ./features/test.feature

Feature: test feature

  Scenario: test feature scenario # ./features/test.feature:5
    Given test step 1             # features/step_definitions/test_steps.rb:1
      in step 1
    Then test step 2              # features/step_definitions/test_steps.rb:6
      in step 2
    Then test step 3              # features/step_definitions/test_steps.rb:11
      in step 3
```

**Comment by mattwynne** [comment]
Hi,

This is by design - we capture printed output so that it can be displayed in other formatters too (e.g. HTML).

There are a few other ways of printing text at the right time. Can you give me a bit more context about what you're trying to achieve so I can suggest the best solution?

**Comment by djwgit** [comment]
hey, @mattwynne, thanks for your reply
as in the example above, we just want to have the printed message from a step can go with the step name printed by cucumber pretty formatter.   otherwise, as you see above,  the message printed from step1 " in step 1"  is above the scenario line... kind of messy...   any suggestions?  thanks

**Comment by mattwynne** [comment]
OOOOH! I just read your output properly. Sorry, I misunderstood.

Try using `puts` instead of `print`. Any better?

**Comment by djwgit** [comment]
thanks, @mattwynne , that works.
