### ISSUE TITLE
Skip running a specific feature file

### ISSUE THREAD

**Issue by ducthanh** [cucumber/cucumber-ruby#1052]
**Summary**

We are looking for a good way to skip a feature when executing the Cucumber, say my System have some features, and depend on the market demand the stack holders decide to stop a feature on the product for some days or some hour, and they make it without our aware. And we want to skip running the test for that feature until it is enabled (we can get the feature status (on/off) through the APIs). And base on the status I will config the feature to run the test or not:

**Example:** 

example_1_service_status = 'off'
example_2_service_status = 'on'

Cucumber.config do |features|
   features.execute(example_1_service) = false if example_1_service_status == 'off' ;
end

**Expected Behavior**
Then the example_1_service feature scenarios test will be skipped.

**Comment by aslakhellesoy** [comment]
Tag the feature with a tag, say `@example_1_service_available` and skip it when you run with `--tags ~@example_1_service_available`

For further questions, please use the [support channels](https://cucumber.io/support) - this is a bug tracker
