### ISSUE TITLE
Pretty formatter freezing up console unless redirected

### ISSUE THREAD

**Issue by jsbakker** [cucumber/cucumber-ruby#1057]
## Summary

Firstly, I'm unsure if this is a problem with the formatter code itself or a problem with Calabash, which is the cucumber implementation I've been seeing the issue on. Either way, I have made them aware of it in [this post](https://github.com/calabash/calabash-android/issues/745) and have been going back and forth with them for months until I've reached a conclusion where the pretty formatter is an apparent point of failure.

## Expected Behavior

Able to run tests without the runner freezing, no matter which formatter or output I am using.

## Current Behavior

Long story short, the terminal window eventually freezes up (and current processes are delayed) when running a series of tests. Exactly when and where it freezes is inconsistent (between steps, between scenarios, no pattern in which kind of step or scenario), but pretty much guaranteed to happen within 10-20 minutes, and often much less than that. I am confidently convinced that it is not the tests themselves. The interesting part, is that it only happens when I am using the pretty formatter. And to reinforce that statement, the freeze also does not occur when I am redirecting pretty to a file, E.g. append --format pretty > cal_dbg.txt 2>&1 to my cucumber command.

## Possible Solution

The freeze can be broken out of by pressing Ctrl + C and the tests will continue to execute normally. This tells me that perhaps some process which directs the STDOUT is being blocked somehow?

## Steps to Reproduce (for bugs)
When trying to run 115 scenarios, including 1351 steps over a ~90 minute period, here are different command-line options which produced different results:

`calabash-android run android\bin\release\colligo.briefcase.android.dev-Signed.apk --tags ~@unstable --format html --out test_report.html --format pretty`

Using the pretty formatter to console will usually freeze at least once within the first 10-20 minutes.

`calabash-android run android\bin\release\colligo.briefcase.android.dev-Signed.apk --tags ~@unstable --format html --out test_report.html --format pretty > cal_dbg.txt 2>&1`

Using the pretty formatter redirected to a file did not reproduce a single freeze in the entire run.

`calabash-android run android\bin\release\colligo.briefcase.android.dev-Signed.apk --tags ~@unstable --format html --out test_report.html`

Not using the pretty formatter at all did not reproduce a single freeze in the entire run.

## Context & Motivation

- This is problematic because I can't always babysit my Android device when running UI test automation. The workaround of not using pretty or by redirecting to file will cause me not to see progress updates in real time.

## Your Environment

This has been encountered on Windows and I appear to have Cucumber 2.4.0 ruby gem installed as a dependency of my Calabash-Android installation, BTW.

**Comment by mattwynne** [comment]
Hi @jsbakker,

That sounds like a very frustrating problem. I'm not familiar with exactly how Calabash uses Cucumber under the hood, and I've certainly never heard of anything like this before.

I'm not sure where to start, to be honest. I guess one thing I could suggest would be to see if you can try this from a Linux or OSX machine, just to give us another data point. Is that possible?

**Comment by jsbakker** [comment]
When I made the original report with Calabash, I claimed it was also occurring on OS X but now I don't think so. I've just now done a run on nearly 1,400 steps in OS X and there was not a single pause.

On Windows 10, I was seeing this issue with both the `cmd` window and with a coloured console .exe called ANSICON, so it's possible that the issue is not specific to the terminal executable. Windows 10 is running within Parallels on a Mac.

**Comment by bigtunacan** [comment]
This sounds very similar to an issue we are having with the pretty formatter on a Rails 4.0.13 application.  The cucumber test suite is passing on our Rails 3.2.22.3 build with cucumber 1.3.17.

On our upgrade branch to Rails 4.0.13 the test suite seemingly fails at random with the pretty formatter and we see an error `stream closed (IOError)` where it appears that somehow the connection to `STDOUT` is being lost or closed.

If we pipe the results to a file like @jsbakker has been doing the failure does not occur.
