### ISSUE TITLE
Don't skip rest of steps after running  a 'pending' one

### ISSUE THREAD

**Issue by MaxPleaner** [cucumber/cucumber-ruby#1060]
If I have a few steps and the first step definition says "pending", I expected the rest of the steps to run.

I don't see the point of "pending" if it's going to make all subsequent steps to get skipped.

**Comment by mattwynne** [comment]
Interesting idea. TBH I rarely use pending steps, if at all, so I can't really comment either way. I guess most people's workflow is to go through the steps from the top and start to make them work in that order.

This is a similar request to https://github.com/cucumber/cucumber/issues/79

**Comment by MaxPleaner** [comment]
@mattwynne yes i saw that. I didn't realize that it was only the current scenario's remaining steps that would be skipped. Adding this functionality via rescue is what I ended up doing.
