### ISSUE TITLE
Need Travis ruby 2.0 test? Nokogiri 1.7 requires Ruby 2.1.

### ISSUE THREAD

**Issue by junaruga** [cucumber/cucumber-ruby#1068]
## Summary

Nokogiri 1.7 looks requiring "ruby version >= 2.1.0"
How to fix Travis test for ruby2.0?

## Current Behavior

https://travis-ci.org/cucumber/cucumber-ruby/jobs/190347224

> $ ruby --version
> 
> ruby 2.0.0p598 (2014-11-13 revision 48408) [x86_64-linux]
...
> nokogiri-1.7.0.1 requires ruby version >= 2.1.0, which is incompatible with the current version, ruby 2.0.0p598

## Possible Solution

- Use latest version nokogiri 1.7.x. And stop support for ruby 2.0. Remove ruby 2.0 from `.travis.yml`. 
or 
- Use old verson nokogiri 1.6. For example, update `cucumber.gemspec` from `'~> 1.5'` to `~> 1.6.0`

## Steps to Reproduce (for bugs)

Just run travis test for ruby2.0.

## Context & Motivation

We are happy for the contribution if we can pass all the tests for Travis CI.

## Your Environment

My local environment is 

* Version used:
  ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
* Operating System and version:
  Feodora 24.
* Link to your project:
  Fedora Project cucumber RPM package:
  https://admin.fedoraproject.org/pkgdb/package/rpms/rubygem-cucumber/

**Comment by mattwynne** [comment]
Thanks for logging this @junaruga, appreciated :) 👍

**Comment by wolffan** [comment]
I still see this issue:

`nokogiri-1.7.1 requires ruby version >= 2.1.0, which is incompatible with the
current version, ruby 2.0.0p648`
