### ISSUE TITLE
features/docs/getting_started.feature:7 fails on Ruby 2.4.

### ISSUE THREAD

**Issue by voxik** [cucumber/cucumber-ruby#1071]
## Summary

The test case features/docs/getting_started.feature:7 fails on Ruby 2.4:

## Expected Behavior

The test should pass.

## Current Behavior

~~~
expected "No such file or directory @ rb_sysopen - features. You can use `cucumber --init` to get started.\n" to include "No such file or directory - features. You can use `cucumber --init` to get started."
Diff:
@@ -1,2 +1,2 @@
-No such file or directory - features. You can use `cucumber --init` to get started.
+No such file or directory @ rb_sysopen - features. You can use `cucumber --init` to get started.
 (RSpec::Expectations::ExpectationNotMetError)
features/docs/getting_started.feature:10:in `Then it should fail with:'

Failing Scenarios:
cucumber features/docs/getting_started.feature:7 # Scenario: Run Cucumber in an empty directory
~~~

## Possible Solution

This obviously fails due to  https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/runtime.rb#L34 . Isn't it about the time to drop the https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/runtime.rb#L15 ? All currently supported Ruby prints this and I don't think it is going to change soon.

**Comment by voxik** [comment]
Other option is to include it unconditionally ....

**Comment by mattwynne** [comment]
Thanks for looking into this @voxik!

I'd definitely prefer if we can avoid showing the `@ rb_sysopen` noise to our users.

I think it would be nicer to stop subclassing the `FileException` and just raise our own error with our own message, and get rid of all of that cruft. Would you like to send a PR for that?
