### ISSUE TITLE
rake cucumber  does not work as "0 scenarios"

### ISSUE THREAD

**Issue by junaruga** [cucumber/cucumber-ruby#1083]
## Summary

Seeing https://travis-ci.org/cucumber/cucumber-ruby/builds

After this commit https://github.com/cucumber/cucumber-ruby/commit/5f811ce3b6bd46a89a06e4441a2463450f83fb60 ,  all the cucumber tests are skipped as "0 scenarios".

## Expected Behavior

cucumber tests work.

### My local environment

```
$ bundle exec rake cucumber
/usr/local/ruby-2.4.0/bin/ruby -S bundle exec cucumber


0 scenarios
0 steps
0m0.000s
```

### Travis

Also same issue in Travis.

Look this. All the Ruby versions's builds have "0 scenarios".
https://travis-ci.org/cucumber/cucumber-ruby/builds/201999195

## Possible Solution

I have no idea right now.

## Steps to Reproduce (for bugs)

```
$ bundle exec rake cucumber
```

## Your Environment

* Version used: ruby 2.4.0
* Operating System and version: Fedora 24
* Link to your project:

**Comment by junaruga** [comment]
I think this issue is urgent, isn't it?

**Comment by brasmusson** [comment]
It's a false positive. #1054 is dependent on cucumber/cucumber-ruby-core#116, but the cucumber-ruby-core change was merged 10 minutes after the cucumber-ruby change. Look at the [Travis jobs](https://travis-ci.org/cucumber/cucumber-ruby/builds/202000346) after I've restarted them.

**Comment by junaruga** [comment]
@brasmusson 
Your travis job's Ruby 2.4.0 is still 0 scenarios. Is this false positive?
https://travis-ci.org/cucumber/cucumber-ruby/jobs/202000363

**Comment by brasmusson** [comment]
> Your travis job's Ruby 2.4.0 is still 0 scenarios. Is this false positive?
https://travis-ci.org/cucumber/cucumber-ruby/jobs/202000363

@junaruga When I follow the link I see:
```
207 scenarios (11 failed, 196 passed)
1217 steps (11 failed, 6 skipped, 1200 passed)
1m10.102s
```
Yes, it is a false positive, until you find a job that both has `0 Scenarios` and under the `bundle install` writes `Using cucumber-core 2.0.0 from https://github.com/cucumber/cucumber-ruby-core.git (at master@1dcf049)` (which is when cucumber/cucumber-ruby-core#116 is included)

**Comment by junaruga** [comment]
> Your travis job's Ruby 2.4.0 is still 0 scenarios

This was my mistake. Maybe. I must see wrong Travis job.

Yes it is the result that you mentioned above now for Ruby 2.4.0 too.
OK, thanks for your explanation.

**Comment by mattwynne** [comment]
My bad, I did the merges in the wrong order after testing it locally.

This could confuse others too. Note that until we do a release of core, you'll need an up-to-date copy of that project locally to avoid seeing this result when working on the main cucumber gem.
