### ISSUE TITLE
Add junaruga to contributor team

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-ruby#1089]
## Summary

Add @junaruga to the `cucumber-ruby` contributor team

## Detail

Jun has been doing some great work to help Cucumber support the latest versions of Ruby, and so I've given him the commit bit by adding him to the @cucumber/cucumber-ruby team.

Please say Hello to Jun everyone!

@junaruga please continue using PRs when:

1) you want feedback
2) you want other people to notice your changes

In the case of (2) feel free to go ahead an merge your own PRs. Otherwise I think we should get into the habit of merging one another's wherever possible.

Please also remember that as a committer you'll be expected to set a good example in following and upholding our [code of conduct](https://github.com/cucumber/cucumber/blob/master/CODE_OF_CONDUCT.md) in your interactions with other contributors and users. Do ask me for guidance or advice if you need it.

We can sometimes be found in IM at https://gitter.im/cucumber/contributors if you want to chat.

Welcome @junaruga!

**Comment by junaruga** [comment]
@mattwynne ok! I am happy to join `cucumber-ruby` team.
I will keep in mind for the PR rules, and the code of conduct.

Hello guys!
I suppose that I can contribute mainly for fixing failed tests and improving development environment.

**Comment by nodo** [comment]
Welcome @junaruga !

**Comment by junaruga** [comment]
@mattwynne I have a question.

I want to merge below PR by myself from the page. There is no merge button for me.
I do not have a authority to merge this?
https://github.com/cucumber/gherkin-ruby/pull/2
https://github.com/cucumber/aruba/pull/428

**Comment by mattwynne** [comment]
@junaruga I think I had set the team permissions up wrong (probably meaning this button was also missing for other recently added team members in @cucumber/cucumber-ruby (sorry folks).

Can you try again?

**Comment by junaruga** [comment]
@mattwynne okay.

In case of below PR, I can see the merge button.
https://github.com/cucumber/cucumber-ruby-wire/pull/8

But in case of above 2 PRs of  `cucumber/gherkin`, `cucumber/aruba`, I can not see the merge button yet.

**Comment by mattwynne** [comment]
Ok, try again now?

**Comment by junaruga** [comment]
@mattwynne `gherkin`, `aruba` => I can see the merge button.
But `multi_test` => I can not see it.

**Comment by mattwynne** [comment]
My bad. Try `multi_test` again?

**Comment by junaruga** [comment]
@mattwynne thanks I can see the merge button for `multi_test` now!

**Comment by danascheider** [comment]
Welcome to the team @junaruga !

**Comment by junaruga** [comment]
Thanks guys. I would close this ticket, as the time has been passed.
