### ISSUE TITLE
progress style output for passing tests, but full output for those failing

### ISSUE THREAD

**Issue by tansaku** [cucumber/cucumber-ruby#1094]
## Summary

Progress style output for passing tests, but full output for those failing

## Expected Behavior

I'd like to see full output for failing tests (steps and stack traces), but nothing (or just a green dot) for tests that pass.

## Current Behavior

On CI I often find myself wading through loads of green output of individual cucumber tests, when I want the full output only for those tests that have failed ...

~~~
~~~

Can I get this already, or perhaps I'm looking for some kind of combination of the `progress` and `pretty` formatters ... I know progress will show stacktraces for failing tests, but particularly on CI I'd like to see the stacktrace and the steps, but only for the failing tests ...

**Comment by mattwynne** [comment]
Yeah I totally agree! We're doing some work on a new [event protocol](https://github.com/cucumber/cucumber/tree/master/event-protocol) that will mean we can write cross-platform formatters. I think that would be the time to build this kind of functionality.

**Comment by mattwynne** [comment]
See https://github.com/cucumber/cucumber-js/pull/866
