### ISSUE TITLE
Cucumber 3.0.0.pre1 - running before hooks multiple times

### ISSUE THREAD

**Issue by westlakem** [cucumber/cucumber-ruby#1098]
## Summary

My Before hook runs twice after a failed scenario with the --retry flag

## Expected Behavior

The before hook should only run once

## Steps to recreate

Create a test suite with a "fail" in the step.  In the before hook, open a new Watir::Browser.  You will see that 2 browsers get opened after the first "fail")

**Comment by danascheider** [comment]
Thanks for reporting, @westlakem, I'll have a chance to look into this tomorrow. If you'd be interested in making a pull request we'd be happy to help you put something together - otherwise if we're able to repro we'll fix it but can't guarantee a timeline.

**Comment by brasmusson** [comment]
The unit of execution in Cucumber is what is internally is called a _Test Case_, and it includes all hooks (before, after, after-step, and around hooks). The semantics of the `--retry` option, is that after the whole Test Case has executed (including after hooks), if it failed, the whole Test Case (including before hooks etc) is executed again. This is not an issue, it is the intended behavior.

**Comment by westlakem** [comment]
@brasmusson The problem is the --retry flag is running the hooks multiple times in the same test execution.  See example execution stack below.

Before hook runs
Test Runs and Fails
After hook runs
Before hook runs
Before hook runs
Test Runs and Fails
After hook runs
After hook runs
Before hook runs
Before hook runs
Before hook runs
Test Runs
After hook runs
After hook runs
After hook runs

**Comment by brasmusson** [comment]
@westlakem Oh, I misinterpret the issue description. We do not want that.
