### ISSUE TITLE
Ability to include feature files with in cucumber feature.

### ISSUE THREAD

**Issue by vveliev** [cucumber/cucumber-ruby#1109]
## Summary

Ability to reuse common features in order to avoid code duplication.
This can partially be resolved using tags and multiple feature files in conjunction but it's very hard to keep things in order. Maybe it's not that bad to add ability to include feature files with in the feature. Or create new files extension for generating templates for specific test sets.

## Expected Behavior

 Option to include feature files in to the cucumber feature:
let's assume we have 10 feature files, each feature file focusing on one particular feature, but have many different test cases:
    -perform basic login 
    -negative test cases
    -special test cases
    - etc.
Now let's say we need a quick smoke test that will run all positive and basic test cases, how would this solution looks like in current cucumber? possibly cucumber profile, now if you are using profiles for environment switching you will need to some what duplicate profiles that would not be so obvious to read.
   And if this feature files need some glue scenarios in between then you will need to create more features in between , and it becomes some what messy...

If we add ability to include feature files with in feature then we can create more advanced test cases avoiding duplication and yet have ability to add some extra logic.

EX:
```
@api @ns
Feature: Smoke test

@basic @positive 
[%- INCLUDE "completed/user_access.feature" %]

@basic @advance_case1
[%- INCLUDE "completed/cookie.feature" %]

[%- INCLUDE "completed/get_price.feature" %]

  Scenario: I need some extra logic before next feature file
    Given that this is required
    Then i need to enable service

[%- INCLUDE 'completed/modify.feature' %]

[%- INCLUDE 'verification.feature' %]

[%- INCLUDE 'renewal.feature' %]

[%- INCLUDE 'autorenew.feature' %]

[%- INCLUDE "completed/privacy.feature" %]

[%- INCLUDE "completed/password.feature" %]

[%- INCLUDE "completed/subuser.feature" %]

[%- INCLUDE "completed/lock.feature" %]

  Scenario: Ones test's are completed
    Given I need dome extra scenarios for this feature only
    Then I will include them here.

```
 

## Context & Motivation

Reduce dev time avoid code duplication and better code reuse. 
Based on #1076
## Your Environment

* Version used: 2.4
* Operating System and version: Linux

**Comment by aslakhellesoy** [comment]
If I understand correctly you want to test the same behaviour several times.

If you've tested it once, why do you need to test it again?

**Comment by brasmusson** [comment]
> Now let's say we need a quick smoke test that will run all positive and basic test cases, how would this solution looks like in current cucumber?

Adding `--tags '@basic or @positive'` to the command line (or `--tags @basic,@positive` when using Cucumber-Ruby versions not using tag-expression, for instance v2.4) will only run the scenarios with `@basic` or `@positive`. I do not see any duplication with this solution.

**Comment by vveliev** [comment]
@aslakhellesoy - sometimes you need product in one particular state and for that you will repeat behavior in order to test some functionality.  if you performing some tests on the user , you will create for every test case just to make sure you always have same state at the beginning. 

@brasmusson - I think i did mentioned it 

>  possibly cucumber profile, now if you are using profiles for environment switching you will need to some what duplicate profiles

So yes I know about tags , but also you will need to write order of the files, now let's say you want to have different tags from different feature files or some small scenarios in between ?! This is probably extreme case but very possible, how readable is your command line ;) and if this is a regular thing then profile would be a better approach then cmd line

**Comment by westlakem** [comment]
This just sounds like a bad idea... If you need to run specific tests (or feature files) for a smoke test, tag them with `@smoke` and run them with `--tags @smoke`

**Comment by vveliev** [comment]
@westlakem - any example to support your claim ?! 

if it's just a smoke a can see your point, if you have 6-8 different profiles using 10-20 feature files having 6-8 tags just to run profiles + 2-10 tags for environment and test case specific tags things are gonna become messy ...

**Comment by westlakem** [comment]
I guess I don't understand your environment then.

**Comment by westlakem** [comment]
We have profiles or pass in env. Variables for each thing that can change.  Browser, environment, log failures, what state to run with, all configurable from command line.  Ex: cucumber -r features -p chrome -p staging -p log_failures, STATE=NY.


why is it a bad idea? Because if someone did what you were recommending and someone ran all features in the features directory, you could run into an infinite loop.

I agree with the person above that if your testing the same functionality but with different inputs, then you're really just testing the same thing twice.  Let unit tests take care of that. You only need 1 test

**Comment by vveliev** [comment]
@westlakem , I see your point.

but if someone will decide to run all feature files , they may as well get stuck for a day of so .... just due to the amount of test's.  So to me this is something to consider on implementation level. where you can put restrictions on how deep nesting is allowed.

at this moment I'm still trying alternative options.

**Comment by westlakem** [comment]
I still question the amount of testing you're doing with Cucumber.  I'm
still of the opinion (again not knowing your enviornment) that you're
relying too much on Browser based testing and not enough on unit testing.

**Comment by vveliev** [comment]
Ok so another support point:

I have 10 feature files. Some feature files have requirements. 
If i run them all everything works just perfect. However some feature expecting product to be in certain state. I think it's would be beneficial to have step where I validate state, if not then have ability to run other feature files with tags , to meet the requirements and avoid duplication code.

**Comment by westlakem** [comment]
@vveliev IF you have a TEST that requires a product to be in a certain state, then **that test** should (in a before hook) put the product in that state, and then change it back at the end of the test (in an after hook).  The #1 and #2 rule for testing is `*Make each test orthogonal (i.e., independent) to all the others 
*Any given behaviour should be specified in one and only one test. `

You should never have a test that relies on the output of another test.  What happens when that first test breaks? The rest of your tests don't run properly, and no state ever gets cleaned up.  That is what hooks were invented for... Even if your test fails, the `After` hook will still run, cleaning up your data so the next test isn't started from a broken state.

**Comment by Raghuram07** [comment]
Hi all,

**Comment by Raghuram07** [comment]
Is there any chance that we can write a single cucumber test feature and run it in different hubs in different test environments at a time.
Thanks,
Raghu

**Comment by xtrasimplicity** [comment]
@raghuram07 I would recommend asking your query in the Cucumber slack channel, or through one of the other support channels, listed at the following link.

https://cucumber.io/support#community

Github issues are for reporting bugs and requesting new features.

**Comment by Raghuram07** [comment]
Is there any slack group for cucumber

**Comment by xtrasimplicity** [comment]
@raghuram07 Yes, there are a few different slack channels for different purposes. Details on how to access them can be found at the link above, under the "Slack" section.
