### ISSUE TITLE
Ambiguous steps ruin reporting

### ISSUE THREAD

**Issue by enkessler** [cucumber/cucumber-ruby#1113]
## Summary

When ambiguous steps are encountered, Cucumber essentially crashes. No reports are generated and no other tests executed. It just dies.

## Expected Behavior

All tests should be run and output generated as normal. Some tests might fail/be skipped/have undefined steps, etc. but they will at least get executed.

## Current Behavior

As soon as an ambiguous step is encountered, Cucumber declares the ambiguity and then stops. It does not proceed to the next step or even output the results of the run. Using `--guess` will, naturally, remove this problem but the idea is to have failures due to ambiguous steps (e.g. when using `--strict`) be handled in a similar way to pending or undefined steps. That is to say, usefully.

## Possible Solution

If I recall correctly, it didn't use to be this way and ambiguous steps were handled similarly to undefined/pending steps. Why did that change?

## Steps to Reproduce (for bugs)

1. Have a test with ambiguous steps
2. Run it
3. Watch Cucumber fail to fail gracefully

Here is a gist that will trigger the problem (run it one with `--guess` and once without in order to see the difference)

https://gist.github.com/enkessler/f351c4fd83f1b621789ad1d22cecb369

## Context & Motivation

Ambiguous steps happen. Breaking the build happens. However, even a broken build needs useful output but ambiguous steps completely ruin that possibility by crashing the suite immediately.

## Your Environment

* Version used: 2.4.0
* Operating System and version: OSX
* Link to your project: N/A (private)

**Comment by mattwynne** [comment]
Thanks for reporting @enkessler. Do you have time to add a scenario into our acceptance tests that reproduces this? That would be the first step to fixing it.

**Comment by enkessler** [comment]
@mattwynne I'm a little short on time but I'll try. I've got some other projects to maintain and I'm trying to get them all ready for when I show up to CukenFest.

**Comment by brasmusson** [comment]
Cucumber-JS as ["ambiguous"](https://github.com/cucumber/cucumber-js/blob/master/features/ambiguous_step.feature#L33-L34) as a separate result type, which neither Cucumber-Ruby nor Cucumber-JVM have.

**Comment by enkessler** [comment]
Step 1. Shamelessly steal from Cucumber-JS.
Step 2. Get it working in Ruby
Step 3. Profit.

:)

**Comment by enkessler** [comment]
Step 0: Make the build work on Windows.

:(

**Comment by mattwynne** [comment]
> Step 0: Make the build work on Windows.

Can you raise a separate ticket about that?

**Comment by enkessler** [comment]
#1115 opened. Links to the failing builds are included. Mind you, I don't necessarily know how to get them working any more than I know how to make ambiguous steps work. But, you know, I'm trying to do my part by keeping you lot informed. ;)
