### ISSUE TITLE
Cucumber Rerun is not working on windows platform

### ISSUE THREAD

**Issue by rasubh** [cucumber/cucumber-ruby#1117]
We have tried to Rerun the failed tests on windows with the following command. It failed to execute the tests.
**bundle exec cucumber @rerun.txt** 

**Output**- 
Using the default profile...
0 scenarios
0 steps
0m0.000s

Can you please fix this issue or please suggest if there are any alternate command to execute the same. Thanks much in advance.

**Comment by rasubh** [comment]
Hey guys,
I am having hard time to get this working on windows platform. Does anyone has idea how to overcome with this problem?

Please let me know in case if you need more details.

Thanks,
Rahul

**Comment by enkessler** [comment]
@rasubh I just gave it a go on my machine (which is Windows with Cucumber 2.4.0) and it appears to be working fine.

Are you sure that you aren't filtering out those tests for some other reason?

**Comment by rasubh** [comment]
Thanks for your reply @enkessler, Really appreciate. As far as I know we are not doing any kind of filtering. I just wanted to make sure that the gems we are using are the same as yours(we are using cucumber 2.4.0), But I wanted to see any other dependent gems are causing this issue. Could you please send me the gem list and gem env details? so that I can compare with mine. Thanks much in advance.

**Comment by rasubh** [comment]
@enkessler Here is the information on my environment:
Windows Version: Windows 8.1 Enterprise
Cucumber Version: 2.4.0
Ruby Version: 2.3.3
Cucumber CLI: --no-source --color --format pretty --format rerun --out rerun.txt

When test fails the rerun text file is created. When I try to run with the rerun.txt (P.S. Original post)
No test runs

**Comment by rasubh** [comment]
@enkessler   We just tried another experiment.  Before running we copied rerun.txt to r1.txt.  Then we ran `bundle exec cucumber @r1.txt` and it worked.  I think you may have a race condition that is causing the test to clear out rerun.txt before it is reading the contents to run the tests.  Again, when using another file name it works.

**Comment by enkessler** [comment]
Were you attempting to both read the rerun file and write the new failed results to it in the same run?

Something like `cucumber @rerun.txt -f rerun -o rerun.txt` ?

**Comment by rasubh** [comment]
Looks like we did the same in cucumber profile, may be that is the reason it's creating this issue.
