### ISSUE TITLE
Getting total number of steps/test cases before suite is run

### ISSUE THREAD

**Issue by tlrdstd** [cucumber/cucumber-ruby#1123]
## Summary

I am a long-time user of the [fuubar-cucumber](https://github.com/martinciu/fuubar-cucumber) formatter. It breaks under Cucumber 2.4.0+.

Specifically, https://github.com/martinciu/fuubar-cucumber/blob/master/lib/cucumber/formatter/fuubar.rb#L28 calls `features.step_count`. But https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/formatter/legacy_api/adapter.rb#L77 passes `features` as `nil`, so this call fails.

I have tried and failed to figure out if new Cucumber knows in advance how many test steps it will be executing. Is there an equivalent in new Cucumber for `features.step_count` ?

(I know `fuubar-cucumber` is also using the legacy formatter API. I'm willing to re-work it with the modern API, but I need to solve this problem first to decide if it's even worth it.)

## Expected Behavior

A way to determine the total number of test steps or test cases before the suite runs.

## Current Behavior

`features.step_count` returns `NoMethodError: undefined method 'step_count' for nil:NilClass`

I can't find anything in `Cucumber::Formatter::LegacyApi::RuntimeFacade` to help answer this question.

## Steps to Reproduce

```
# Gemfile
gem 'fuubar-cucumber'
```
```
cucumber features/ --format=fuubar
```

## Context & Motivation

I love the insta-fail, progress-bar approach to cucumber output. I can't find any way to achieve this without `fuubar-cucumber`.

**Comment by mattwynne** [comment]
Hi Tyler, thanks for volunteering to help sort this out.

You're right that the design in Cucumber 2+ streams test cases straight out of the compiler and never assembled them into a list to count them first.

Although there was some design elegance to this, it's impractical. We were already buffering up the test cases for certain run configurations, like [randomized runs](https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/filters/randomizer.rb).

I just merged #1082 which now means that we'll collect together the test cases and emit a `test_run_starting` event (in the new protocol) which contains that list of all test cases.

At this point you have a range of options about how to resurrect fuubar-cucumber's compatibility with our API: a quick-and-dirty solution might be to patch https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/formatter/legacy_api/adapter.rb to use that new event to fix the `step_count` attribute you're looking for. Alternatively, you could try mixing new and old protocols, listening to the new event in your existing code and using that to get the info you need. Finally (and this is obviously the best long-term) you'd go over to using the new API entirely.

There's an example [here] of mixing the two.
