### ISSUE TITLE
Steps within Modules - Using World to include the right steps (Cross Platform)

### ISSUE THREAD

**Issue by KyleFairns** [cucumber/cucumber-ruby#1139]
## Summary

I'm attempting to write a library of step definitions for a project that I'm working on that has Web, iOS and Android applications. They all have the same features included, the implementation however, is not the same.

At the moment, we've managed to survive on `if`/`unless` statements to state which type of app we are testing on at that time through a configuration file, however, the amount of differences between some of the steps is adding a lot more complexity than could be achieved if this is in place.

As we do silent checks within step definitions for formatting issues and other simple bugs that have appeared in the past, so that we can be certain they haven't regressed, we're feeling that no matter what we do, the step definition is essentially attempting to do too much.

This is completely unrelated to the generic "Web Steps" / "Training Wheels" of the past, and is a different take on duplicating step definitions, but when used in the manner that I intend to, is a slightly different issue. 

## Expected Behavior

After the `ProjectSteps::Web` module has been included in the "World" like this: `World(ProjectSteps::Web)`, the other step definitions within `ProjectSteps::Android` and `ProjectSteps::IOS` should be ignored (this is in the case that this method of working has not been abused - where multiple platforms have been included in the "World" at the same time).

This would be easier to maintain despite being more, as it is simpler than the mountain of `if`/`unless` statements that currently have to be written to achieve the same thing:

```ruby
require 'cucumber'
module ProjectSteps::IOS
   Cucumber::When 'I provide my personal details' do
       select :title, $user[:title]
       fill :first_name, $user[:first_name]
       fill :last_name, $user[:last_name]
       click :progress
       fill :occupation, $user[:occupation]
       fill :company, $user[:company]
       click :progress
       fill :postcode, $user[:postcode]
       select :address, $user[:line1]
       click :progress
   end
end
module ProjectSteps::Android
   Cucumber::When 'I provide my personal details' do
       select :title, $user[:title]
       fill :first_name, $user[:first_name]
       fill :last_name, $user[:last_name]
       click :progress
       fill :postcode, $user[:postcode]
       select :address, $user[:line1]
       click :progress
       fill :occupation, $user[:occupation]
       fill :company, $user[:company]
       click :progress
   end
end
module ProjectSteps::Web
   Cucumber::When 'I provide my personal details' do
       select :title, $user[:title]
       fill :first_name, $user[:first_name]
       fill :last_name, $user[:last_name]
       fill :occupation, $user[:occupation]
       fill :company, $user[:company]
       fill :postcode, $user[:postcode]
       select :address, $user[:line1]
       click :progress
   end
end

When 'some thing that is the same across platforms' do
   # Some stuff
end
```
Bear in mind, this is a simple example of what this issue is trying to achieve, and doesn't show the full complexity of some of the issues that I'm trying to resolve, but it does highlight areas of unnecessary complexity.

## Current Behavior
Well I'm either *really* close, or *really* far off.

Given, When and Then don't work as expected when within a different module, which is why I had to search for the method that I believe them to be an alias of.

Here is the resulting code:

```ruby
require 'cucumber'

module ProjectSteps::Web
    Cucumber::RbSupport::RbDsl.register_rb_step_definition(
        'I attempt to write a step definition that has to be included to work', 
        Proc.new { 
            # Some stuff here
        })
  end
end
```
It registers the step definition absolutely fine. But that's part of the problem. I only want to register this step definition if the module has been included in the "World" of the project that I'm working on.

Currently, the way to test 3 apps that are fundamentally the same, but are implemented in different ways, is like so:

```ruby
When 'I provide my personal details' do
    select :title, 'Mr'
    fill :first_name, 'John'
    fill :last_name, 'Doe'

    unless $profile[:app_type] == 'web'
        click :progress
    end

    if $profile[:app_type] == 'android'
        fill :postcode, 'TE37ER'
        select :address, '1 Test Street'
        click :progress
        fill :occupation, 'Tester'
        fill :company, 'Test Company'
        click :progress
    else 
        fill :occupation, 'Tester'
        fill :company, 'Test Company'
        unless $profile[:app_type] == 'web'
           click :progress
        end
        fill :postcode, 'TE37ER'
        select :address, '1 Test Street'
        click :progress
    end
end
``` 
If this were split into three step definitions, then it would be simpler to debug in the future, but the same feature files would be able to be used for each of them. As they have the same requirements and features for the most part, they do not warrant an entirely new suite of features that are essentially copied and pasted from the one suite across all three, but they are different enough as to need different definitions across platforms. The current way of doing this is in my opinion, a step definition that is trying to achieve too much.

The ability to have steps that are not part of these modules is still - in my opinion - a benefit in a project like this, as there will be cases where the step definition is cross-platform.

## Context & Motivation

I'm trying to simplify writing of cross-platform tests for users of cucumber in the future.

**Comment by mattwynne** [comment]
Hi Kyle,

Briefly, what I generally do in this situation is to create a layer of indirection at the Ruby level, by mixing in different modules to the World depending on the platform I want to run against. So something like this:

```
module AndroidDriver
  def provide_personal_details
    select :title, $user[:title]
    fill :first_name, $user[:first_name]
    fill :last_name, $user[:last_name]
    # ...
  end
end

Before do
  include AndoidDriver if ENV["app_type"] == "android"
  include WebDriver if ENV["app_type"] == "web"
  # ... etc
end
```

If you'd prefer to keep the indirection at the level of steps, you should be able to do that by keeping the sets of step defs in separate folders, and using the `-r` switch to load different ones. That's not something I've tried much myself though...

I hope that helps, let me know how you get on.

**Comment by enkessler** [comment]
Having multiple step definitions and dynamically loading the correct set (using `-r` or otherwise) works well enough as long as you don't need to use both within the same runtime.

I had a project that had a handful of different applications in its ecosystem and some of these applications had multiple 'skins' but essentially the same functionality so we likewise did not want to duplicate feature files. We ended up loading a different set of steps depending on which product we were testing but hit a snag as soon as we had to do an end to end test across products (because only one product's set of steps had been loaded).

Using the driver approach does encapsulate the behavior in a nicer manner but including the driver directly into the world would have the same limitation in that only one driver could be loaded at once because they all define the same methods.

If your steps used the drivers explicitly, however, you could use more than one at once.

Compare 

```
Given /some step/ do
  perform_action
end
```

with

```
Given /some step/ do
  @driver.perform_action
end
```

They achieve the same goal but the second variation would allow the driver to be changed mid test if need be with a quick `@driver = AndroidDriver.new`
