### ISSUE TITLE
Is there a way to print nested steps to console?

### ISSUE THREAD

**Issue by kapoorlakshya** [cucumber/cucumber-ruby#1155]
## Summary

Is there a way to print nested steps to the console in the current version of Cucumber? Or can this be achieved through a custom formatter? Right now, it only prints the wrapper steps. This could be useful to see in reports for end-to-ends tests that perform multiple small actions under wrapper step.

## Step Definition

```
When /^I log in  as '(.+)' and access the Member Search page$/ do |usr_id|
    step "I log in to the application as '#{usr_id}'"
    step "I access the Member Search page"
end
```

## Current Output:

`I log in as 'TestUser' and access the Member Search page`

## Expected Output

```
I log in and access the Member Search page
    I log in to the application as 'TestUser'
    "I access the Member Search page"
```

or something along these lines.

## Your Environment

* Ruby version: 2.4.4 x64
* Version used: cucumber-ruby 2.4.0
* Operating System and version: Windows 8.1 Pro

I am just getting started on learning about formatters so just curious if this is possible or not.

**Comment by brasmusson** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.

**Comment by kapoorlakshya** [comment]
Will do, thanks!
