### ISSUE TITLE
Rerun formatter should use newlines

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-ruby#1162]
For consistency with other implementations, the `rerun` formatter should use newlines. See https://github.com/cucumber/cucumber/issues/233 for context.

**Comment by brasmusson** [comment]
The parsing of the rerun file already handles newlines in the rerun file, see https://github.com/cucumber/cucumber-ruby/blob/master/spec/cucumber/cli/rerun_spec.rb#L35-L43
