### ISSUE TITLE
Deprecation of `#step` method will cause a lot of trouble for aruba's users

### ISSUE THREAD

**Issue by maxmeyer** [cucumber/cucumber-ruby#1165]
## Summary

Hey @danascheider @mattwynne,

on Cukenfest it was announced, that the `#step` method will be deprecated or is already deprecated. As a lot of aruba's consumers are using this kind of pattern to reference our steps, this is problematic and will cause some effort to fix.

Example:
https://github.com/mroth/lolcommits/blob/master/features/step_definitions/lolcommits_steps.rb (project has 3,800 Stars on Github)

Is there an ETA for the deprecation notice which will cause a lot of warnings running "aruba" in its current form?

This issue should raise attention that adding a warning message and removing will cause a lot of trouble for our users.

Currently there's no effort going on to solve this on "aruba's" side, but I've got some ideas - e.g. an `StepApi`-layer where we can move our step code to - some steps contain quite complicated code.

**Comment by aslakhellesoy** [comment]
The purpose of a deprecation warning is to make people aware that an API is going away in a future release so they have a chance to update code before that happens.

When users of `lolcommits` see those warnings, then the person that loves the project the most will update `lolcommits` to no longer use the deprecated API. If nobody does it, then nobody loves it enough that anyone cares.

I don't think we need to do anything, except point people to a page explaining how to replace `#steps` with direct method invocation (preceded by an extract method refactoring).

**Comment by tooky** [comment]
I think it's also worth pointing out that our intention is to extract the `#step(s)` to a gem as the first step to deprecating it. So even if we remove it from Cucumber, it will still be possible for people to choose to use it.

**Comment by mathieujobin** [comment]
I also love the '#step' method. Will it be replaced by something functionally equivalent?

**Comment by maxmeyer** [comment]
@tooky Thanks Steve. Good to know that, but I think it will be worth to clean up our step definitions. Unfortunately not in the near future.
