### ISSUE TITLE
Make the TC count event optional

### ISSUE THREAD

**Issue by brasmusson** [cucumber/cucumber-ruby#1167]
It is not a good idea to always stop all test cases in a filter before passing them on, because maybe a formatter that is interested in the test case count is used (from the [cukenspace workshop](https://cucumberbdd.slack.com/archives/C5B8A9Q3H/p1498313949091649)), see also https://github.com/cucumber/cucumber-ruby/pull/1082#issuecomment-310316166

**Comment by aslakhellesoy** [comment]
Who cares about fixing this?

**Comment by aurelien-reeves** [comment]
Closing because the PR is outdated.
