### ISSUE TITLE
Gather metrics per scenario to identify long running scenarios

### ISSUE THREAD

**Issue by maxmeyer** [cucumber/cucumber-ruby#1181]
## Summary

Ordered Output runtime of scenarios (Slowest first)

## Expected Behavior

~~~cucumber
Feature: Output duration of each scenario

As a software developer facing severe slow downs in my tests
I want to gather some metrics about what tests are slow
In order to fix them

  Scenario: Single scenario
      Given a feature file with:
      """
      Feature: My feature
        Scenario: My scenario #1
          When I run `sleep 15`
        Scenario: My scenario #2
          When I run `sleep 5`
        Scenario: My scenario #3
          When I run `sleep 25`
      """
      When I run `cucumber --format duration`
      Then the output should contain:
      """
      Feature "My feature"
        Scenario "My scenario #3": Duration 25s
        Scenario "My scenario #1": Duration 15s
        Scenario "My scenario #2": Duration 5s
      """
~~~

## Current Behavior

There's a formatter to output the usage of steps. This outputs information per step, but not per scenario. Thanks @aslakhellesoy for the tip, but unfortunately I was not able to gather the metrics I need to identify long running scenarios.

## Possible Solution

Add a formatter which outputs the duration of each scenario. This requires the start and stop time to be captured for each scenario.

## Context & Motivation

We face a severe slow down of our test suite in https://github.com/cucumber/aruba on JRuby. I would like to make sure it's not the "fault" of our tests.

## Your Environment

* Version used: 2.4.0
* Operating System and version: Arch Linux (Rolling Release)
* Link to your project: https://github.com/cucumber/aruba

**Comment by aslakhellesoy** [comment]
This would be very useful. This shouldn't be added to Cucumber-Ruby though. It should be a standalone command line tool (written in any language) that can slurp Cucumber events (https://docs.cucumber.io/event-protocol/) and make the report you want. It would be usable from any Cucumber implementation.

**Comment by mattwynne** [comment]
I should also say, this is high on my priority list for test results features in Cucumber Pro.
