### ISSUE TITLE
scripts/update-history generates bad links

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-ruby#1182]
2 problems:

* The Markdown is wrong (missing `]`)
* The URL to the issue is wrong (points to API)

Both the script and the `History.md` needs updating.

/cc @mattwynne @jaysonesmith

**Comment by mattwynne** [comment]
Gah! That'll teach me to write untested code late at night while on whisky

**Comment by jaysonesmith** [comment]
Hah! GG @mattwynne :p It should be easy enough to fix for now until the [bash version](https://github.com/cucumber/cucumber/issues/255) comes out.

**Comment by jaysonesmith** [comment]
@mattwynne You fixed this in master, yeah?

**Comment by mattwynne** [comment]
I did, in 25b33b0e8c6e39099bb1a9e76986fef07bd4dded

**Comment by mattwynne** [comment]
Oh wait, actually I didn't fix the URL to the issue thing.

**Comment by mattwynne** [comment]
links fixed in eed8b2d3e0d77dedc2dd8269b2b53b402bdd4d65

**Comment by olleolleolle** [comment]
The only remaining thing is to get History.md in line with those two changes.

**Comment by jaysonesmith** [comment]
History.md is no more @olleolleolle ! :p Are you referring to adding the changes that @mattwynne made to the update script as needing to be added to the changelog or something different?

**Comment by olleolleolle** [comment]
@jaysonesmith The Description field mentioned the History.md as a last step; so, I guess, in order to take this to _done_ as defined in there, the changelog needs to avoid the issues, as well.

**Comment by jaysonesmith** [comment]
@olleolleolle Ah, I get what you mean. Pretty sure I nabbed things. I'd like to also update usernames to point to git profiles, but perhaps that'll be something for another day.
