### ISSUE TITLE
Cannot save changes to profiles in cucumber.yml

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-ruby#1188]
_From @NahidSiddiqui on August 29, 2017 15:17_

Cannot save changes to profiles in cucumber.yml

## Summary
I have saved my cucumber.yml file in config directory which lies in the project directory of my calabash tests. I was previously able to save changes and run the profiles, but this is no longer possible. I cannot create new profiles in cucumber.yml and execute them in command line.

My cucumber.yml looks as below:

simulator: --tags ~@device
device:  --tags ~@emulator

stability: --tags @stability
functional: --tags @functional
ui:  --tags @ui_validation
critical_tests: --tags @criticals
all_tests: --tags @functional,@stability,@ui_validation
local_tests: --tags @emulator,
local_report_format: <%= format_standard_report_local %>

ios_cloud_configuration:      -p ios     -p device <%= feature %>  <%= format_standard_report_cloud %>  --tags ~@cloud_android
android_cloud_configuration:  -p android -p device <%= feature %>  <%= format_standard_report_cloud %>  --tags ~@cloud_ios

When I create a new profile as below, its not picked up during execution and says that profile is not defined.

full_ios_test: --@tags regression

## Expected Behavior

Profile created should be picked up from cucumber.yml

## Current Behavior

New profile created is not picked up from cucumber.yml

## Steps to Reproduce (for bugs)

1. Open cucumber.yml in text editor
2. Add new profile in the file
3. Execute profile in cucumber

## Context & Motivation

I am trying to create a new profile to run specific tests in command line

##Additional information

It seems that the cucumber.yml file is picked up from elsewhere, since when I delete the file from the config folder a new one reappears during execution from no where.

_Copied from original issue: cucumber/cucumber#262_

**Comment by jaysonesmith** [comment]
@NahidSiddiqui, could you share what version of the gem you're using, please?

**Comment by jaysonesmith** [comment]
Also, was your position of the @ sign a typo? If not, I'm curious if you move it to the word regression if that resolves what you're running into?

`full_ios_test: --@tags regression`

**Comment by NahidSiddiqui** [comment]
@ jaysonesmith Hi thanks for your response. Version of my gem is 2.4.6. Yes, sorry that was a typo I did when posting the issue. I did use the correct one as full_ios_test: --tags @regression.

**Comment by NahidSiddiqui** [comment]
Please close this issue

**Comment by jaysonesmith** [comment]
@nahid, is this still an issue you're facing?

**Comment by NahidSiddiqui** [comment]
No, I found the problem. It was a coding error on my side sorry. It has nothing to do with the cucumber ruby framework in this instance.

**Comment by jaysonesmith** [comment]
Hey, good to hear! Thank you for providing more info, I'll go ahead and close this out. :)
