### ISSUE TITLE
Gherkin capturing incorrectly in Step Definitions

### ISSUE THREAD

**Issue by luke-hill** [cucumber/cucumber-ruby#1189]
## Summary

See Example and Expected Behaviour - Self Explanatory

## Expected Behavior
Expected value of `input` should be `5th`

Should capture a local variable `input`. It should *not* do any cleansing as we are not using a Transform* (Note we have a bug raised for this as well)

## Current Behavior
Actual value of input is `5`

## Steps to Reproduce (for bugs)

Feature Code:
```
Feature: Dummy
  Scenario: I can select a suffixed number
    Given I start with the value 5th
```

Step Def Code:
```
Given(/^I start with the value (\w+)$/) do |input|
  @input = input
end
```

## Your Environment

Windows 7 / Mac OSX / Win 8.1
Ruby 2.2.x / 2.3.x
Cucumber 2.4.0
Gherkin 4.1.3

**Comment by aslakhellesoy** [comment]
This surprises me. Are you saying the actual value of `input` is the `Integer` `5`?

Are you *sure* you don't have a transform hidden somewhere that does the transformation?

What's the other bug you've raised?

**Comment by aslakhellesoy** [comment]
In an empty directory I created 2 files:

```gherkin
# features/f.rb
Feature: Dummy
  Scenario: I can select a suffixed number
    Given I start with the value 5th
```

```ruby
# features/step_definitions/s.rb
require 'test/unit/assertions'

World(Test::Unit::Assertions)

Given(/^I start with the value (\w+)$/) do |input|
  assert_equal('5th', input)
end
```

Cucumber passes:

```
$ cucumber
# features/f.rb
Feature: Dummy

  Scenario: I can select a suffixed number # features/f.feature:3
    Given I start with the value 5th       # features/step_definitions/s.rb:6

1 scenario (1 passed)
1 step (1 passed)
0m0.034s
```

Sorry, can't reproduce what you're describing.

**Comment by luke-hill** [comment]
I'll completely wipe my transforms folder

Other issue is this: https://github.com/cucumber/cucumber-ruby/issues/1055

**Comment by luke-hill** [comment]
For reference, my transforms folder contains three transforms, it's likely the SUFFIXED_NUMBER is being used here, but again without my express wishes for it to be used.

```
# Captures any string (incl. spaces) containing accented latin characters e.g. ä, ë, ö, ø.
ACCENTED_CHARACTERS = Transform /^([\w \-\u0091-\u00ff]+)$/ do |name|
  name
end

# Captures a number with suffix e.g. 1st / 3rd. The 2 letters after the number are removed from the capture group
CAPTURE_SUFFIXED_NUMBER = Transform /^(\d+)\w{2}$/ do |number|
  number.to_i
end

CAPTURE_A_NUMBER = Transform /^(-?\d+)$/ do |number|
  number.to_i
end
```

**Comment by aslakhellesoy** [comment]
When Cucumber 3 is released you'll have [Cucumber Expressions](https://cucumber.io/blog/2017/07/26/announcing-cucumber-expressions), which also replace `Transform` and handle it in a better way.

**Comment by mattwynne** [comment]
@aslakhellesoy do you think we should deprecate `Transform` at the same time as we release expressions with 3.0?

**Comment by luke-hill** [comment]
It would seem likely, as there is a lot of unwanted / buggy behaviour with it (This issue is technically a bug, but it's a bug with Transforms, not with regex)
