### ISSUE TITLE
Junit Formatter not working with 'puts' and 'Cucumber.logger': <system-out> section is empty

### ISSUE THREAD

**Issue by alb-i986** [cucumber/cucumber-ruby#1192]
The feature introduced in 847848f4c283a77d390ae99ca589a18c549429cd (see also #258) does not seem to work with `puts`, but it does with `print`.

Given a feature file like this:
```
Feature: asd

  Scenario: write to stdout
    Given I write to stdout something
```

And a step definition like this:
```
Given(/^I write to stdout (\w+)$/) do |string|
  puts string
end
```

When I run `cucumber --format junit --out out`
Then the JUnit report should contain "something" inside the CDATA section of `<system-out>`

But actually it's empty:

```
$ cat out/TEST-features-asd.xml 
<?xml version="1.0" encoding="UTF-8"?>
<testsuite failures="0" errors="0" skipped="0" tests="1" time="0.014794" name="asd">
<testcase classname="asd" name="write to stdout" time="0.014794">
  <system-out>
    <![CDATA[]]>
  </system-out>
  <system-err>
    <![CDATA[]]>
  </system-err>
</testcase>
</testsuite>

```

But if I run `cucumber --format junit --out out --format pretty`, I can see "something" printed on the console:
```
$ cucumber --format junit --out out --format pretty
Feature: asd

  Scenario: write to stdout           # features/asd.feature:3
    Given I write to stdout something # features/step_definitions/stdout.rb:1
      something

1 scenario (1 passed)
1 step (1 passed)
0m0.017s
```

If I replace `puts` with `print` the JUnit formatter works as well.

Environment:

* Version used: 2.4.0
* Operating System and version: Ubuntu

**Comment by alb-i986** [comment]
Also not working with `Cucumber.logger`.

More formally:
Given a step definition like this:
```
Given(/^I write to stdout (\w+)$/) do |string|
  Cucumber.logger.info string
end
```

**Comment by tooky** [comment]
Hi, @alb-i986, thanks for reporting this.

Would you be able to document the behaviour you expect with a breaking acceptance test, please?

The JUnit formatter feature file is here: https://github.com/cucumber/cucumber-ruby/blob/master/features/docs/formatters/junit_formatter.feature

Cucumber treats `puts` in a special way inside step definitions, and I wonder if this is related to that. There's more about that here: https://github.com/cucumber/cucumber-ruby/blob/master/features/docs/defining_steps/printing_messages.feature

I wonder if you use $stdout.puts, do you get the JUnit report that you expect?
