### ISSUE TITLE
Document Cucumber-Expressions in a feature file

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-ruby#1198]
## Summary

The new [cucumber expressions](https://cucumber.io/blog/2017/07/26/announcing-cucumber-expressions) feature being released with 3.0 doesn't have much in the way of documentation in our own [living documentation](https://app.cucumber.pro/projects/cucumber-ruby).

## Expected Behavior

Users of Cucumber need to be guided in how to use Cucumber expressions when reading our living documentation.

We need to set them the right example.

We need to replace almost all uses of step definitions in the docs with cucumber expressions. We'll need one remaining feature for explaining (and testing) the existing regular expression syntax. All other instances should use cucumber expressions.

## Implementation guide

Step 1: Review the feature files, starting with the ones in https://github.com/cucumber/cucumber-ruby/tree/master/features/docs/defining_steps for use of regular expression syntax step defs.

One by one, change them to use cucumber expressions instead, running the tests as you go to make sure nothing's broken.

Step 2: Write a new feature file in that same folder called "getting_started.feature" that explains the basics of how to use a step definition, and uses cucumber expressions for the example.

Feel free to submit a pull request with `WIP` (meaning Work in Progress) in the title and we'll give you feedback and support as you go.

**Comment by aslakhellesoy** [comment]
It's far from complete, but there is a feature file: https://github.com/cucumber/cucumber-ruby/blob/master/features/docs/writing_support_code/parameter_types.feature

**Comment by aslakhellesoy** [comment]
For more detailed documentation, there is https://docs.cucumber.io/cucumber-expressions/ which we'll port over to the new docs project. Let's keep the documentation quantuplication to a minimum.

**Comment by aslakhellesoy** [comment]
Different Cucumber implementations don’t currently share feature files.
Documenting this consistently in each implementation is a lot of work. I’d
prefer documenting it once and for all.

That’s what the new docs.cucumber.io site aims to do. We have
infrastructure in place for sharing docs across implementations.

Documenting Cucumber with Cucumber is a great goal, but before we can do
that in a scalable fashion we should agree whether we want to have shared
features for all implementations, and how we’d solve that in practice.

**Comment by enkessler** [comment]
> we should agree whether we want to have shared
features for all implementations

Why wouldn't we want to have shared features for all implementations?

**Comment by brasmusson** [comment]
> Why wouldn't we want to have shared features for all implementations?

IIRC the last project for shared features (https://github.com/cucumber-attic/cucumber-tck) was abandoned because if was to hard to maintain.

**Comment by aslakhellesoy** [comment]
I didn't say we don't want to have them. I'm just saying doing it in practice is challenging:

* In what repo would they live?
* If they live in a separate repo, how are they versioned alongside the multiple implementations?
* How do we deal with the fact that Cucumber implementations are currently slightly inconsistent in several areas
* Making them cross platform means we can't put code in docstrings, meaning they won't show code examples and won't be good documentation

**Comment by mattwynne** [comment]
I've thought about this quite a bit. Several of Cucumber's users have encountered and solved similar problems. To your excellent points @aslakhellesoy:

> In what repo would they live?
I think the monorepo would be the perfect place

> If they live in a separate repo, how are they versioned alongside the multiple implementations?
Don't know, that seems like an interesting puzzle!

> How do we deal with the fact that Cucumber implementations are currently slightly inconsistent in several areas
I think that surfacing this inconsistency (and the areas where we do have consistency) would be really helpful for the project. When I've seen other Cucumber users (e.g. people deploying their code to multiple TVs and set-top-boxes, they used tags to mark the scenarios that weren't compatible with particular platforms. We could do something similar.

> Making them cross platform means we can't put code in docstrings, meaning they won't show code examples and won't be good documentation
It depends on who we're writing the documentation for. I wouldn't see this as necessarily being a user guide, so much as a living document of how a Cucumber implementation should behave. So the reader is more a Cucumber implementor, who probably cares more about the overall logic than exactly how to define a hook in Java. I think we could leave those documents to the individual implementations.

**Comment by mattwynne** [comment]
Whatever big picture thing we end up doing, this still feature doesn’t currently have any docs.
