### ISSUE TITLE
Steps with parenthesis aren't matched

### ISSUE THREAD

**Issue by artemave** [cucumber/cucumber-ruby#1206]
## Summary

Steps with parenthesis aren't matched against step definitions.

Here is my setup:

```cucumber
Feature: parens
  Scenario: with parens
    Given I have a test with (parens)
```
And a step definition

```ruby
Given("I have a test with (parens)") do
  puts "it works"
end
```

## Expected Behavior

All green.

## Current Behavior

Step does not match the definition

![image](https://user-images.githubusercontent.com/23721/31075267-9a17900c-a76c-11e7-8311-d9d102042d45.png)

If I remove parens from both step and the definition then it works as expected:

![image](https://user-images.githubusercontent.com/23721/31075345-f1c98990-a76c-11e7-9191-604c780aa0c4.png)

## Your Environment

* Version used: 3.01
* Operating System and version: OSX

**Comment by brasmusson** [comment]
Parenthesis has special meaning in Cucumber Expression, AFAIK there is currently no way to escape them, see https://github.com/cucumber/cucumber/issues/107. When using regular expression to define the step definitions it should be possible to escape the parenthesis's, at least with the unreleased fix in https://github.com/cucumber/cucumber/pull/254.

**Comment by artemave** [comment]
Oh, I see. Makes sense. Thanks!
