### ISSUE TITLE
Broken rerun format because of newline

### ISSUE THREAD

**Issue by mkrei** [cucumber/cucumber-ruby#1207]
## Summary

Recent change of the output of rerun feature seems to break the feature by producing a content in the output file, which can not be read in again.
This is probably related to commit 488ea4dba8742d5bad26d71f90df5f32f4ed9654

Up until recently (probably before ) the workflow of running a cucumber suite with `-f rerun --out rerun.txt` followed by cucumber @rerun.txt to run failed tests again worked properly. It wrote a string in the file, e.g. `test.feature:3:14 test2.feature:5` and ran those tests again.
Now cucumber will replace the space between the two feature files with \n resulting in test.feature:3:14\ntest2.feature:5 which can not be read properly. It will complain with

## Expected Behavior

When I run a feature suite with `-f rerun -- rerun.txt` I expect cucumber to procude a file called rerun.txt which contains a valid description of the failed scenarios, so I can use them as input for a second run, e.g. by running `cucumber @rerun.txt`

## Current Behavior

When running the suite with  `-f rerun -- rerun.txt`, the file will contain a string like test.feature:3:14\ntest2.feature:5 instead of formerly test.feature:3:14 test2.feature:5, which cucumber can not parse, but instead fails with 

> No such file or directory - \ntest2.feature:5. You can use `cucumber --init` to get started.

## Possible Solution

Fix or revert the mentioned commit regarding the use of newlines in the rerun output file

## Steps to Reproduce (for bugs)

1. Have a cucumber suite with at least two failing tests, each in a separate feature files
2. Run cucumber -f rerun --out somefile
3. Run cucumber @somefile

## Your Environment

* Version used: ruby 2.3.1p112, cucumber 3.0.1
* Operating System and version: Ubuntu 16.04

**Comment by brasmusson** [comment]
Yes, the rerun feature was broken. The rerun formatter shall separate feature file entries with newline (see #1162), unfortunately 488ea4d made the rerun formatter instead print `'\n'` literately instead of newlines.

**Comment by mulmi** [comment]
I am sorry, could you please also tell us if and when this issue was fixed?

**Comment by tooky** [comment]
@brasmusson I think we should do a patch release for this fix? I'm happy to do it later today or tomorrow?

**Comment by summittracker** [comment]
Was this fixed in a new version of cucumber?

**Comment by aslakhellesoy** [comment]
@summittracker yes: https://github.com/cucumber/cucumber-ruby/blob/master/CHANGELOG.md#302-2017-11-11
