### ISSUE TITLE
rb_support folder is removed from  ruby 3.0.0 release onwards. It was there in beta

### ISSUE THREAD

**Issue by pjapkar** [cucumber/cucumber-ruby#1229]
My dependent gems are failing which look for require 'cucumber/rb_support/rb_language'

**Comment by aslakhellesoy** [comment]
What are those gems?

**Comment by pjapkar** [comment]
cucumber_priority

**Comment by mattwynne** [comment]
This one? https://github.com/makandra/cucumber_priority

Interesting use-case! It's like more configurable version of [guess mode](https://app.cucumber.pro/projects/cucumber-ruby/documents/branch/master/features/docs/defining_steps/ambiguous_steps.feature#scenario-ambiguous-steps-with-guess-mode).

I'm afraid depending on internal bits of Cucumber like that one is going to be brittle. For the time being, the authors of the `cucumber_priority` gem could change the dependency to load files from https://github.com/cucumber/cucumber-ruby/tree/master/lib/cucumber/glue which is where those files moved to, but I couldn't guarantee those won't change again in v4.0.0

It would be better to work on a stable plugin API that lets you do this. We could perhaps move the guess mode functionality out into a similar or the same plugin.
