### ISSUE TITLE
Embed image error

### ISSUE THREAD

**Issue by Richard-Cao** [cucumber/cucumber-ruby#1231]
When I embed image, image id is the same in html.
![image](https://user-images.githubusercontent.com/5953992/32428719-d750da6a-c28c-11e7-8051-6ffdd926a7ea.png)

https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/formatter/html.rb#L45

https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/formatter/html.rb#L399

I think `next_id` function maybe incorrect.

**Comment by Richard-Cao** [comment]
cucumber ruby version > 3.0 will report this error, 2.99.0 is correct.

**Comment by brasmusson** [comment]
Fixed by https://github.com/cucumber/cucumber-ruby/pull/1216, the fix is not released yet but it is available on the master branch.

**Comment by Richard-Cao** [comment]
👍
