### ISSUE TITLE
Ignore case flag not working in new ParameterType regexp

### ISSUE THREAD

**Issue by Lec1k** [cucumber/cucumber-ruby#1232]
## Summary

Ignore case flag not working in new ParameterType regexp parameter.
example: 
```
ParameterType(
    name: 'test',
    regexp: /example/i,
    transformer: lambda do |text|
        text = text + 'qweqw'
        text
    end
)

Given 'I use {test}' do |test|
...
end
```
Will work for:
```
Given I use example
```
But not for:
```
Given I use EXAMPLE
```

## Your Environment

* Version used: 3.0.2
* Operating System and version: ubuntu 16.04
* Ruby:  2.4.2

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/cucumber#308
