### ISSUE TITLE
Cucumber Expressions Ruby - 1line fix

### ISSUE THREAD

**Issue by luke-hill** [cucumber/cucumber-ruby#1234]
I've not managed to get the repo cloned yet in my spare time, however I'll try contribute where possible.

Here is a nice 1line tidy bugfix.

Change
https://github.com/cucumber/cucumber-expressions-ruby/blob/master/lib/cucumber/cucumber_expressions/parameter_type.rb#L41

to
```
"Single transformer unexpectedly matched 2 values - \"#{non_nil_group_values[0]}\" and \"#{non_nil_group_values[1]}\""
```

`$` syntax from java leakover I imagine.

**Comment by olleolleolle** [comment]
@luke-hill There's cool pen icon you can use on GitHub, which forks-and-edits a file.

**Comment by enkessler** [comment]
Now it just needs a test. :)

**Comment by luke-hill** [comment]
I plan on contributing here and to selenium as and when I get around to setting up machine after having completed my ruby training (Last month), I can now start OS contributions

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/cucumber#306
