### ISSUE TITLE
Cucumber Expressions: Runtime infinite hang when invalid match with ParameterType

### ISSUE THREAD

**Issue by luke-hill** [cucumber/cucumber-ruby#1237]
## Summary

When running the following minimal code section RubyMine / command line hangs, and needs killing

## Expected Behavior

Test runs and fails due to it not matching anything

## Current Behavior
Test hangs

## Steps to Reproduce (for bugs)

`test.feature` -Ignore the name, thats something for later should the parser work

``` 
Scenario Outline: Compressed step testing
    Given <query>

    Examples:
    | query                                |
    | I reach Stage4: 1st flight-1st hotl | #Note the typo here
```

`test_steps.rb`
```
Given('I reach Stage4: {optional-flight}-{optional-hotel}') do |flight, hotel|
  puts 'I add normally'
end
```

`support/test.rb`
```
ParameterType(
  name: 'optional-flight',
  regexp: /(1st flight)?/,
  type: String,
  transformer: ->(_) { _ },
)

ParameterType(
  name: 'optional-hotel',
  regexp: /(1st hotel)?/,
  type: String,
  transformer: ->(_) { _ },
)
```

## Context & Motivation

This cropped up when I was (wrongly), trying to convert the following Cucumber 2 step into cucumber 3
`When(/^I reach Stage(?:4|5): ?(#{ACCENTED_CHARACTERS} flight)?\/?(#{ACCENTED_CHARACTERS} hotel)?$/) do |flight, hotel|`

## Your Environment

Cucumber 3, Recent Bundle.
Win7
Ruby 2.3

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/cucumber#307
