### ISSUE TITLE
Cucumber Expressions - Alternation doesn't play nicely with numbers.

### ISSUE THREAD

**Issue by luke-hill** [cucumber/cucumber-ruby#1238]
## Summary

Nice and short. ParameterTypes don't like alternation `/` with numerals.

## Expected Behavior

If I want the option between 2 non capturing groups. Lets say Alpha1 and Beta2 I would write.

`Given('Alpha1/Beta2')` - Sadly this isn't liked.

## Current Behavior

Basically the entire system just infinite hangs. It can't compute. If I create 2 distinct steps.
`Given('Alpha1')`
`Given('Beta2')`

Then I'm on to a winner.

## Steps to Reproduce (for bugs)

`test.feature`
```
Feature: Test
  Scenario: Test scenario
    Given Alpha1
```

`test_steps.rb`

```
Given('Alpha1/Beta2') do
  puts 'WORK!'
end
```

## Context & Motivation

On a side note, I don't believe spacing works either for alternation. (However not directly related), and we have different "pages" of our website under test referred to by numbers.

We call our pages:

`Stage1` - Homepage
`Stage2` - Flights
e.t.c.

## Your Environment

* Version used: Cucumber 3.0.0
* Operating System and version: Win7 Ruby 2.3

P.S. Sorry for all the issues :( I'm about 60% through migrating our suite. And so far it's worked seemless. It's only when I start trying to fix our complex interpolated steps that these issues have cropped up.

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/cucumber#303
