### ISSUE TITLE
Snippet generation throws an error

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-ruby#1239]
@jonjagger found a bug in snippet generation during a training:
http://cyber-dojo.cucumber.io/review/show/AA5C4F80AD?avatar=squid&was_tag=17&now_tag=17

The error went away by changing the step text

**Comment by aslakhellesoy** [comment]
Also: http://cyber-dojo.cucumber.io/kata/edit/178FA4990E?avatar=gopher

**Comment by sebrose** [comment]
Does the error only occur on Cyber-Dojo?

**Comment by aslakhellesoy** [comment]
I haven't tried outside cyber-dojo yet. I have no reason to believe it's cyber-dojo specific - probably a general bug.

**Comment by sebrose** [comment]
The `cucumber` invocation in `cyber-dojo.sh` included this parameter `-I .`

Removing it fixed the error. Not sure why we were ever specifying the location of snippets - or how it ever worked.

**Comment by aslakhellesoy** [comment]
Not sure why that would affect the snippet generation logic but thanks for the pointer!

**Comment by jaysonesmith** [comment]
@aslakhellesoy What action needs to be done on this?

**Comment by aslakhellesoy** [comment]
@sebrose - the `-I` option is an alias for `--snippet-type`, which can take the values `cucumber_expression`, `classic`, `percent` or `regexp`. Not sure why it was specified as `.`, but if that's fixed in the Cyber Dojo template, we can close this.
