### ISSUE TITLE
Error when html formatter tries to render error

### ISSUE THREAD

**Issue by fschwahn** [cucumber/cucumber-ruby#1240]
## Summary

When `Cucumber::Formatter::Html` tries to render an error where `snippet_for` goes to the `else`-branch (line 581)
https://github.com/cucumber/cucumber-ruby/blob/84bc859a62220290383a0a8c80ebf6820a426b4c/lib/cucumber/formatter/html.rb#L575-L583

it returns a frozen string (because of `frozen_string_literal: true`). When the syntax gem is not installed, modifying the frozen string in the `snippet`-method (line 571) raises an error (`can't modify frozen String`).
https://github.com/cucumber/cucumber-ruby/blob/84bc859a62220290383a0a8c80ebf6820a426b4c/lib/cucumber/formatter/html.rb#L568-L573

## Possible Solution

Either `highlighted += "..."` to copy the frozen string instead of mutating it, or `[String.new("# Couldn't get snippet for #{error_line}"), 1]` in `snippet_for` to create a mutable string from the start.

I would have submitted a PR, but couldn't find an easy way to add a regression spec for this.

## Steps to Reproduce (for bugs)

This is hard to reproduce, because I'm not sure how to reliably trigger the `else`-branch in `snippet_for`. It happened on our CI, as well as locally, and was connected with timeouts from `poltergeist`-gem.

## Your Environment

* Version used: 3.1.0 (but every version with frozen_string_literals: true is affected)

**Comment by fschwahn** [comment]
This is still relevant.

**Comment by sciros** [comment]
I see it consistently when hitting a particular kind of error with Watir, usually when an element is not clickable at (x,y) because of an unexpected modal dialog or some-such.
I've been able to replicate it by simply adding 
`raise(Selenium::WebDriver::Error::UnknownError.new('something something')`
into a step definition.

**Comment by newtewt** [comment]
I'm am seeing it consistently as well when the button is visible but not enabled. I see the error below then the can't modify frozen string. Causes my subsequent tests to fail. Installing syntax gem is a work around to fix the error. 

Stack trace showing 
`~/.rvm/gems/ruby-2.4.1/gems/cucumber-3.1.0/lib/cucumber/formatter/html.rb:571:in 'snippet'`

`element present, but timed out after 30 seconds, waiting for #<Watir::Button: located: true; {:class=>"qa-forward-stepper", :tag_name=>"button"}> to be enabled (Watir::Exception::ObjectDisabledException)`

**Comment by xtrasimplicity** [comment]
@newtewt, would you be able to create a [mcve](https://stackoverflow.com/help/mcve) app to demonstrate this particular issue? I've been working on some specs but have not been able to reproduce this issue, even when `snippet` is passed an error with a frozen string. i.e.

```
describe Html::SnippetExtractor do
  describe '#snippet' do
    let(:instance) { Html::SnippetExtractor.new }

    context 'when the error string is frozen' do    
      context 'the error line doesnt end with a colon and a line number' do
        let(:error_line) { 'path/to/file'.freeze }
        let(:error) { [error_line, nil] }

        it do
          expect { instance.snippet(error) }.to raise_error
        end
      end
    end
  end
end
```

(Note: Ideally, this spec will fail - once it does, I can work on patching it so that it doesn't).

**Comment by fschwahn** [comment]
`Html::SnippetExtractor.converter` has to be a `NullConverter` to trigger the mutation of the frozen string, the `error_line` itself does not have to be frozen.

**Comment by xtrasimplicity** [comment]
Thanks @fschwahn! I'll take a look and see what I can do.

**Comment by xtrasimplicity** [comment]
Thanks again, @fschwahn. I can't believe I missed that!

**Comment by olleolleolle** [comment]
(Cool find, fschwan!)

**Comment by aidamanna** [comment]
Hi here! What is the status of this one? I'm having this kind of errors very often :( cc @xtrasimplicity

**Comment by xtrasimplicity** [comment]
Hi @aidamanna, this feature was released as part of [Cucumber v3.1.1](https://rubygems.org/gems/cucumber/versions/3.1.1). Have you tried using this version?

**Comment by aidamanna** [comment]
Nop, but I will now. Thanks a lot!!!

**Comment by xtrasimplicity** [comment]
@aidamanna Not a problem. Let us know if you have any issues.
