### ISSUE TITLE
Issue with 3.0.0,  "Failed describing child of " messages. - Change from ~@Tag to 'not @Tag' needs better error handling

### ISSUE THREAD

**Issue by Githraine** [cucumber/cucumber-ruby#1245]
## Summary
After updating Cuke to 3.0 I started having 2 issues.  Initially I got the deprecation  warning about tags switching from ~@ notation to 'not @' notation.  When I update my files to reflect that, I start getting  "Failed describing child of " messages with hard failures.  

## Steps to Reproduce (for bugs)

https://github.com/Githraine/FWK_for_Cuke_error

**Comment by brasmusson** [comment]
You have to use ` "  --tags 'not @XX'  " `. This is not a cucumber specific thing, it is standard shell behavior (see [mailing list post](https://groups.google.com/d/msg/cukes/oAjwMG9Gqyg/fpjTsYRPAgAJ)). When I change to ` " --tags 'not @XX'  " ` in `cucumber.yml` I get the same behavior as with `ALT_cucumber.yml`

**Comment by Githraine** [comment]
Can you be a little more explicit?  What is missing from my cuke file?  And if you get the same behavior as the ATL cuke file, do you mean it runs without the warnings?
Thanks!

**Comment by brasmusson** [comment]
Does not work:
```
<% base_args = " --no-source --color --format json --tags not @nyi --tags not @ignore --tags not @test --tags not @eyes" %>
```
Does work:
```
<% base_args = " --no-source --color --format json --tags 'not @nyi' --tags 'not @ignore' --tags 'not @test' --tags 'not @eyes'" %>
```
(and so for the other lines with `"not @XX"` in `cucumber.yml`)

The warnings "`Deprecated: Found tags option '~@nyi' ...`" do not occur with the modified `cucumber.yml`

**Comment by Githraine** [comment]
The quotes.  Got it, thanks!!!  I will get to try to upgrade again before Friday.

**Comment by Githraine** [comment]
That worked.  Is there any way to get better error messages when this simple formatting issue occurs?

**Comment by brasmusson** [comment]
Another thing you can do is to rewrite:
```
<% base_args = " --no-source --color --format json --tags 'not @nyi' --tags 'not @ignore' --tags 'not @test' --tags 'not @eyes'" %>
```
as
```
<% base_args = " --no-source --color --format json --tags 'not @nyi and not @ignore and not @test and not @eyes'" %>
```
to really take advantage of [tag-expressions](https://github.com/cucumber/cucumber/tree/master/tag-expressions)
