### ISSUE TITLE
The deprecation warning in adapter.rb is breaking our tests

### ISSUE THREAD

**Issue by kdthomas2121** [cucumber/cucumber-ruby#1247]
## Summary

The parser/formatter doesn't like the puts "WARNING: The formatter #{formatter.class.name} is using the deprecated formatter API which will be removed in v4.0 of Cucumber." in adapter.rb, and reports all of our tests as failing because of it. Could this be removed, as a puts shouldn't break the existing working code.

## Possible Solution

Removing line 59 in adapter.rb fixes the issue

**Comment by jaysonesmith** [comment]
Hey @kdthomas2121 - Thanks for the feedback! Could you share what version of Cucumber you're using and what formatter, please?

**Comment by kdthomas2121** [comment]
No problem! Using 3.0, and 'CustomFormatter::EmptyFormatter' : 'pretty'.

**Comment by mattwynne** [comment]
@kdthomas2121 I don't quite understand. Is it the tests for your `CustomFormatter::EmptyFormatter` that are breaking? Are they somewhere we can see?

**Comment by brasmusson** [comment]
@kdthomas2121 You should rewrite custom formatter to use the new formatter API (see for instance the [Json formatter](https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/formatter/json.rb)). Removing line 59 in `adapter.rb` is a really bad idea, we need to notify people still using the old formatter API, so they have a change to start using the new formatter API before the whole `legacy_api` module is removed.

**Comment by jaysonesmith** [comment]
@kdthomas2121 What ended up happening here for you? Were you able to modify your custom formatter?
