### ISSUE TITLE
Possible Issue: Ruby Instance Variables leaking between scenarios

### ISSUE THREAD

**Issue by luke-hill** [cucumber/cucumber-ruby#1274]
## Summary

Each scenario should be a blank canvas. Variables don't leak in between features, but they seem to be leaking in between scenarios

## Expected Behavior

Variables don't leak in between scenarios (In my attached zip file, you should get 3 different random numbers - 99% of the time anyways!). I should point out I believe this to be an issue, but it might be me misunderstanding the behaviour of cucumber

## Current Behavior

Run my SSCCE attached. You'll get the same random number 3 times.

## Steps to Reproduce (for bugs)

1. Download attached ZIP
2. `cucumber features`
3. You will get 3 values dumped to the console, they will be identical (They shouldn't be IMO)

## Context & Motivation

We have a situation where on each run, the domain (website), might be different
i.e.

Feature: Test search
Scen 1: Test search on uk
Scen 2: Test search (identically) on se
Scen 2: Test search (identically) on no

Here we want to use a memo to set these values accordingly (Previous code below)

```
class Domains
    def current
      @current ||=
        case current_site
        when :uk
          Domains::UK
        when :se
          Domains::SE
        when :no
          Domains::NO
        end
    end
end
```

## Your Environment

* Version used: 2.4.0
* Operating System and version: Win7

**Comment by luke-hill** [comment]
[cucumber test - leaking instance vars.zip](https://github.com/cucumber/cucumber-ruby/files/1663187/cucumber.test.-.leaking.instance.vars.zip)

**Comment by brasmusson** [comment]
Cucumber uses the [World](https://github.com/cucumber/cucumber-ruby/blob/master/features/docs/writing_support_code/world.feature) to isolate the execution of test cases from each other, your step definitions should make sure to only put state within the World (and not within themselves).

**Comment by enkessler** [comment]
@luke-hill 
Clarification: You can put state within step definitions and hooks because they have the same context as the World, a new instance of which is created for each test.

```
When(/^I generate a random number$/) do
  @some_data_to_share = 'foo'
end
```

or

```
Before do
  @some_data_to_share = 'bar'
end
```

In your code example, however, you are storing state within the singleton instance of a Ruby class and only one of those will exist during the entire execution of Cucumber.

```
class RandClass
	def self.generate
		@memo ||= rand(1..100)
	end
end
```

The `self` in the above method declaration is the culprit.
