### ISSUE TITLE
Is the deep clone of arguments necessary?

### ISSUE THREAD

**Issue by jamis** [cucumber/cucumber-ruby#1275]
## Summary

I'm using Cucumber as a platform-agnostic way to describe an API in a book I'm writing, and for the most part it's working fantastically. Cucumber 3.x, though, has thrown a wrench in some of my plans, especially as I've been migrating to cucumber expressions.

This report uses the following minimal setup to demonstrate what I'm seeing.

```gherkin
Scenario: Using arguments to manage scenario state
  Given pi := 3.1415
  Then display pi
```

```ruby
class Variable < Struct.new(:name, :value); end

ParameterType(
  name: "var",
  regexp: /\w+/,
  transformer: -> (name) { @vars[name] ||= Variable.new(name) }
)

Before { @vars = {} }

Given "{var} := {float}" do |var, float|
  var.value = float
end

Then "display {var}" do |var|
  puts "#{var.name}=#{var.value.inspect}"
end
```

_Please note that this setup is intentionally simplified from my actual configuration. While it is certainly possible to accomplish the above without passing state via arguments, doing so in my existing configuration is less trivial._

## Expected Behavior

The scenario should print the value of `pi` (3.1415) when it is run, like so:

```console
$ cucumber -s
Feature: Experiments

  Scenario: Using arguments to manage scenario state
    Given pi := 3.1415
    Then display pi
      pi=3.1415

1 scenario (1 passed)
2 steps (2 passed)
0m0.020s
```

## Current Behavior

The scenario _actually_ prints `nil`, like so:

```console
$ cucumber -s
Feature: Experiments

  Scenario: Using arguments to manage scenario state
    Given pi := 3.1415
    Then display pi
      pi=nil

1 scenario (1 passed)
2 steps (2 passed)
0m0.020s
```

This is because of these lines:

https://github.com/cucumber/cucumber-ruby/blob/187b6cc5f6aadfe3de19eaccb0fcb72f50304799/lib/cucumber/step_match.rb#L97-L99

The arguments are deep cloned before being passed to the step, so any changes the step makes to them are lost.

## Possible Solution

Interestingly, if you replace the call to `deep_clone_args` with just `args` in the `#invoke` method, here:

https://github.com/cucumber/cucumber-ruby/blob/187b6cc5f6aadfe3de19eaccb0fcb72f50304799/lib/cucumber/step_match.rb#L28-L32

The tests all still pass. It is not clear to me what the purpose of the deep clone is, especially given that no tests exist to enforce that condition.

## Your Environment

* Version used: 3.1.0
* Operating System and version: macOS 10.13.3

**Comment by brasmusson** [comment]
It is pretty much intentional that step argument should be able to leak state neither between steps or between scenarios, see https://github.com/cucumber/cucumber-ruby/pull/760 and https://github.com/cucumber/cucumber-ruby/issues/1219.

**Comment by jamis** [comment]
I see, thanks for pointing me at those issues, @brasmusson. I definitely understand not wanting to leak state between scenarios, but allowing data within a scenario to move between steps seems reasonable to me. Still, it has obviously been discussed before, so I won't beat a dead horse. :)

I'll explore other options. In the worst case, I can always monkey patch!
