### ISSUE TITLE
Hooks running twice with versions 2.99.0 and 3.1.0

### ISSUE THREAD

**Issue by Suganthi06** [cucumber/cucumber-ruby#1280]
Hooks running twice.

## Steps to Reproduce

1. I have hooks.rb file with Before and After hooks.
_Before do
    @start_time = Time.now
end

After do
    duration = Time.now - @start_time
end_

2. When I run a scenario, 'Before' hook line '@start_time = Time.now' runs twice. Same with After hook.

## Environment
Versions I tried:
- cucumber gem versions 2.99.0 and 3.1.0
- jruby 9.1.15 and 9.1.16

**Comment by Castone22** [comment]
Are you requiring the hooks file manually somewhere like env?
