### ISSUE TITLE
Cucumber.yml Re-run issue

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-ruby#1290]
_From @reach2jeyan on April 16, 2018 9:11_

I want to re-run the failed scenarios in cucumber, and I understand I can do it using the command

`cucumber --tags @abc --format json --out abc.json --format pretty -f rerun --out rerun.txt || cucumber @rerun.txt`

Now, As I am implementing parallel tests and I am launching multiple scenarios in different devices. This is done by launching multiple cucumber profiles using `cucumber.yml` with rake.

    def run_cucumber(profile) #Configure cucumber to run rake tasks through profiles.
      Cucumber::Rake::Task.new do |t|
        t.profile = profile
      end
      Rake::MultiTask[:cucumber].invoke
    end

Now the cucumber.yml contains the profile name with re-run as

    PixelXL: --tags @device2 --format json --out device2.json --format pretty -f rerun --out rerun.txt || cucumber @rerun.txt

When I run this using `rake` with command `rake PixelXL` after defining a rake task to `cucumber.yml`. I get this error:
```
bundle exec cucumber --profile MotoZ2play

    No such file or directory - ||. You can use `cucumber --init` to get started.
```

And hence I tried using re-run manually by removing from the `cucumber.yml` and adding it to `at_exit` with:

    at_exit do
      @reruninfo = File.open("rerun.txt") {|file| file.read}
      if @reruninfo.size > 1
        system('cucumber @rerun.txt')
      end
    end

This re-runs fine, but would be in loop, since the filesize is always more than 1 as the scenarios have failed once and wouldn't erase. Is there a way, I can implement re-run either with cucumber.yml or by mentioning in hooks? while running with rake?

_Copied from original issue: cucumber/cucumber#362_

**Comment by xtrasimplicity** [comment]
Hey @reach2jeyan, are you still experiencing this issue?

**Comment by reach2jeyan** [comment]
Yes i do! I cannot use `re-run` using cucumber profiles. I ended up running with `--tags` option.
