### ISSUE TITLE
cuwhich ruby

### ISSUE THREAD

**Issue by Paulalliants** [cucumber/cucumber-ruby#1302]
## Current Behavior

~~~
~~~

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by danascheider** [comment]
Hi there @Paulalliants - thanks for opening an issue! You'll need to edit the issue template with the information you want to include so we can help you. :)
