### ISSUE TITLE
JSON Formatter Outputs an Invalid JSON

### ISSUE THREAD

**Issue by fscottmiller** [cucumber/cucumber-ruby#1303]
## Summary

The JSON formatter output is an array of JSON objects (one for each feature) rather than a valid single instance of a JSON. As such, it cannot be parsed universally.
## Expected Behavior

I'd expect the JSON formatter to put out a valid JSON document which can be parsed and used in analytics without any additional transformations.
## Current Behavior

The current output looks something like this (with the pretty option turned off):

[{"uri":"PATH","id":"some-test"...}]

While the JSON format is valid for each element within the array, the output itself if not a valid JSON file, but an array of JSON's.

## Possible Solution
The fix is very easy - simply add something like:

{ "features" : 

to the beginning of the output (and a closing bracket at the end), which will make the format valid. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context & Motivation
I'm working on using ELK to store and analyze automated test results, but Logstash wouldn't recognize the JSON files outputted by Cucumber's normal JSON formatter. I ended up editing the formatter (I simply prepended '{ "features" :' to the output, and appended '}' to the end) and then it was recognized.

## Your Environment

* Version used: 3.1; Ruby 2.4.0
* Operating System and version: Windows 10
* Link to your project:

**Comment by aslakhellesoy** [comment]
According to the [JSON Spec](https://www.json.org) an array is valid JSON. Where have you read it's not?

**Comment by aslakhellesoy** [comment]
We're in the process of finalising a new streaming/messaging API that will replace the JSON formatter, so I recommend you decouple your parser/analyser from the ELK interface so you can easily adopt the new messaging API when it's released.

**Comment by aslakhellesoy** [comment]
Won’t fix because:

* It would break a lot of tools that use the old format
* It’s valid JSON

**Comment by fscottmiller** [comment]
Thank you for the prompt response! My apologies for not first checking the spec; I had assumed opening the json as an array was problematic as it failed with two parsers and was something I had not seen before. Clearly, though, this is something I should address in the parsers, not in the output.

Thank you very much for all your work!
