### ISSUE TITLE
Error missing from console output

### ISSUE THREAD

**Issue by viraptor** [cucumber/cucumber-ruby#1315]
## Summary

Some errors are not displayed in the output properly, but they're saved in the log correctly.
Specifically, in the feature background I can see:
```
session not created exception
from disconnected: unable to connect to renderer
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.35 (0),platform=Linux 3.13.0-147-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 25.02 seconds
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'ip-10-50-1-207', ip: '10.50.1.207', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-147-generic', java.version: '1.8.0_171'
Driver info: driver.version: unknown (Selenium::WebDriver::Error::SessionNotCreatedError)
[remote server] sun.reflect.NativeConstructorAccessorImpl(NativeConstructorAccessorImpl.java):-2:in `newInstance0'
[remote server] sun.reflect.NativeConstructorAccessorImpl(NativeConstructorAccessorImpl.java):62:in `newInstance'
...
-1# Couldn't get snippet for [remote server] sun.reflect.NativeConstructorAccessorImpl(NativeConstructorAccessorImpl.java):-2:in `newInstance0'
0# gem install syntax to get syntax highlighting
```
But the normal output does not contain the same information. I get:
```
Failing Scenarios:
 cucumber -p parallel features/.../some.feature:12
```
but without the same console output.

## Expected Behavior

The error is visible in both the console output and the log.

## Current Behavior

The error details and the warning about failed snippet are in the log file only.

## Steps to Reproduce (for bugs)

Unknown

## Your Environment

* Version used: 3.1.2
* Operating System and version: Ubuntu 16.04
* Link to your project:

**Comment by xtrasimplicity** [comment]
Does this error occur when not using parallel mode?

**Comment by viraptor** [comment]
@xtrasimplicity  I can't easily answer that question unfortunately. The errors which are missing are mostly those coming from chromedriver and they're happening randomly. I reported this because I'm trying to debug/reproduce them.

Since the suite is too big to switch to sequential run and I can't reproduce the issue on demand, this limits my options :( Do you have some specific ideas I could try here?

**Comment by xtrasimplicity** [comment]
I'm not sure, sorry. The `-p parallel` flag stood out to me, as I haven't seen it before (and assumed it was a plugin).

Is it consistently failing, and if so, is it failing at the same point?

**Comment by viraptor** [comment]
They're run against different databases and with the [https://github.com/grosser/parallel_tests](parallel_tests) gem.

It's failing very rarely (every few hundred builds?), so I'm happy to patch in some debug code and report after a while, but wouldn't be able to 100% confirm things for a while.
