### ISSUE TITLE
Request for BeforeStep / AroundStep

### ISSUE THREAD

**Issue by viraptor** [cucumber/cucumber-ruby#1316]
## Summary

There are situations where instrumenting a step would be really useful.

## Possible Solution

Add a `BeforeStep` with an optional parameter to activate for sub-steps as well (calling `step` in a process).

## Context & Motivation

One of the examples I ran into is adding a [marginalia](https://github.com/basecamp/marginalia/) tag. While it's doable in theory by getting the scenario steps in `Before` and then advancing, it has various other issues.
It would be much easier if I could rely on `BeforeStep` for both the defined and called steps explicitly.

## Your Environment

* Version used: 3.1.2

**Comment by xtrasimplicity** [comment]
I think this would be a valuable addition. Is this something you'd like to take a look at implementing? Otherwise, I can try to take a look at this sometime. :)

**Comment by danascheider** [comment]
@xtrasimplicity I don't totally agree that this is a feature we'd want. Using `step` is an antipattern, we don't want to encourage its use. @viraptor Is there a reason you're using `step` instead of helper modules or another approach to deduplicating your step code? I'm wondering if there's a use case we're not seeing.

**Comment by viraptor** [comment]
Sorry, I don't think I'm the right person to talk to about it :-) I'm just trying to instrument a large existing codebase.
The support for `step` is not critical though. I'd be happy with just steps declared in the scenario.

Re. previous question: I can give it a go, but it won't be very soon.

**Comment by xtrasimplicity** [comment]
@danascheider, I definitely agree re: nested steps being an anti-pattern, but unless I've misunderstood, this is only a small part of the initial suggestion?

**Comment by viraptor** [comment]
That's correct.

**Comment by danascheider** [comment]
Got it! The way I read it that looked like the primary use case.

**Comment by viraptor** [comment]
Step away from the close button, bot :)

**Comment by alfarore** [comment]
Hi everyone, not sure if this is the right place to ask this but I'd give it a try.
I've just started to do test automation using Cucumber and Ruby and I'm not sure how to implement 'Before' and 'After' hooks with ruby.
Can someone please direct me to a helpful site or if you have an own example? I would really appreciate it.
Thank you!

**Comment by danascheider** [comment]
@alfarore Although we don't have a whole lot of docs about hooks, you can look at [this section](http://docs.cucumber.io/cucumber/state/#cleaning-your-database) for an example of how hooks are implemented in Ruby. I'll look into adding docs on hooks as well.

**Comment by viraptor** [comment]
Bad bot...

**Comment by luke-hill** [comment]
I had a brief dive into how hooks are created and registered and part of it seems simple to implement, but then I struggled to find how the caller-chain actually then decided which type of hook it was (I can see the different method names, but struggled to find the bit that made it select a type), and also how the hooks were fired (Again I could find the methods, but not spotting how they're selected).

I'll happily have a go at it if I can get some assistance, other than that, just need to maybe wait for someone with a bit more knowledge than me.

**Comment by reitzig** [comment]
Just to add a concrete use case: acting on a test failure (e.g. logging the error separately) doesn't currently seem possible. While this seems reasonable:

```ruby
Around do |scenario, block|
    begin
        block.call
    rescue Exception => e
        $logger.error("Scenario '#{scenario.feature}' failed: #{e}")
        raise e
    end
end
```

exceptions get there. `AroundStep` would be a good place to add this kind of hook instead.
(Explicit error hooks may be nicer, but well.)

**Comment by luke-hill** [comment]
:point_up: I'm not sure what part of this you cannot do with a global `After`

Once a step fails, you can detect the exception class with `if scenario.failed?` and then go from there.

**Comment by reitzig** [comment]
Right, this seems to work:

```ruby
After do |scenario|
    if scenario.failed?
        $logger.error("Scenario '#{scenario.feature} - #{scenario.name}' failed: #{scenario.exception}")
    end
end
```

Thanks, @luke-hill!

**Comment by luke-hill** [comment]
Closing in favour of https://github.com/cucumber/cucumber-ruby/pull/1236
