### ISSUE TITLE
Failing scenario Ambiguous steps

### ISSUE THREAD

**Issue by jackorp** [cucumber/cucumber-ruby#1317]
## Summary

When running cucumber test suite, there is a failure at [features/docs/defining_steps/ambiguous_steps.feature:13 # Scenario: Ambiguous steps](https://github.com/cucumber/cucumber-ruby/blob/master/features/docs/defining_steps/ambiguous_steps.feature#L13), the output contains extra line.

## Expected Behavior

Test suite passes

## Current Behavior

The test output contains extra line `/usr/share/ruby/delegate.rb:83:in 'method_missing'`.

~~~
(::) failed steps (::)

expected "Feature: \n\n  Scenario:                # features/ambiguous.feature:3\n    When a step            #...s/ambiguous.feature:3 # Scenario: \n\n1 scenario (1 failed)\n2 steps (1 failed, 1 passed)\n0m0.012s" to have output: string includes: "      Ambiguous match of \"an ambiguous step\":\n      \n      features/step_defini...ambiguous.feature:3 # Scenario: \n\n1 scenario (1 failed)\n2 steps (1 failed, 1 passed)\n0m0.012s\n"
Diff:
@@ -1,2 +1,22 @@
-(string includes: "      Ambiguous match of \"an ambiguous step\":\n      \n      features/step_definitions.rb:1:in `/^...ambiguous.feature:3 # Scenario: \n\n1 scenario (1 failed)\n2 steps (1 failed, 1 passed)\n0m0.012s\n")
+Feature: 
+
+  Scenario:                # features/ambiguous.feature:3
+    When a step            # features/step_definitions.rb:1
+    Then an ambiguous step # features/ambiguous.feature:5
+      Ambiguous match of "an ambiguous step":
+      
+      features/step_definitions.rb:1:in `/^a.*step$/'
+      features/step_definitions.rb:5:in `/^an ambiguous step$/'
+      
+      You can run again with --guess to make Cucumber be more smart about it
+       (Cucumber::Ambiguous)
+      /usr/share/ruby/delegate.rb:83:in `method_missing'
+      features/ambiguous.feature:5:in `Then an ambiguous step'
+
+Failing Scenarios:
+cucumber features/ambiguous.feature:3 # Scenario: 
+
+1 scenario (1 failed)
+2 steps (1 failed, 1 passed)
+0m0.012s
 (RSpec::Expectations::ExpectationNotMetError)
features/docs/defining_steps/ambiguous_steps.feature:36:in `Then it should fail with:'

Failing Scenarios:
cucumber features/docs/defining_steps/ambiguous_steps.feature:13 # Scenario: Ambiguous steps

212 scenarios (1 failed, 211 passed)
1272 steps (1 failed, 1271 passed)
0m19.667s
~~~

## Possible Solution

There seems to be problem when Cucumber::Ambiguous gets thrown, same test with `--guess` option passes with not problem. Maybe somewhere around [step_match_search line#22](https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/step_match_search.rb#L22)?

## Steps to Reproduce (for bugs)

There is also [log](https://copr-be.cloud.fedoraproject.org/results/jackorp/rubygem-cucumber/fedora-rawhide-x86_64/00792520-rubygem-cucumber/build.log.gz) of the RPM build, scroll down the log to see the failure.

1. fetch gem from rubygems
2. unpack gem
3. clone this repo into seperate folder
4. copy features and cucumber.yml to same place where gem was unpacked
6. Run `RUBYOPT=-Ilib cucumber features/docs/defining_steps/ambiguous_steps.feature`.

## Context & Motivation

I am trying to update rubygem-cucumber package in Fedora.

## Your Environment

* Version used:
gem cucumber version 3.1.2
* Operating System and version:
OS: Fedora rawhide (currently version 30)

ruby version:
~~~
$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
~~~

gems:
~~~
$ gem list
*** LOCAL GEMS ***

aruba (0.14.6)
backports (3.11.0)
builder (3.2.3)
bundler (1.16.1)
childprocess (0.5.9)
cmath (default: 1.0.0)
contracts (0.16.0)
csv (default: 1.0.0)
cucumber (3.1.2)
cucumber-core (3.2.0)
cucumber-expressions (6.0.1)
cucumber-tag_expressions (1.1.1)
cucumber-wire (0.0.1)
date (default: 1.0.0)
dbm (default: 1.0.0)
diff-lcs (1.3)
etc (default: 1.0.0)
fcntl (default: 1.0.0)
ffi (1.9.23)
fiddle (default: 1.0.0)
fileutils (default: 1.0.2)
gdbm (default: 2.0.0)
gherkin (4.1.3)
io-console (0.4.6)
ipaddr (default: 1.2.0)
json (2.1.0)
multi_json (1.13.1)
multi_test (0.1.2)
nokogiri (1.8.4)
openssl (2.1.0)
psych (3.0.2)
rake (12.3.1)
rdoc (6.0.3)
rspec (3.7.0)
rspec-core (3.7.1)
rspec-expectations (3.7.0)
rspec-mocks (3.7.0)
rspec-support (3.7.1)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
stringio (default: 0.0.1)
strscan (default: 1.0.0)
thor (0.19.1)
webrick (default: 1.4.2)
zlib (default: 1.0.0)
~~~

**Comment by danascheider** [comment]
@jackorp Ambiguous step errors are raised when multiple step _definitions_ match a single step. It would be really helpful to see your step definitions for that reason, since this is not an issue with your feature file. An example here would be if you had step definitions like this:
```ruby
Given(/^a step$/) do
  ...
end

Then(/^an?\s?.* step$/) do
  ...
end
```
In this case, the step "Given a step" would match both of these expressions and therefore raise `Cucumber::Ambiguous`. Also note that, in the step definition file, the `Given` and `Then` methods are aliased to one another, so those keywords aren't considered when matching steps. That is to say, the fact that "a step" is a `Given` step and "an ambiguous step" is a `Then` step doesn't actually change anything about how the steps are matched.

Incidentally, in your Gherkin, I noticed you're using a `Then` step to establish the conditions the feature needs to pass (i.e., the presence of one normal step and one ambiguous one). This will work, but the convention is to only use `Then` to denote a result or outcome, and not for steps that establish conditions or take actions meant to trigger that result. You might consider using `And` for the second step for clarity. For example:
```
Given a step
And an ambiguous step
When I run the feature
Then it should raise an error
```
I hope my unsolicited advice is helpful 😬

**Comment by jackorp** [comment]
I may have not specified. I am encountering problem with this repository's features. Specifically this Scenario is to test the [cucumber's](https://github.com/cucumber/cucumber-ruby) implementation of ambiguous steps..

**Comment by danascheider** [comment]
OH okay! I was wondering why those looked suspiciously like our steps! I'll see what I can figure out about this.
