### ISSUE TITLE
Can not add descriptions to Cucumber::Rake::Task

### ISSUE THREAD

**Issue by entwanderer** [cucumber/cucumber-ruby#1325]
## Summary

I want to add descriptions to Cucumber::Rake::Task as i'm get used for rake tasks.

## Expected Behavior

Given the following tasks are in my Rakefile:
```ruby
desc "This is my cucumber rake task"
Cucumber::Rake::Task.new(:my_task) do |t|
  t.profile = 'default'
  t.cucumber_opts = %w{--tags @my-special-tests}
end

desc "This is a simple normal rake task"
task :cleanup do |t|
  clean_up_environment
end
```

When i run `rake --tasks` i get the following output:
```
rake my_task     # This is my cucumber rake task
rake cleanup     # This is a simple normal rake task
```

## Current Behavior

When i run `rake --tasks` with the Rakefile examples in the section "Expected Behaviour" i get the following output:

```
rake my_task     # Run Cucumber features
rake cleanup     # This is a simple normal rake task
```

Because i have lots of Cucumber rake tasks, it looks like this:

```
rake my_task       # Run Cucumber features
rake another_task  # Run Cucumber features
rake cleanup       # This is a simple normal rake task
rake some_task     # Run Cucumber features
rake other_task    # Run Cucumber features
rake task          # Run Cucumber features
rake cucumber_task # Run Cucumber features
rake test_task     # Run Cucumber features
rake tasky_task    # Run Cucumber features

```

## Possible Solution

Add description feature to Cucumber::Rake::Task the same way as usual rake tasks provide.

## Context & Motivation

I've got a lot of rake tasks for my projects.
I would like to document them within the description to have an handy overview as i'm get used with usual rake tasks as well. So I'm forced to write comments into the rake file and read them when i want to figure out what task to run ... especially other people will have to.  The command `rake --tasks` is becoming some bit useless.

## Your Environment

* Version used: 3.1.2
* Operating System and version: NT 6.1 (Win7)

**Comment by luke-hill** [comment]
Whilst it's a valid complaint. If your output is to be treated as literal why are you not naming your rake tasks thus.

```
smoke_tests
e2e_tests
sample_tests
flaky_tests
```

Ruby as a language is designed to be fairly self-descriptive, given its nomenclature and syntax I'm surprised you've not looked at maybe namespacing. So you could have `my_feature:all` or `my_feature:smoke`

That's not to say your issue isn't an issue. Just the instance you've described seems to be fairly conflicting with the traditional ruby / OO language standpoint of having code that is descriptive.

**Comment by danascheider** [comment]
@luke-hill I don't think that's necessarily the case. Personally, even when my Rake tasks have descriptive or namespaced names, I still like them to have good descriptions. I think this would be a worthwhile change to make to Cucumber.

**Comment by danascheider** [comment]
@luke-hill @entwanderer I just realised that in [this code](https://github.com/cucumber/cucumber-ruby/blob/24bf293889ff46a627ad6ba40a4d3740223841c2/lib/cucumber/rake/task.rb#L136-L145) - the `initialize` method of `Cucumber::Rake::Task` - the description can be passed in as a second argument to `Cucumber::Rake::Task.new` (the first argument being the name of the task if not the default name, which is `cucumber`). It's just a slightly different API from a regular Rake task but you can easily add your own description.

**Comment by luke-hill** [comment]
@entwanderer replace

```
desc "This is my cucumber rake task"
Cucumber::Rake::Task.new(:my_task) do |t|
  t.profile = 'default'
  t.cucumber_opts = %w{--tags @my-special-tests}
end
```

With
Cucumber::Rake::Task.new(:my_task, "This is my cucumber rake task") do |t|
  t.profile = 'default'
  t.cucumber_opts = %w{--tags @my-special-tests}
end
```

**Comment by entwanderer** [comment]
@luke-hill thank you for your reply with a working solution example.

I suggest to adjust the API of cucumber tasks to match the usual rake tasks.
