### ISSUE TITLE
Scenario outlines still don't support examples in title

### ISSUE THREAD

**Issue by Githraine** [cucumber/cucumber-ruby#1328]
We finally got upgraded to the latest Cuke.
This is NOT resolved.  Given this scenario outline:
  @mm_calc_tvr_001 @wip
  Scenario Outline: Traditional vs Roth Base tests - <title>
    Given I output "<title>"
      And I am on the "Traditional vs Roth Calculator" calculator page
    When I populate the calculator from "<inputs>" and "calculate"
    Then the calculator results should match the "base" section of "<inputs>"

    Examples:
      | title                                                  | inputs                                         |
      | Single Higher Roth Now Matches                         | single_higher_now_roth_matches                 |
      | Married Higher Roth Now Matches                        | married_higher_now_roth_matches                |
      | Married Lower Roth Now Matches                         | married_lower_now_roth_matches                 |
      | Married Lower Roth Later Matches                       | married_lower_later_roth_matches               |
      | Married Lower 401k Later Matches                       | married_lower_later_401k_matches               |
      | Single Lower Roth Later Matches                        | single_lower_later_roth_matches                |
      | Married Lower 401k Later no Match                      | married_lower_later_401k_does_not_match        |
      | Single Lower Later 401k no match                       | single_lower_later_401k_does_not_match         |
 the results are showing:
Feature: Calculators - Traditional Vs Roth, Scenario: Traditional vs Roth Base tests - <title>, Examples (#1)

_Originally posted by @Githraine in https://github.com/cucumber/cucumber-ruby/issues/984#issuecomment-439983638_

**Comment by danascheider** [comment]
I'm labelling this a bug since we said it was supposed to be fixed in an earlier version of Cucumber.

**Comment by jaysonesmith** [comment]
Thanks for bringing this up to us, @Githraine! We do have tests for that behavior, but perhaps something is up with how they're working or something along those lines. We'll get this ironed out.

**Comment by danascheider** [comment]
So @Githraine let me get this straight as far as the behaviour you're expecting to see.

When I run the code you provided (after writing trivial step definitions so as not to get pending steps), this is the output I get:
```
Feature: Some feature

  Scenario Outline: Traditional vs Roth Based Tests - <title> # features/test.feature:3
    Given I output "<title>"                                  # features/test.feature:4
    And I am on the "Traditional vs Roth Calculator" page     # features/test.feature:5
    When I populate the calculator from "" and "calculate"    # features/test.feature:6
    Then the calculator should match the "base" section of "" # features/test.feature:7

    Examples:
      | title                             | inputs                                  |
      | Single Higher Roth Now Matches    | single_higher_now_roth_matches          |
      | Married Higher Roth Now Matches   | married_higher_now_roth_matches         |
      | Married Lower Roth Now Matches    | married_lower_now_roth_matches          |
      | Married Lower Roth Later Matches  | married_lower_later_roth_matches        |
      | Married Lower 401k Later Matches  | married_lower_later_401k_matches        |
      | Single Lower Roth Later Matches   | single_lower_later_roth_matches         |
      | Married Lower 401k Later no Match | married_lower_later_401k_does_not_match |
      | Single Lower Later 401k no match  | single_lower_later_401k_does_not_match  |

8 scenarios (8 passed)
32 steps (32 passed)
0m0.025s
```
If I understand correctly, the output you'd rather see would look like this:
```
Feature: Some feature

  Scenario: Traditional vs Roth Based Tests - Single Higher Roth Now Passes      # features/test.feature:3
    Given I output "Single Higher Roth Now Passes"
    And I am on the "Traditional vs Roth Calculator" page
    When I populate the calculator from "" and "calculate"
    Then the calculator should match the "base" section of ""

  Scenario: Traditional vs Roth Based Tests - Married Higher Roth Now Passes 
    Given I output "Married Higher Roth Now Passes"
    And I am on the "Traditional vs Roth Calculator" page

  <etc>

1 scenario (1 passed)
2 steps (2 passed)
0m0.011s
```
(Obviously that's not exactly what it would be since it would include locations of step definitions, etc.). But is the idea that you would want each scenario, such as it is, created from your outline to be listed separately?

**Comment by Githraine** [comment]
Ok, here is what I currently get (small edits for clarity):
`Tags: @@mm, @@mm_calc, @@mm_calc_tvr, @@not_prod
Feature: Calculators - Traditional Vs Roth
Scenario: Traditional vs Roth Base tests - <title>, Examples (#1)
Tags: @@mm_calc_tvr_001, @@wip
Start Timestamp : 27 November 2018 - 10:42:49 AM  (2018-11-27 15:42:49 UTC)
Feature: Calculators - Traditional Vs Roth, Scenario: Traditional vs Roth Base tests - <title>, Examples (#1)
Single Higher Roth Now Matches ## this is the output of the Given step, our workaround for this issue
I am on the TradVsRoth Main Page
...
...`

What we want to see would be:
`Tags: @@mm, @@mm_calc, @@mm_calc_tvr, @@not_prod
Feature: Calculators - Traditional Vs Roth
Scenario: Traditional vs Roth Base tests - Single Higher Roth Now Matches, Examples (#1)
Tags: @@mm_calc_tvr_001, @@wip

Feature: Calculators - Traditional Vs Roth, Scenario: Traditional vs Roth Base tests - Single Higher Roth Now Matches, Examples (#1)
I am on the TradVsRoth Main Page`

We could even lose the 'Examples (#1)' but I understand how that might not be good for everyone

Does that help?

**Comment by jaysonesmith** [comment]
I'll let @danascheider reply, but also wanted to ask if you could give us the output from `bundle exec cucumber --version` please? The fix is currently in the v4.0.0.rc1 version.

**Comment by Githraine** [comment]
Ah, well there is a problem!  Our framework just jumped up to 3.1.2
I thought we jumped to latest.
I just changed my local to latest and I am getting 4.0.0.rc.1 
However I am getting this error on that version:
cannot load such file -- cucumber/core/ast/empty_multiline_argument

**Comment by brasmusson** [comment]
What gem is requiring `cucumber/core/ast/empy_mutliline_argument`? Not the `cucumber` gem, it depends on v4.0.0 of the `cucumber-core` gem (in which the module `cucumber/core/ast` is removed).

From what are you getting the output? A custom formatter?

**Comment by Githraine** [comment]
I cannot find anything on empy_mutliline_argument, I am not sure what is using it.  I'll keep digging, thx

**Comment by Githraine** [comment]
Ok, looks like it is a RubyMine dependency.  I am working the issue

**Comment by Githraine** [comment]
When will 4.0.0 go from release candidate to actual stable version?

**Comment by danascheider** [comment]
@Githraine The `parallel_test` dependency will probably affect my employer if they try to upgrade so I'll look into that as well.

**Comment by brasmusson** [comment]
The tag expression handling has been moved to the gem [`cucumber-tag_expressions`](https://github.com/cucumber/cucumber/tree/master/tag-expressions).
