### ISSUE TITLE
typo in the method name at this line ? 

### ISSUE THREAD

**Issue by rlgomes** [cucumber/cucumber-ruby#1334]
https://github.com/cucumber/cucumber-ruby/blob/c44b6bc5e0ecee98dd1daef5be0c7f0142a57d29/lib/cucumber/formatter/stepdefs.rb#L10

I believe the idea here was to override `max_stepdef_length` and not `max_step_length`which doesn't exist.

**Comment by rlgomes** [comment]
@luke-hill sorry I don't have a simple repro for this as I found it only when profiling some code on my side where I had extended from the existing json formatter and noticed that this method getting called a lot and spending time when there was no ned to calculate the length of the step like the pretty formatter requires. When I dug a bit more into it I noticed the typo and overrode on my side to increase quite a bit the performance of the JSON formatter.

**Comment by luke-hill** [comment]
I'll have a quick dig into the code for this. If it is as you mentioned and that method is not defined then I'll add the extra one. But I'll need to consult whoever added it originally just to double check, as I've no idea how this is consumed.

**Comment by luke-hill** [comment]
@rlgomes - This is currently awaiting some input from yourself. If you think it's no longer an issue then we can close up this issue.

**Comment by rlgomes** [comment]
hey @luke-hill thanks for taking a look, its not a big deal for me as I've overridden the method locally but thought you folks would want to know. No reason to spin more wheels here and we can close this and leave it for a future reference if someone finds a really good reason to fix that.
