### ISSUE TITLE
CI: Fix JRuby build (google-protobuf not working with JRuby)

### ISSUE THREAD

**Issue by olleolleolle** [cucumber/cucumber-ruby#1336]
## Summary

In #1335, I tried to use JRuby 9.2.5.0, and looked at the CI output.

The JRuby build was broken.

## Expected Behavior

I expected the `bundle install` to pass.

## Current Behavior

[There was a failure to `bundle install`](https://circleci.com/gh/cucumber/cucumber-ruby/2307).

## Possible Solution

If a fix to protocolbuffers/protobuf#1594 appears, this would resolve this problem.

## Steps to Reproduce (for bugs)

1. use `jruby-9.2.5.0`
1. `bundle install`

## Context & Motivation

This stops us from using Cucumber Ruby with JRuby.

## Your Environment

This is in CircleCI, for JRuby 9.2.5.0.

**Comment by olleolleolle** [comment]
@luke-hill Good news - there's been a development - https://rubygems.org/gems/google-protobuf now has a `3.7.0.rc.2` - let's see how that flies.

**Comment by luke-hill** [comment]
Update. We've merged something in which "should" fix Ruby 2.2 -> 2.6, but it doesn't fix JRuby.

The issues we found was having 2 different versions bundled into the `gem` directly (Which is needed)

**Comment by mvz** [comment]
FWIW, I get the impression that JRuby is very low on the priority list for google-protobuf. So, even if they release a compatible version now, things might break again in the future.

**Comment by luke-hill** [comment]
Going to close this one up as well given all the work gone in recently.
