### ISSUE TITLE
Ruby 2.6 compatibility issues on Fedora Rawhide

### ISSUE THREAD

**Issue by pvalena** [cucumber/cucumber-ruby#1341]
## Summary
nested Features / tests are failing, due to additional Ruby trace output with dynamic steps.

## Current Behavior
In comparison with the [expected output](https://github.com/cucumber/cucumber-ruby/blob/master/features/docs/defining_steps/nested_steps.feature), the output contains an entry from `forwardable.rb`:
~~~
+./features/step_definitions/steps2.rb:5:in `/I have a couple turtles/'
+/usr/share/ruby/forwardable.rb:230:in `invoke_dynamic_step'
+./features/step_definitions/steps2.rb:2:in `/two turtles/'
+features/test_feature_1.feature:3:in `Given two turtles'
~~~
and also here:
~~~
+  Scenario: Call directly
+    Given a step that calls an undefined step
+      Undefined dynamic step: "this does not exist" (Cucumber::UndefinedDynamicStep)
+      /usr/share/ruby/forwardable.rb:230:in `invoke_dynamic_step'
+      ./features/step_definitions/steps.rb:2:in `/^a step that calls an undefined step$/'
+      features/call_undefined_step_from_step_def.feature:4:in `Given a step that calls an undefined step'
+
+  Scenario: Call via another
+    Given a step that calls a step that calls an undefined step
+      Undefined dynamic step: "this does not exist" (Cucumber::UndefinedDynamicStep)
+      /usr/share/ruby/forwardable.rb:230:in `invoke_dynamic_step'
+      ./features/step_definitions/steps.rb:2:in `/^a step that calls an undefined step$/'
+      /usr/share/ruby/forwardable.rb:230:in `invoke_dynamic_step'
+      ./features/step_definitions/steps.rb:6:in `/^a step that calls a step that calls an undefined step$/'
+      features/call_undefined_step_from_step_def.feature:7:in `Given a step that calls a step that calls an undefined step'
~~~

As seen in our [Fedora build](https://copr-be.cloud.fedoraproject.org/results/pvalena/ruby26-gems/fedora-rawhide-x86_64/00843811-rubygem-cucumber/build.log.gz) ([failures only](https://paste.fedoraproject.org/paste/S7fGHAdF9xCIIxSOkQyadA)), during which we execute tests+features.

## Your Environment

* Version used: 3.1.2
* Operating System and version: Fedora Rawhide + Ruby 2.6.0
* Link to your project: http://fedoraproject.org/

**Comment by junaruga** [comment]
I see Ruby 2.6 (RC) is added on Circle CI.
https://github.com/cucumber/cucumber-ruby/blob/master/.circleci/config.yml
But the CI on master branch is not regularly executed? Can you enable cron mode?
https://circleci.com/gh/cucumber/workflows/cucumber-ruby/tree/master

**Comment by luke-hill** [comment]
@pvalena - Do you have a github repo I could clone that shows this failing. Ideally with the smallest amount of code possible?

**Comment by pvalena** [comment]
I do use simply Ruby 2.6 ([on Fedora](https://copr.fedorainfracloud.org/coprs/pvalena/ruby/)) and execute your test suite(cloned repo at git tag v3.1.2): `rspec spec`.

**Comment by pvalena** [comment]
_Note: we currently workaround this by [disabling the failing scenarios](https://src.fedoraproject.org/rpms/rubygem-cucumber/pull-request/2#request_diff)._

**Comment by luke-hill** [comment]
And do you observe this on other operating systems? If not could you amend the issue title accordingly?

**Comment by voxik** [comment]
I think this is the same issue as #1317 and the whole problem is that the `lib/cucumber/formatter/backtrace_filter.rb` is rather naive. I believe that this line [[1]] is supposed to filter out all entries such as `/usr/share/ruby/forwardable.rb:230:in `invoke_dynamic_step'` but this filter actually works just in case that ruby is built in default configuration and installed into `/usr/local`. However, the default Fedora configuration installs ruby into `/usr/lib64/ruby` so the filter does not work.

I think the filter should be improved a bit and should reflect ruby configuration. I think `RbConfig::CONFIG['rubyarchdir']` and `RbConfig::CONFIG['rubylibdir']` should be filtered instead. These are their values with default configuration:

~~~
$ ruby -r rbconfig -e "puts RbConfig::CONFIG['rubyarchdir']"
/usr/local/lib/ruby/2.6.0/x86_64-linux
$ ruby -r rbconfig -e "puts RbConfig::CONFIG['rubylibdir']"
/usr/local/lib/ruby/2.6.0
~~~

and same values obtained from Ruby package provided by Fedora:

~~~
$ ruby -r rbconfig -e "puts RbConfig::CONFIG['rubyarchdir']"
/usr/lib64/ruby
$ ruby -r rbconfig -e "puts RbConfig::CONFIG['rubylibdir']"
/usr/share/ruby
~~~

[1]: https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/formatter/backtrace_filter.rb#L16

**Comment by luke-hill** [comment]
I'm happy to review and work with you on this, as I use Linux as well mainly (Albeit Ubuntu).

Problem: So the issue we believe is that fedora is installing stuff to a different directory based off thats the way "it" works?

Solution: The line that makes the false assumption about where ruby is needs a conditional based on if you're on fedora or not?

Am I there so far>?

If so, check out the PR. I've put some suggestions on there for the first kind of thing we could tidy up. And then maybe tackle from there.

**Comment by voxik** [comment]
This is not about Fedora. This is about a configuration of Ruby. Here are several configuration options which influences layout of Ruby directories:

~~~
$ ./configure --help

... snip ...

Installation directories:
  --prefix=PREFIX         install architecture-independent files in PREFIX
                          [/usr/local]
  --exec-prefix=EPREFIX   install architecture-dependent files in EPREFIX
                          [PREFIX]

... snip ...

Fine tuning of the installation directories:
  --bindir=DIR            user executables [EPREFIX/bin]
  --sbindir=DIR           system admin executables [EPREFIX/sbin]
  --libexecdir=DIR        program executables [EPREFIX/libexec]
  --sysconfdir=DIR        read-only single-machine data [PREFIX/etc]
  --sharedstatedir=DIR    modifiable architecture-independent data [PREFIX/com]
  --localstatedir=DIR     modifiable single-machine data [PREFIX/var]
  --libdir=DIR            object code libraries [EPREFIX/lib]
  --datarootdir=DIR       read-only arch.-independent data root [PREFIX/share]
  --datadir=DIR           read-only architecture-independent data [DATAROOTDIR]
  --infodir=DIR           info documentation [DATAROOTDIR/info]

... snip ...

Program names:
  --program-prefix=PREFIX            prepend PREFIX to installed program names
  --program-suffix=SUFFIX            append SUFFIX to installed program names
  --program-transform-name=PROGRAM   run sed PROGRAM on installed program names

... snip ...

Optional Features:
  --enable-multiarch      enable multiarch compatible directories

... snip ...

Optional Packages:

... snip ...

  --with-os-version-style=TYPE
                          OS version number for target and target_os [[full]]
                          (full|teeny|minor+0|minor|major+0|major|none)

... snip ...

  --with-rubylibprefix=DIR
                          prefix for ruby libraries [[LIBDIR/RUBY_BASE_NAME]]

... snip ...

  --with-rubyarchprefix=DIR
                          prefix for architecture dependent ruby libraries
                          [[RUBYLIBPREFIX/ARCH]]

... snip ...

  --with-ruby-version=STR ruby version string for version specific directories
                          [[full]] (full|minor|STR)

... snip ...
~~~

As you can see, there is plenty of freedom, where Ruby can put its stuff. Various platforms are using the flags in different way.
