### ISSUE TITLE
4.0.0.rc.1 + Ruby 2.6.0 compatibility

### ISSUE THREAD

**Issue by JaniJegoroff** [cucumber/cucumber-ruby#1342]
## Summary

Cucumber version 4.0.0.rc.1 seems to be incompatible with Ruby 2.6.0 whereas everything works fine with Ruby 2.5.3

(Official Cucumber version 3.1.2 is working fine with Ruby 2.6.0)

```
Janis-MacBook-Pro:test-demo janijegoroff$ bundle exec cucumber
bundler: failed to load command: cucumber (/Users/janijegoroff/.rbenv/versions/2.6.0/bin/cucumber)
LoadError: cannot load such file -- google/protobuf_c
  /Users/janijegoroff/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/google-protobuf-3.6.1-universal-darwin/lib/google/protobuf.rb:50:in `require'
```

## Environment

* macOS Mojave 10.14.2 (18C54)
* Ruby 2.6.0
* Cucumber 4.0.0.rc.1

**Comment by luke-hill** [comment]
I'm going to close this in: https://github.com/cucumber/cucumber/pull/578

This is only in `master` currently and it's something that still affects JRuby. If you find that this is not working, it is likely to be Mac specific and would need some additional info from yourself.
