### ISSUE TITLE
Method of identifying test being rerun as 'flaky'

### ISSUE THREAD

**Issue by sjoedwards** [cucumber/cucumber-ruby#1347]
## Summary

First issue, so please let me know if you need any more info

This issue highlights that there does not seem to be a property in the JSON report that can be used to clearly identify flaky tests which have previously failed. 

Ideally, the functionality might work in a similar way as suggested in #1333 (a flag to only output the final test run). However I understand the point that we might not want to omit failures as it is a record of the flaky behaviour.

I guess instead, it might be an idea to add a property to outputted JSON of 'attempt', which allows extraction of the number of times that particular test has been run (1 for the first time a test is run, 3 for the second retry etc.)

This would make grabbing the last rerun a lot easier when parsing that JSON file in reporting.

## Current Behavior

Running cucumber with the options `--retry 2`  results in a JSON report that has no clear way of distinguishing when a test is a rerun, or whether it is being run for the first time.

JSON output when using `--retry 2`:

```
      {
        "id": "test-suite;scenario-with-failing-scenario",
        "keyword": "Scenario",
        "name": "Feature test will fail due to flaky test",
        "description": "",
        "line": 7,
        "type": "scenario",
        "steps": [
        ....
```
## Possible Solution

Add an attempt property to the feature JSON output, which correlates to the number of times that test has been attempted to have been run:

```
      {
        "id": "test-suite;scenario-with-failing-scenario",
        "keyword": "Scenario",
        "name": "Feature test will fail due to flaky test",
        "attempt": 1,
        "description": "",
        "line": 7,
        "type": "scenario",
        "steps": [
        ....
```

Then in the second attempt to run the flaky test: 

```
      {
        "id": "test-suite;scenario-with-failing-scenario",
        "keyword": "Scenario",
        "name": "Feature test will fail due to flaky test",
        "attempt": 2,
        "description": "",
        "line": 7,
        "type": "scenario",
        "steps": [
        ....
```

There might be something I'm missing and theres already a way to distinguish tests being re-run in JSON reports. In which case just after some clarity. If theres any merit in the above suggestion I can have a crack at a PR

Thanks all in advance,

**Comment by luke-hill** [comment]
Just because you mentioned maybe attempting a PR. My advice is hold off.

Gherkin 6 and Cucumber4 will attempt to use protocol-buffers to send language agnostic info and the first area we're looking into rewriting is the formatter(s)

**Comment by sjoedwards** [comment]
Thanks @luke-hill, I'll keep an eye out. Do you know at this stage whether the ability to retry is proposed in the new versions of Gherkin and Cucumber?

**Comment by danascheider** [comment]
I think it'd be good to have a way to identify flaky tests in JSON output, but I'd be curious to see what the other maintainers think about that idea and about your specific implementation suggestion before I give it the go-ahead.

**Comment by luke-hill** [comment]
The existing logic will be maintained, however the additional bits you've mentioned haven't been specced yet. But there's no reason against trying to include it if we add it to the spec

**Comment by luke-hill** [comment]
Hi there. As the transforming to a single language reporter is still a way off, there may be some value in merging this in now if you're happy putting something together. I could even possibly pair up / help a little bit.

Currently the way in which the retry runner works is it will immediately retry a failing test. So you could look for the last consecutive instance?

Let me know if you need any more pointers or if you want to collaborate on something.

**Comment by luke-hill** [comment]
Hi @sjoedwards 

I've removed the Slow Burner on this as it's been a while. This means if anyone picks it up in the next few months it'll get worked on. Otherwise it'll get closed then locked in a while as per the regular policy. This helps us clean things up.
