### ISSUE TITLE
Petition to drop 2.2 from CI matrix

### ISSUE THREAD

**Issue by olleolleolle** [cucumber/cucumber-ruby#1348]
## Summary

I want us to drop support for Ruby 2.2

This Issue is about us working hard to support EOL'd versions of Ruby, which the other libraries in Cucumber do not support any longer.

## Expected Behavior

Tests to run green on all supported CI matrix members.

## Current Behavior

- jruby fails
- 2.2 fails

## Possible Solution

Change the CI matrix.

## Steps to Reproduce (for bugs)

1. Example CI failure https://circleci.com/gh/cucumber/cucumber-ruby/2444

## Context & Motivation

The presence of failures reduces contributors' confidence in their own changes.

**Comment by danascheider** [comment]
I agree with this, but I'd also be curious to know what the impact would be on enterprise users since larger organisations tend to be change-averse. I definitely do think the presence of these failures reduces the usefulness of CI.

**Comment by luke-hill** [comment]
Just as a side-note, the following has happened in the last 6 months (Co-operating libraries).

Rails v6 - 2.5 minimum (Extreme)
Selenium-Webdriver v4 - "Will be" 2.4 minimum (Currently 2.3 but will be going up) (Strong)
Capybara (Moderate)
  - v3.0 (2.2 minimum)
  - v3.2 (2.3 minimum)
  - v3.16 (2.4 minimum)
SitePrism (shameless plug) - 2.3 minimum

I can't think of a co-operating library that is used by the majority of the cucumber community where a later upgrade isn't forcing users to 2.3 minimum

My eyes, we can ditch Ruby 2.2 and JRuby 9.1 almost without any issue. JRuby 9.2 I've no idea on, but I know it's tied to rubies which are still in support.

**Comment by luke-hill** [comment]
Given @aslakhellesoy 's work on Fixing up stuff for Ruby 2.6 - I suggest we just cherry-pick this commit into master a4aac741a7b6803a1440aed1c812148a5cd55f0b

**Comment by olleolleolle** [comment]
I like that!

**Comment by danascheider** [comment]
Seconded

**Comment by luke-hill** [comment]
Done this. So Will close this issue as fixed in a4aac74

**Comment by luke-hill** [comment]
#Fail - This isn't fixed and won't be by that commit. We are still in a massive chicken-egg scenario until 3.8 comes out (Which should in theory fix most things)

**Comment by luke-hill** [comment]
This is now a very simple change to make, given the core dependencies in master now have a 2.3 limit (Which actually means 2.2 builds cannot build any more)
