### ISSUE TITLE
Add scenarios with Rule keyword

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-ruby#1365]
We need a few feature files under `features/docs` that use the new `Rule` keyword.

In particular, we should verify that the `pretty` formatter can render it. I can't remember if it renders the `Rule` lines, and if it doesn't, it's fine (ref cucumber/cucumber#757)

**Comment by vincent-psarga** [comment]
I've added two new features here:
 - https://github.com/cucumber/cucumber-ruby/pull/1367/commits/e12075a7b4fcca9236fdf794219cabf52aab2342
 - https://github.com/cucumber/cucumber-ruby/pull/1367/commits/44509e0219bb96944292d385dbcb35f3bed3e82a

Although, I'm not convinced by the examples. Is there some doc I could as descriptions for those features ?
From the docs:

> The purpose of the Rule keyword is to represent one business rule that should be implemented. It provides additional information for a feature. A Rule is used to group together several scenarios that belong to this business rule. A Rule should contain one or more scenarios that illustrate the particular rule.

Would that be enough ? any idea @aslak @mattwynne @sebrose ?

**Comment by aslakhellesoy** [comment]
As long as these feature files are only used to validate/test the syntax and not provide an example of good use, I think these are fine!

**Comment by vincent-psarga** [comment]
Ok, works for me :)
