### ISSUE TITLE
Error while installing cucumber gem in ruby

### ISSUE THREAD

**Issue by pandyachirag** [cucumber/cucumber-ruby#1376]
C:>gem install cucumber --backtrace ./iruby-0.2.9 gem
ERROR: While executing gem ... (TypeError)
Type mismatch (expect [1] but 3 present)
C:/Ruby23-x64/lib/ruby/2.3.0/win32/registry.rb:646:in read' C:/Ruby23-x64/lib/ruby/2.3.0/win32/registry.rb:694:in read_s'
C:/Ruby23-x64/lib/ruby/2.3.0/win32/resolv.rb:64:in block in get_info' C:/Ruby23-x64/lib/ruby/2.3.0/win32/registry.rb:435:in open'
C:/Ruby23-x64/lib/ruby/2.3.0/win32/registry.rb:542:in open' C:/Ruby23-x64/lib/ruby/2.3.0/win32/resolv.rb:62:in get_info'
C:/Ruby23-x64/lib/ruby/2.3.0/win32/resolv.rb:20:in get_resolv_info' C:/Ruby23-x64/lib/ruby/2.3.0/resolv.rb:972:in default_config_hash'
C:/Ruby23-x64/lib/ruby/2.3.0/resolv.rb:989:in block in lazy_initialize' C:/Ruby23-x64/lib/ruby/2.3.0/resolv.rb:982:in synchronize'
C:/Ruby23-x64/lib/ruby/2.3.0/resolv.rb:982:in lazy_initialize' C:/Ruby23-x64/lib/ruby/2.3.0/resolv.rb:360:in block in lazy_initialize'
C:/Ruby23-x64/lib/ruby/2.3.0/resolv.rb:358:in synchronize' C:/Ruby23-x64/lib/ruby/2.3.0/resolv.rb:358:in lazy_initialize'
C:/Ruby23-x64/lib/ruby/2.3.0/resolv.rb:518:in fetch_resource' C:/Ruby23-x64/lib/ruby/2.3.0/resolv.rb:512:in each_resource'
C:/Ruby23-x64/lib/ruby/2.3.0/resolv.rb:493:in getresource' C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/remote_fetcher.rb:99:in api_endpoint'
C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/source.rb:47:in api_uri' C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/source.rb:86:in dependency_resolver_set'
C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/resolver/best_set.rb:24:in block in pick_sets' C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/source_list.rb:98:in each'
C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/source_list.rb:98:in each_source' C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/resolver/best_set.rb:23:in pick_sets'
C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/resolver/best_set.rb:29:in find_all' C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/resolver/installer_set.rb:152:in find_all'
C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/resolver/installer_set.rb:55:in add_always_install' C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/dependency_installer.rb:474:in resolve_dependencies'
C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/commands/install_command.rb:239:in install_gem' C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/commands/install_command.rb:300:in block in install_gems'
C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/commands/install_command.rb:296:in each' C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/commands/install_command.rb:296:in install_gems'
C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/commands/install_command.rb:203:in execute' C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/command.rb:308:in invoke_with_build_args'
C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/command_manager.rb:169:in process_args' C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/command_manager.rb:139:in run'
C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/gem_runner.rb:55:in run' C:/Ruby23-x64/bin/gem.cmd:29:in

**Comment by luke-hill** [comment]
Can I just clarify are you trying to install an older version of cucumber and not one of the latest ones?

what happens when you just do `gem install cucumber`

**Comment by pandyachirag** [comment]
When I do gem install cucumber, I get following -

C:\>gem install cucumber
ERROR:  While executing gem ... (TypeError)
    Type mismatch (expect [1] but 3 present)

**Comment by aslakhellesoy** [comment]
@pandyachirag are you able to install other gems? Can you successfully run `gem install gherkin`?

**Comment by aslakhellesoy** [comment]
Your command line looks suspicious:

```
gem install cucumber --backtrace ./iruby-0.2.9 gem
```

Try this instead:

```
gem install cucumber
```

**Comment by pandyachirag** [comment]
> @pandyachirag are you able to install other gems? Can you successfully run `gem install rspec`?

I had few gems installed successfully. But, after those few, can't install any gem.

**Comment by pandyachirag** [comment]
> Your command line looks suspicious:
> 
> ```
> gem install cucumber --backtrace ./iruby-0.2.9 gem
> ```
> 
> Try this instead:
> 
> ```
> gem install cucumber
> ```

I tried that earlier. Since it didn't work, I tried the one mentioned in the issue

**Comment by luke-hill** [comment]
Judging from your install dir. Are you on windows? Did you modify the installation path of ruby?

I know the default windows 2.3 installer installs to `C:\Ruby23` yours looks slightly different.

**Comment by aslakhellesoy** [comment]
> But, after those few, can't install any gem.

It's not related to Cucumber then. Your Ruby installation seems hosed. I recommend you reinstall Ruby and start over.
