### ISSUE TITLE
Test case name should be taken from the scenario

### ISSUE THREAD

**Issue by vincent-psarga** [cucumber/cucumber-ruby#1382]
## Summary

_Originally posted by @mattwynne in https://github.com/cucumber/cucumber-ruby-core/pull/188#issuecomment-572996204_

Just creating an issue to avoid loosing the idea/feedback, I need to dig deeper to understand exactly what is happening here.

## Current Behavior

~~~
~~~

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by mattwynne** [comment]
Here's how it used to work:

For this gherkin:
```
Scenario: Make cheese
  Given add some <ingredient>

  Examples: Dairy product
    | ingredient |
    | milk |
```

The test case `.to_s` would be `Make Cheese, Dairy Product (#1)`

For a regular scenario it's just the name of the scenario.

I would ignore this until we see a need for it.

**Comment by jenisys** [comment]
@mattwynne
Just a hint (if that is any help for you): 
In `behave`, I provided ScenarioTemplate/Outline naming schema that could be tweaked by a user to his/her needs by using the config file, like:

```
"{name} -*- {examples.name} @{row.id}"

# HINTS:
#  name = scenario.name = "Make cheese"
# examples.name = "Dairy product"
# row.id = 1.1. (Example_table.index, row.index in Examples table)
# row.index = 1 (for row with ingredient = "milk")
```

The underlying internal entity type is a ScenarioOutline/ScenarioTemplate (at least for me),
even when the new Gherkin version "calls" them all "Scenario" (or ...).
Therefore, a twist in the behaviour compared to a "normal" Scenario is justified IMHO.

SEE ALSO:
* https://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.5.html#scenario-outline-improvements
* https://github.com/behave/behave/blob/master/features/scenario_outline.name_annotation.feature#L106
