### ISSUE TITLE
Please include Steps in Junit Test output

### ISSUE THREAD

**Issue by nadethoughts** [cucumber/cucumber-ruby#1384]
## Summary

Junit reports only include information about whether or not a test failed, but doesn't include test steps with pass/fail information at the step level, like cucmber-jvm does.

## Expected Behavior

I have attached a file with the ideal state of the junit report included
![cucumber_steps](https://user-images.githubusercontent.com/60153730/72835178-41fb5380-3c58-11ea-88f4-c6e503b4588b.png)

## Current Behavior

I have attached a file that has the current state of the junit report.
<img width="673" alt="ruby cucumber junit report current state" src="https://user-images.githubusercontent.com/60153730/72835496-cf3ea800-3c58-11ea-8aee-5fd71bb9d714.png">

## Context & Motivation

I am trying to use the junit report in Zephyr. In order to have complete functionality of zephyr, I need to have the steps in the Junit reports. This way I can full in the tests and generate test cases from the junit reports with the test steps in them.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by luke-hill** [comment]
Just so you have an idea, currently we are doing some extensive work to rewrite the formatters in a single place using cucumber messages (Which uses protobuf).

This is still ongoing and has a few tweaks still being made - as such, any work to fix / rewrite the existing formatters is unlikely to gain much traction.

That being said, if you could identify roughly what areas need fixing or submit a PR, I will happily review it. But the existing maintainers are unlikely to devote much time to this.
