### ISSUE TITLE
Timeout caused by around hook does not run after hooks

### ISSUE THREAD

**Issue by newtewt** [cucumber/cucumber-ruby#1405]
## Summary
Following the [documentation](https://cucumber.io/docs/cucumber/api/#hooks) on using an around hook to cause a timeout causes after hooks to not be run. This leaves any clean up done in after not to happen. Not sure if this is fixable or documentation should be updated to detail that after hooks will not be executed.  

## Expected Behavior

When an around hook times out it should still process the after hooks. 

## Current Behavior

When the timeout occurs it kills the test run which kills any after hooks that might need run. 

## Possible Solution

Allow an easy way to trigger the hooks that might need to be run after catching the timeout exception. Provide another way to timeout a test. If this isn't possible I can submit a pull request to update the document to include a note indicating after hooks cannot be ran if the timeout is used. 

## Steps to Reproduce (for bugs)

I've created a very simple project [here](https://github.com/newtewt/simple_cucumber_hooks) that displays the issue.  

1. clone the project
2. Run in terminal `bundle install`
3. Run in terminal `cucumer`

## Context & Motivation

Trying to follow the example in the docs to timeout tests that run longer than a specified period of time. In my case it is anything over 5 minutes. 

## Your Environment

* Version used: 3.1.2
* Operating System and version: OSX 10.15.3 Ruby 2.6.3
* Link to your project: https://github.com/newtewt/simple_cucumber_hooks

**Comment by luke-hill** [comment]
The code example there is poor and I remember a while ago not being happy about it being there, it's very bad ruby advice.

Around hooks also are a bit weird and we have some existing issues that people have picked up and triaged when they have time (Such as the scenario state not updating).

If you're using that code word for word, then I would advise against it. I'll have a chat with some of the other regular ruby people to see if they're ok with me removing it from the docs.

cc/ @olleolleolle @mvz 
For comparison @mpkorstanje do you have Around hooks in JVM?

**Comment by mpkorstanje** [comment]
No. No around hooks in JVM. Also no timeouts. There are libs for that.

**Comment by vincent-psarga** [comment]
and we have no notion of `Around` in the Hook message either. I think they'll disssapear in one of the next releases anyway.

**Comment by mvz** [comment]
It looks like the hook order is such that the After hook runs inside of the Around, so the timeout aborts the running of the After hooks as well.
