### ISSUE TITLE
Can't log objects

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-ruby#1410]
## Summary

Can't `log` objects

## Expected Behavior

This statement:

```ruby
log Date.parse('2020-02-03')
```

prints:

```
2020-02-03
```

## Current Behavior

I get an error:

```
Cucumber::LogTypeInvalid (Cucumber::LogTypeInvalid)
```

## Possible Solution

Allow any object and call `#to_s` on it

## Your Environment

* Version used: `4.0.0.rc.6`
* Operating System and version: `MacOS`

**Comment by vincent-psarga** [comment]
Ok it makes sense. That said, originally, we decided to go for an approach where the user had to handle himself the `to_s` part and raie an exception if something than a String was logged.
https://github.com/cucumber/cucumber/issues/897#issuecomment-586639574

Should we also make the change in the other Cucumber implementations ?
