### ISSUE TITLE
ETA for 4.x stable release?

### ISSUE THREAD

**Issue by DannyBen** [cucumber/cucumber-ruby#1417]
Is there any estimation as to when the 4.x version will leave RC state?
The current stable version uses an old cucumber-core version, which throws a warning when executed:

```
/gems/ruby-2.7.0/gems/cucumber-core-3.2.1/lib/cucumber/core/test/result.rb:12:
warning: calling private without arguments inside a method may not have the intended effect
```

Also, I guess the lack of a stable release prevents the other dependants (e.g. cucumber-rails) to update, so even if I wanted to use the RC version, I can't at this time (since cucumber-rails does not have an RC release that uses the cucumber RC release...).

**Comment by vincent-psarga** [comment]
That's an easy one: 24th of May if everything goes as expected :)

We want to leave a month between the latest RC and the final release, we hope the RC5 to be the latest one but we had to change the `--out=url` behavior which explains this slight delay.

**Comment by DannyBen** [comment]
> That's an easy one: 24th of May if everything goes as expected :)

That is pleasantly surprising. Thank you.

**Comment by joallard** [comment]
@vincent-psarga All my encouragements, shipping releases is hard!

I got here on trying out Cuc for a long time in years, having a bit of a hard time with the setup.

I'll give a try on master!
