### ISSUE TITLE
Missing jruby-win32ole gem: jruby -S gem install jruby-win32ole

### ISSUE THREAD

**Issue by AnmolNarang** [cucumber/cucumber-ruby#1419]
After updating Gem to 4.0.0 getting below error

Windows 10
Jruby 9.2.9.0 or latest

19:12:54.650 !!!! Missing jruby-win32ole gem: jruby -S gem install jruby-win32ole
19:12:54.651 LoadError: no such file to load -- jruby-win32ole
19:12:54.651           require at org/jruby/RubyKernel.java:970
19:12:54.651            <main> at E:/automation-engineering/tools/jruby-9.2.0.0/lib/ruby/stdlib/jruby/win32ole/stub.rb:3
19:12:54.651           require at org/jruby/RubyKernel.java:970
19:12:54.651   block in (root) at E:/automation-engineering/tools/jruby-9.2.0.0/lib/ruby/gems/shared/gems/sys-uname-1.2.1/lib/sys/windows/uname.rb:1
19:12:54.651           require at org/jruby/RubyKernel.java:970
19:12:54.651            (root) at E:/automation-engineering/tools/jruby-9.2.0.0/lib/ruby/gems/shared/gems/sys-uname-1.2.1/lib/sys/windows/uname.rb:6
19:12:54.651            <main> at uri:classloader:/jruby/kernel/kernel.rb:1
19:12:54.651           require at org/jruby/RubyKernel.java:970
19:12:54.651            <main> at uri:classloader:/jruby/kernel/kernel.rb:13
19:12:54.651           require at org/jruby/RubyKernel.java:970
19:12:54.651            <main> at E:/automation-engineering/tools/jruby-9.2.0.0/lib/ruby/gems/shared/gems/sys-uname-1.2.1/lib/sys/uname.rb:14
19:12:54.651           require at org/jruby/RubyKernel.java:970
19:12:54.651            <main> at E:/automation-engineering/tools/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cucumber-4.0.0/lib/cucumber/runtime.rb:1
19:12:54.651           require at org/jruby/RubyKernel.java:970
19:12:54.651            <main> at E:/automation-engineering/tools/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cucumber-4.0.0/lib/cucumber/runtime.rb:13
19:12:54.651              load at org/jruby/RubyKernel.java:994
19:12:54.651            <main> at E:\automation-engineering\tools\jruby-9.2.0.0\bin\cucumber:23

**Comment by luke-hill** [comment]
So as semi-relevant piece of info. JRuby 9.2 is the only JRuby we "unofficially" support. There are some limitations and we don't run it in CI as it was conflicting a lot with messages.

I appreciate this probably isn't the best news. I will try dig into this myself in the next week or so when I have time.

**Comment by karamosky** [comment]
The readme [here](https://github.com/enebo/jruby-win32ole) says "It is distributed as a gem that comes bundled/packaged with jruby's mainline windows distros."
Worth checking if you can start an irb session (```jruby -S irb```) and try to require it

**Comment by AnmolNarang** [comment]
Sorry for late reply,  
Current stats we have and it is working 

Jruby 9.2.9.0
and Cucumber 3.1.2

**Comment by AnmolNarang** [comment]
> The readme [here](https://github.com/enebo/jruby-win32ole) says "It is distributed as a gem that comes bundled/packaged with jruby's mainline windows distros."
> Worth checking if you can start an irb session (`jruby -S irb`) and try to require it



> I'll take a look at this in the next week or so. I know JRuby is a bit trickier for cucumber. We have had some issues with it in the past.
> 
> Does this work fine with the latest 3.x revisions? I know you said it doesn't work with 4.0 but could you try with 3.2.

Sorry for late reply,
Current stack I have and it is working

Jruby 9.2.9.0
and Cucumber 3.1.2

**Comment by AnmolNarang** [comment]
> The readme [here](https://github.com/enebo/jruby-win32ole) says "It is distributed as a gem that comes bundled/packaged with jruby's mainline windows distros."
> Worth checking if you can start an irb session (`jruby -S irb`) and try to require it

It didn't complain. 

![image](https://user-images.githubusercontent.com/27833007/84918246-5704d300-b08e-11ea-8da4-e488fe18c36a.png)

**Comment by AnmolNarang** [comment]
> > The readme [here](https://github.com/enebo/jruby-win32ole) says "It is distributed as a gem that comes bundled/packaged with jruby's mainline windows distros."
> > Worth checking if you can start an irb session (`jruby -S irb`) and try to require it
> 
> > I'll take a look at this in the next week or so. I know JRuby is a bit trickier for cucumber. We have had some issues with it in the past.
> > Does this work fine with the latest 3.x revisions? I know you said it doesn't work with 4.0 but could you try with 3.2.
> 
> Sorry for late reply,
> Current stack I have and it is working
> 
> Jruby 9.2.9.0
> and Cucumber 3.1.2

Ok, I just updated cucumber to 3.2.0 and it worked. didn't complain. 

current stacks
Jruby 9.2.9.0
Cucumber 3.2.0

**Comment by luke-hill** [comment]
I couldn't readily reproduce this, but I may be doing something different to you.

Can you create an SSCCE - sscce.org and give me a way of accessing it. To validate your findings.
