### ISSUE TITLE
Small Bug/Unintended Feature - CLI: Show Profiles

### ISSUE THREAD

**Issue by luke-hill** [cucumber/cucumber-ruby#1428]
**Describe the bug**
When trying to show what profiles are set (Not sure if this is "meant" to exist), a weird minor bug shows where it says "ofiles" not found.

**To Reproduce**
1. In any cucumber project (That has profiles), run the cli command `bundle exec cucumber -profiles` (Note single hyphen)
2. Observe the output says something like
```
Could not find profile: 'rofiles'

Defined profiles in cucumber.yml:
  * default
  * wip
```
**Expected behavior**
1. The first line shouldn't be shown

**Additional context**
This may be an inadvertent feature, that isn't meant to exist. I found this by working on a new project that sets cucumber.yml in some far-flung folder, so I wanted to see which profiles were set without needing to grep the codebase

**Comment by olleolleolle** [comment]
@luke-hill I get curious, was the option passed with a `-` single hyphen, as a "short option"? Or as a `--` double hyphen, a long option?

**Comment by luke-hill** [comment]
Single one. Double one gives a different error.

maybe this is some weird use case or something I don't know. I think this is half a bug, half a feature.

**Comment by vincent-psarga** [comment]
Isn't that more linked to the terminal/shell used ?
From what I understand:

```
bundle exec cucumber -profiles
```

is equivalent to typing:

```
bundle exec cucumber -p rofiles
bundle exec cucumber --profiles rofiles
```

**Comment by luke-hill** [comment]
Possibly, but then it also dumps all of the profiles that have been set, which I think is neat.

If this is an unintended consequence, could we maybe add a way of returning profiles? I could probably dig in and find this out and code it as well. Just trying to gauge the situation first.

**Comment by vincent-psarga** [comment]
Maybe adding another option `--profiles` to list them all could be interesting indeed :)
