### ISSUE TITLE
cucumber: Cucumber 4.x does not work on JRuby 9.1.7 on OSX

### ISSUE THREAD

**Issue by enkessler** [cucumber/cucumber-ruby#1429]
## Summary

Exactly what it says on the tin: Cucumber 4.x does not work on JRuby 9.1.7 on OSX.

## Expected Behavior

Because 4.x is declared as supporting Ruby 2.3 and because JRuby 9.1.7 is equivalent to Ruby 2.3 and because earlier versions worked fine with the 9.1.7/OSX combination, I would expect it to work.

## Current Behavior

It does not work.

~~~
LoadError: Unsupported platform: x86_64-darwin
           require at org/jruby/RubyKernel.java:961
            <main> at /Users/travis/.rvm/rubies/jruby-9.1.7.0/lib/ruby/stdlib/ffi/ffi.rb:69
           require at org/jruby/RubyKernel.java:961
            <main> at /Users/travis/.rvm/rubies/jruby-9.1.7.0/lib/ruby/stdlib/ffi.rb:1
           require at org/jruby/RubyKernel.java:961
            <main> at /Users/travis/.rvm/rubies/jruby-9.1.7.0/lib/ruby/stdlib/ffi.rb:1
           require at org/jruby/RubyKernel.java:961
            <main> at /Users/travis/.rvm/gems/jruby-9.1.7.0/gems/ffi-1.13.0-java/lib/ffi.rb:1
           require at org/jruby/RubyKernel.java:961
  require_relative at uri:classloader:/jruby/kernel/kernel.rb:13
            <main> at /Users/travis/.rvm/gems/jruby-9.1.7.0/gems/ffi-1.13.0-java/lib/ffi.rb:27
           require at org/jruby/RubyKernel.java:961
            <main> at /Users/travis/.rvm/gems/jruby-9.1.7.0/gems/sys-uname-1.2.1/lib/sys/unix/uname.rb:1
           require at org/jruby/RubyKernel.java:961
            <main> at /Users/travis/.rvm/gems/jruby-9.1.7.0/gems/sys-uname-1.2.1/lib/sys/unix/uname.rb:1
           require at org/jruby/RubyKernel.java:961
            <main> at /Users/travis/.rvm/gems/jruby-9.1.7.0/gems/sys-uname-1.2.1/lib/sys/uname.rb:1
           require at org/jruby/RubyKernel.java:961
            <main> at /Users/travis/.rvm/gems/jruby-9.1.7.0/gems/sys-uname-1.2.1/lib/sys/uname.rb:16
              load at org/jruby/RubyKernel.java:979
            <eval> at /Users/travis/.rvm/gems/jruby-9.1.7.0/gems/cucumber-4.0.0/lib/cucumber/runtime.rb:1
              eval at org/jruby/RubyKernel.java:1000
            <main> at /Users/travis/.rvm/gems/jruby-9.1.7.0/bin/jruby_executable_hooks:24
~~~

## Possible Solution

From what I was told by a developer on the project, this slipped through because JRuby 9.1.7 is not included in Cucumber's CI. I suggest including it and any other officially supported platforms.

## Steps to Reproduce (for bugs)

Here it is one of my builds failing when I use 4.x
https://travis-ci.org/github/enkessler/cuke_modeler/builds/694205239

Here it is happy again when I revert to an earlier version of Cucumber (2.2.0)
https://travis-ci.org/github/enkessler/cuke_modeler/builds/694232464

## Context & Motivation

Previous versions of Cucumber worked for JRuby 9.1.7 on OSX. I have had to restrict which version of the `cucumber` gem I use so as to not encounter the problem. Currently, this means using `cucumber` 2.2.0, which is rather old (see cucumber/cucumber#1063).

## Your Environment

* Version used: 4.0.0
* Operating System and version: OSX with JRuby 9.1.7
* Link to your project: https://github.com/enkessler/cuke_modeler

**Comment by vincent-psarga** [comment]
Ruby 2.3 EOL was two year old, and I'm not sure we'll support it much longer to be honest (or at least, won't do much efforts to keep it supported).
If you want to add 9.1.7 to the CI and fix the failing test, that could be cool but I don't think this will be our focus for the coming months/weeks.

**Comment by luke-hill** [comment]
Also just to add to this we've made steps on removing Ruby 2.3 from Cucumber-rails and have also started removing Rails 4.2 (Both EOL options). So I think the way forward is to start being a bit more robust with only supporting software that is in life, or at least newly EOL (With the case of cucumber 2.4)

Also I think some of the new packages which cucumber depends on are likely to only support 2.4+ going forwards as well, although Vincent can probably explain those better

**Comment by vincent-psarga** [comment]
We've cut down dependencies with Cucumber (mainly to ease support with Windows). I recall having some troubles with some of the test libraries working against 2.3 and to be honest, I prefer dropping 2.3 support than fighting/rewriting libs to support it.
