### ISSUE TITLE
AfterConfiguration - Name/Running Context

### ISSUE THREAD

**Issue by luke-hill** [cucumber/cucumber-ruby#1442]
**Describe the bug**
AfterConfiguration, ideally should be renamed, and have it's running context altered.

**To Reproduce**
1) in `env.rb` mix in some Helpers to the World
2) Create an `AfterConfiguration` hook.
3) Try to access World Helpers - You cannot (The running context is `main`)

**Expected behavior**
AfterConfiguration should run in the World instance

**Your Environment**
 - Versions used 3.2.0
 - Operating System and version Ubuntu 18.04LTS
 - Cucumber Ruby on Browserstack / Locally

**Additional context**
This should be renamed to `BeforeAll` as that is what it is, and it would hint it would run first. `AfterConfiguration` running before a `Before` is a bit confusing.

**Comment by vincent-psarga** [comment]
That could totally make sense I think (while reading your comment I was surprised an `After...` was running before other hooks).

It could also be interesting to check if what happens in those steps is correctly shown in the messages (and I'm fairly sure it is not :/ )

**Comment by luke-hill** [comment]
I'm happy to dedicate some time diving into this / coding it. Would need a bit of a push as I tried scanning the hook code a while back for the long standing "Around hooks" issue (I know this is going to be redundant soon), and got so confused.

**Comment by luke-hill** [comment]
Related issue: https://github.com/cucumber/cucumber-js/issues/1393
