### ISSUE TITLE
NoMethodError (private method `puts' called for #<Cucumber::Formatter::Interceptor::Pipe:0x00007fc8a5bc0c08>)

### ISSUE THREAD

**Issue by haonv88** [cucumber/cucumber-ruby#1445]
**Describe the bug**
When using the JUnit Formatter for --format , I got error `NoMethodError (private method `puts' called for #<Cucumber::Formatter::Interceptor::Pipe:0x00007fc8a5bc0c08>)`

**To Reproduce**
1. Go to rails console
2. require 'cucumber/formatter/interceptor'
3. interceptederr = Cucumber::Formatter::Interceptor::Pipe.wrap(:stderr)
4. $stderr.puts "test" # raise error `NoMethodError (private method `puts' called for #<Cucumber::Formatter::Interceptor::Pipe:0x00007fc8a5bc0c08>)`

**Expected behavior**
Should not raise error. 

**Context & Motivation**

As I research, in cucumber-4.1.0/lib/cucumber/formatter/interceptor.rb:34
$stderr.puts("test") will invoke method
```
        def method_missing(method, *args, &blk)
          @pipe.send(method, *args, &blk) || super
        end
```
@pipe.send(method, *args, &blk) will log the error and return nil, then it keeps calling `super` and raise error

**Screenshots**
<img width="1295" alt="Screen Shot 2020-07-15 at 15 01 21" src="https://user-images.githubusercontent.com/7000603/87519638-18256580-c6ac-11ea-97f6-eed4c243cb69.png">

**Your Environment**
 - Versions used [4.1.0]
 - Operating System and version [MacOs 10.15.5 ]

**Comment by vincent-psarga** [comment]
Thanks for the report.

I'm trying to investigate on what may cause this issue. Do you have a full stack-trace by any chance or is it the same than when you use the method to reproduce the issue ?

**Comment by haonv88** [comment]
Hi @vincent-psarga I don't have full stack-trace. 
```
          command: |
            [[ -n $SKIP_EXECUTION ]] || (mkdir -p ~/cucumber && \
            ./bin/cucumber --format junit \
                                 --out ~/cucumber/junit.xml \
                                 $(circleci tests glob "features/**/*.feature" | circleci tests split --split-by=filesize))
```
When I run cucumber in CI. The above error (`NoMethodError private method`) will hide the real errors from ruby libraries, because `$stderr.puts` does not work anymore.

**Comment by luke-hill** [comment]
@haonv88 I think what vincent is saying is in your screenshot it says `"traceback from irb (1)"` could you paste the next 10-20lines of that.

**Comment by haonv88** [comment]
Hi @luke-hill There are no other lines for the traceback. I think it's easy to reproduce, you can do the same as the screenshot to see the error.

**Comment by vincent-psarga** [comment]
In fact, what I'd like to understand is how cucumber ends up trying to call `puts` directly on `$stderr` (as usually the process uses named streams for I/O).
And I was not able to reproduce the issue, at least when running cucumber cli (your way to reproduce the bug works great and will certainly be used as the non-regression test :) )

I'm wondering if there's a step definition or something else trying to `puts` directly on `$stderr` for example, mainly to fix the bug in a more robust way.

**Comment by haonv88** [comment]
<img width="1642" alt="Screen Shot 2020-07-22 at 09 26 06" src="https://user-images.githubusercontent.com/7000603/88127336-8d89bc80-cbfd-11ea-8fbb-8d03ae82d5ce.png">

There are many places in my gem files which call `puts` directly on `$stderr`.

**Comment by vincent-psarga** [comment]
Yes that's what I was looking for.

I think the issue was introduced in [this commit](https://github.com/cucumber/cucumber-ruby/commit/07d9d31a6961e514f4611368cbe221f579005645) and, as I understand it, we were calling `super` when as calling `puts` on the stream does not return anything.

I've pushed a commit fixing that in #1449
