### ISSUE TITLE
[QUESTION] Is it possible to explicitly define named after hooks strict order?

### ISSUE THREAD

**Issue by vitalyk** [cucumber/cucumber-ruby#1447]
## Summary

The reason I'm asking is the following issue that I have recently faced:

I have a Ruby based test framework which is uses gem cucumber version of 3.2
In the framework I have some named After hooks
After the test is completed - after hooks are always executed in the following order:
```
After(@user_story)
After(@upload_image) 
After@remove_user
```

Now I want to make an update to the latest one cucumber gem version which is 4.1.0
and I've found a side effect that order is different:

```
After(@upload_image)
After(@remove_user)
After(@user_story)
```

Such order brakes my test.  So I was looking at the way of specifying some rule for the `After(@remove_user)` hook, which could setup hook order as the very last one,  but I can't figure out how to do that.
Thanks ahead for your reply.

**Comment by vincent-psarga** [comment]
That's surprising as I would have thought `Hooks` would execute in the order of their definition.

Two questions to ease finding where the issue might come from:
 - are all the `Hooks` defined in a single file ?
 - how to you load those files ? (could you try to set `Cucumber.use_legacy_autoloader` to true and see if that reverts to your original behaviour ([some more infos about that here](https://cucumber.io/blog/open-source/tweaking-cucumber-rubys-auto-loader/) )

**Comment by vitalyk** [comment]
@vincent-psarga Looks like your first suggestion has helped me, I've moved problematic tag into a separate .rb  hook file and also have reviewed how my files are required in my `env.rb` So I also didn't have to use `Cucumber.use_legacy_autoloader`
