### ISSUE TITLE
Security Notice & Bug Bounty - HTML Injection - huntr.dev

### ISSUE THREAD

**Issue by huntr-helper** [cucumber/cucumber-ruby#1448]
# Overview

[cucumber](https://rubygems.org/gems/cucumber) is behavior Driven Development with elegance and joy.

Affected versions of the package are vulnerable to HTML Injection. The HTML formatter appends any scenario output to the HTML without escaping HTML tags in the messages. This way, any output from the steps gets injected into the report page. In the simple case, this won't display the message as expected. When combined with for example capybara and CI environments this opens up the possibility of an XSS attack from the user input on the environment being tested.

# Bug Bounty

We have opened up a bounty for this issue on our bug bounty platform. Want to solve this vulnerability and get rewarded 💰? Go to https://huntr.dev/

We will submit a pull request directly to your repository with the fix as soon as possible. Want to learn more? Go to https://github.com/418sec/huntr 📚

_Automatically generated by @huntr-helper..._

**Comment by aslakhellesoy** [comment]
The HTML formatter is now based on https://github.com/cucumber/cucumber/tree/master/html-formatter which again is based on React, which I believe is pretty good at avoiding this.

Feel free to reopen this issue with more details such as:
* The affected cucumber version
* A [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by huntr-helper** [comment]
### Bug Bounty

We have opened up a bounty for this issue on our bug bounty platform. Want to solve this vulnerability? Go to https://huntr.dev/

We will submit a pull request directly to your repository with the fix as soon as possible. Want to learn more? Go to https://github.com/418sec/huntr 📚

_Automatically generated by @huntr-helper..._
