### ISSUE TITLE
Cannot map datatable headers if one header is a prefix of another

### ISSUE THREAD

**Issue by mrdaniellewis** [cucumber/cucumber-ruby#1450]
**Describe the bug**

An error is raised for `map_headers` on a `DataTable` if one header value is a prefix of another header value.

**To Reproduce**

```ruby
DataTable.from([["ant", "anteater"], [1, 2]]).map_headers { |h| h.capitalize }.hashes
# RuntimeError Exception: 2 headers matched "ant": ["ant", "anteater"]
```

**Expected behavior**
`[{"Ant"=>1, "Anteater"=>2}]`

**Your Environment**

Ruby 2.6.6p146
Cucumber 4.1.0

**Additional context**

Appears to be due to this PR: https://github.com/cucumber/cucumber-ruby/commit/7b9825084e883aa139d220f1f482eb84a3c67a3b#diff-0466a7e3105b8e1a9e19cb8b0750f74fR510

**Comment by gleonet** [comment]
Same issue
```
RuntimeError Exception: 3 headers matched "name": ["name", "short_name", "full_name"]
```

Is there a solution? Or a better way to map the headers?

**Comment by luke-hill** [comment]
This is something I need to fix. We have identified the problematic area. I can try work on this in the coming weeks.
