### ISSUE TITLE
[QUESTION] How to get rid of warning --format=json is deprecated - please improve documentation description

### ISSUE THREAD

**Issue by vitalyk** [cucumber/cucumber-ruby#1451]
Dear team,
I've recently updated my Ruby based test framework to the latest cucumber gem of v.4.1.0
Now I'm getting warning
```
WARNING: --format=json is deprecated and will be removed after version 5.0.0.
Please use --format=message and stand-alone json-formatter.
json-formatter homepage: https://github.com/cucumber/cucumber/tree/master/json-formatter#cucumber-json-formatter.
```
According to the link reference it is suggested to use
```
cucumber --format protobuf:cucumber-messages.bin
cat cucumber-messages.bin | cucumber-json-formatter > cucumber-results.json
```
with some example
```
../fake-cucumber/javascript/bin/fake-cucumber \
--results=random \
../gherkin/testdata/good/*.feature \ | 
go/dist/json-formatter-darwin-amd64
```
But it is not really clear how to do that.

Mentioned warning comes from my cucumber.yml where I have default profile and I use json output for my reporting:
```
default:
  -r features
  --expand -f pretty --color
  -f json -o reports/cucumber.json
```

**Comment by luke-hill** [comment]
I think potentially a step by step guide here would be useful. What's more. The team I'm working on uses the old json formatter and is due to upgrade to cucumber4 soon. So I'm happy to add in my experiences in some form of working update as/when we get round to it.

**Comment by vincent-psarga** [comment]
I think I'll need to spend some time fixing the documentation about that, you're not the first one raising this issue.
I'll see for a draft documentation and a link displayed in the deprecation warning.

**Comment by matusnovak** [comment]
I have tried to follow the documentation to use a protobuf formatter, but I assume the formatter is not available? If I am reading it correctly, only these https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/cli/options.rb#L14-L28 formatters are available?

I don't mind using the deprecated json, but once it is removed, it creates a problem. Is protobuf formatter going to be implemented in the future so that we can use cucumber-json-formatter?

**Comment by vincent-psarga** [comment]
the protobuf formatter is the `message` formatter, so it's already implemented as part of the `4.x` releases of `cucumber-ruby`.

**Comment by matusnovak** [comment]
Ah, thanks! I did not realize that.

**Comment by vincent-psarga** [comment]
> Ah, thanks! I did not realize that.

Well, the documentation is definitely not clear enough (is any extra proof was needed :/ ), so it's understandable that you did not figure that out.
Hopefully I'll be able to squeeze in some extra documentation soon enough to ease that in the next release.
