### ISSUE TITLE
undefined method `outline?' for #<Cucumber::Core::Test::Case: error on cucumber v 4.1.0

### ISSUE THREAD

**Issue by cristinavelican** [cucumber/cucumber-ruby#1455]
Hello,

I my Ruby project, in the Before hooks i am having the following piece of code to grab the information of the scenario outline (name, keywork etc)

Before do |scenario|
@all_sources = scenario.outline? ? scenario.scenario_outline.all_source : scenario.all_source
  @scenario_script << @all_sources[0].keyword.to_s<<":"
  @scenario_script << @all_sources[0].to_s
end

Using cucumber gem versions 3.1.2 or 3.2.0, the script works without any issues, but when recently upgrading to the newest cucumber versio 4.1.0, I am retrieving the following error:

undefined method `outline?' for #<Cucumber::Core::Test::Case:

Do I need to install other dependency gems to make it work with this new cucumber version?

**Comment by luke-hill** [comment]
This is a similar issue to the one outlined here: https://github.com/cucumber/cucumber-ruby/issues/1432
