### ISSUE TITLE
Specifying --publish and no formatter does not default to using pretty formatter

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-ruby#1468]
This is because `--publish` registers as a formatter internally, causing cucumber to think there is no need to default to pretty

**Comment by aslakhellesoy** [comment]
bump

**Comment by cbliard** [comment]
Experienced by this customer https://app.intercom.com/a/apps/fy7zk1ud/inbox/inbox/all/conversations/160128100001667

>How to temporarily disable this feature, so that I can see results and failures in command line when building the cucumber tests ?

**Comment by meliesan** [comment]
If I may add to previous issue experienced: (using cucumber/capybara ruby)
The undefined step definitions "code snippet" is also not provided in the report and unable to see it in the console either.

I have had to downgrade to Cucumber 5.1.3 but still seeing following issues, which requires me to still use the report; 

1. If I add "default: --publish-quiet" in cucumber.yml, I am able to see the code snippet for undefined steps in the console but not the details of the failures.
2. If I add "default: --publish" to cucumber.yml, I see the details of failures in the report only but no undefined steps code snippet in neither console nor the report.
3. If I omit any reference to the report, i.e. "--publish" or "--publish-quiet" in the cucumber.yml file, I see the code snippet in the console only but not the details of failures.

Currently I have to comment/uncomment the line in cucumber.yml file depending on if I want to see the code snippet in the console or the failures in the report.
Hope this helps !
Mel

**Comment by meliesan** [comment]
I found the workaround to have both the url to the cucumber report and the details at runtime in the console.
in cucumber.yml, I added : 
`default: --publish --format pretty`
it's a little bit slow to kickoff the tests but it works.

now I can probably also use: (but have not tried it) :
`default: --publish-quiet --format pretty`

**Comment by aslakhellesoy** [comment]
Fixed by #1500
