### ISSUE TITLE
Junit Formatter not working with 'puts' and 'Cucumber.logger': <system-out> section is empty

### ISSUE THREAD

**Issue by ShubhraGoyal** [cucumber/cucumber-ruby#1487]
This is same issue reported at the https://github.com/cucumber/cucumber-ruby/issues/1192
The feature introduced in 847848f (see also #258) does not seem to work with puts, but it does with print.

```
Given a feature file like this:

Feature: asd

  Scenario: write to stdout
    Given I write to stdout something
And a step definition like this:

Given(/^I write to stdout (\w+)$/) do |string|
  puts string
end
When I run cucumber --format junit --out out
Then the JUnit report should contain "something" inside the CDATA section of <system-out>
```

But actually it's empty:

```
$ cat out/TEST-features-asd.xml 
<?xml version="1.0" encoding="UTF-8"?>
<testsuite failures="0" errors="0" skipped="0" tests="1" time="0.014794" name="asd">
<testcase classname="asd" name="write to stdout" time="0.014794">
  <system-out>
    <![CDATA[]]>
  </system-out>
  <system-err>
    <![CDATA[]]>
  </system-err>
</testcase>
</testsuite>
```

But if I run cucumber --format junit --out out --format pretty, I can see "something" printed on the console:

```
$ cucumber --format junit --out out --format pretty
Feature: asd

  Scenario: write to stdout           # features/asd.feature:3
    Given I write to stdout something # features/step_definitions/stdout.rb:1
      something

1 scenario (1 passed)
1 step (1 passed)
0m0.017s
```
If I replace puts with print the JUnit formatter works as well.

**Comment by luke-hill** [comment]
If you're working with cucumber5 this is by design. Can you confirm which version of the gem you're using.

**Comment by ShubhraGoyal** [comment]
> If you're working with cucumber5 this is by design. Can you confirm which version of the gem you're using.

 cucumber (3.1.0)

**Comment by luke-hill** [comment]
@ShubhraGoyal could you try using cucumber5 and using the new log method? See if this works.

I appreciate this might be tricky (As it's 2 major versions bumped), but v3.1 of cucumber is quite old.
