### ISSUE TITLE
CI: GitHub Actions - Deprecated set-env fails the build

### ISSUE THREAD

**Issue by olleolleolle** [cucumber/cucumber-ruby#1499]
**Describe the bug**

GitHub Action: fails on the issue described in  https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**To Reproduce**
1. Go to CI results on current master https://github.com/cucumber/cucumber-ruby/runs/1587672374
2. Click on `Set Up Ruby` or navigate to https://github.com/cucumber/cucumber-ruby/actions/runs/435284010 for an overview
3. Scroll down to 'Annotations'
4. See error described, with the above URL as a resolution hint.

**Expected behavior**

A green CI run.

**Context & Motivation**

This fails CI to red on master.

**Your Environment**
- this is on CI

**Comment by romaingweb** [comment]
I forgot to mention the issue in my commit. But I guess this was fixed by da38c03d1dbfec7b61eec7480d1f2a85fda9fbb8.

**Comment by olleolleolle** [comment]
Yep, that commit fixed the GitHub Actions issue, I will close this report, the test suite reports as red in GitHub Actions, but for other reasons. Thanks, @romaingweb for the repairs!
