### ISSUE TITLE
Allow attaching a path

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-ruby#1506]
It's common that users pass a file path (usually for a png or jpg file) as the first argument to the `attach` method. This leads to attachments that cannot displayed. One of the reasons users attach paths is that tools like Capybara's `save_screenshot` method returns a path instead of image data. Many users don't realise they have to `IO.read` the path before passing it to `attach`.

I think the `attach` method should behave as follows:

If the argument is a string, and the file exists, read the file and attach that.
Use a file extension to media type lookup to determine the media type. If a media type was specified, throw an error if the specified media type is different from the inferred one.

**Comment by aslakhellesoy** [comment]
@mpkorstanje @davidjgoss @vincent-psarga @charlierudolph what do you think about doing the same for Cucumber.js and Cucumber-JVM?

**Comment by mpkorstanje** [comment]
No objections in principle.

What would the protobuf look like?

> If the argument is a string, and the file exists, read the file and attach that.

For java and other typed languages we can use File/Path.

> Use a file extension to media type lookup to determine the media type. If a media type was specified, throw an error if the specified media type is different from the inferred one.

I would imagine that if the user provides the media type we don't second guess that - imagine `application/json` vs `text/json`. If none is provided we might guess, but that seems like a separate feature.

**Comment by mpkorstanje** [comment]
Perhaps we can also make the question clear in the API. 

Currently the method name is `attach`. Perhaps a more verbose set of names could make it clear that there is a question about what might be attached by having an api that say `attachFile`, `attachStream`, `attachBytes`, ect.

**Comment by aslakhellesoy** [comment]
> What would the protobuf look like?

I don't anticipate any protobuf changes to implement this. This is just about changing the logic that constructs the `Attachment` protobuf message.

**Comment by aslakhellesoy** [comment]
> Perhaps we can also make the question clear in the API.

I think it's more idiomatic in Ruby to have a single polymorphic method that accepts different types for the same argument. I don't see any problems doing the same with Java, where polymorphism is verified by the compiler. Same for TypeScript.

**Comment by davidjgoss** [comment]
Anecdotally I don't think this is much of a problem for cucumber-js - for screenshots, webdriver gives you a base64 string, puppeteer gives you a buffer - but I don't see an issue with adding this in the way you describe.

**Comment by aurelien-reeves** [comment]
After studying the code base, one quick question: do we update formatter/message_builder in order to fix all formatter which rely on it? Or do we go one step further and update runtime/user_interface to open a potentially given path?

At the moment, the former json formatter is the only one opening a given path.

Updating message_builder would fix formatters which rely on it like the html formatter.

Updating user_interface would update all existing and incoming formatter without having to even think about that specific case.

Also, I may have missed something, so feel free to correct me / drive me to another path if needed :D

What do you think everyone?
