### ISSUE TITLE
Some Scenarios running by line number are not executed

### ISSUE THREAD

**Issue by VladimirGumenny** [cucumber/cucumber-ruby#1520]
**Describe the bug**
Some Scenarios from the list with semicolon like `cucumber feature_name.feature:NNN:MMM:KKK` skipped to execute.

**To Reproduce**
It's really hard to say how to reproduce. Attached part of the log where skipped test cases are highlited.

**Expected behavior**
`cucumber feature_name.feature:NNN:MMM:KKK` should execute all Scenarios from the list with semicolon.

**Context & Motivation**
I use `parallel_tests` gem to execute in parallel threads (usually 8 threads). In `parallel_cucumber` i pass tags, and `parallel_cucumber` generates commands with features and line numbers with semicolon to execute. Last times we noticed that some tests cases were skipped to execute when started our regression in Jenkins. In last regression were skipped 25 test cases out of 763. Added more details (used `--verbose` option of `parallel_cucumber`) to the Jenkins log and found that those test cases were tagged in correct way, but somehow skipped to execute by `cucumber`. All skipped test cases are in 1 thread. Some of them Scenario Outline, some of them Scenario. All numbers point to the correct line, that contains `Scenario:` or `Scenario Outline:` keyword, not inside of Scenario.

**Screenshots**
![image](https://user-images.githubusercontent.com/38302890/114232579-eab2d300-9930-11eb-87f1-9b33ed0a9e3f.png)

**Your Environment**
Ruby 2.5.3
gem 'cucumber', '5.3.0'
gem 'parallel_tests', '3.6.0'
centOS7 / x86-64

**Comment by aurelien-reeves** [comment]
Would you have some examples - a reproduction feature with command lines for example - to help us to reproduce?

**Comment by VladimirGumenny** [comment]
Today I had another regression execution and got different set of skipped test cases. Could not find any dependency why exactly these test cases were skipped.

Initial command line to execute from Jenkins:

`parallel_cucumber features/ --verbose -t cucumber -n $THREADS --group-by scenarios -o "--tags '$TAGS' -p parallel -p allure --retry 2 -p default"`

where $THREAD=8, $TAGS=@regression and not @cert_only

It was converted to 8 commands, this is command that contains skipped test cases:

`bundle exec cucumber --tags '@regression and not @cert_only' -p parallel -p allure --retry 2 -p default features/feature_files/oom_admin/account/admin_profile.feature:11:123 features/feature_files/oom_admin/account/billing.feature:81 features/feature_files/oom_admin/account/locations.feature:277 features/feature_files/oom_admin/account/porting.feature:220:50 features/feature_files/oom_admin/account/schedules.feature:143:27 features/feature_files/oom_admin/account_summary.feature:7 features/feature_files/oom_admin/header_footer.feature:5 features/feature_files/oom_admin/settings/device/base_station.feature:105 features/feature_files/oom_admin/settings/device/dp1_device.feature:95 features/feature_files/oom_admin/settings/device/ip_phones.feature:1075:1212:142:150:270:533:760 features/feature_files/oom_admin/settings/extensions/conference_server.feature:253:9 features/feature_files/oom_admin/settings/extensions/paging_groups.feature:48 features/feature_files/oom_admin/settings/extensions/ring_groups.feature:236:77 features/feature_files/oom_admin/settings/extensions/users.feature:139:302:475:622:800 features/feature_files/oom_admin/settings/extensions/virtual_fax.feature:147 features/feature_files/oom_admin/settings/extensions/virtual_receptionist.feature:166:392:619 features/feature_files/oom_admin/settings/managed_wifi.feature:87 features/feature_files/oom_admin/settings/phone_numbers/phone_numbers.feature:281:93 features/feature_files/oom_admin/settings/system/call_blocking.feature:105:194:234 features/feature_files/oom_admin/settings/system/general.feature:29 features/feature_files/oom_admin/settings/system/messaging.feature:12 features/feature_files/oom_admin/settings/system/music.feature:49 features/feature_files/oom_admin/settings/system/shared_speed_dial.feature:81 features/feature_files/oom_admin/store/accessories.feature:26 features/feature_files/oom_admin/store/office_pro.feature:232:362:49 features/feature_files/oom_admin/store/overview_page.feature:5 features/feature_files/oom_admin/store/phones.feature:36 features/feature_files/oom_admin/store/store.feature:110:146:265:298:306:337:73 features/feature_files/oom_admin/store/store_assign_and_pair_device.feature:131:41 features/feature_files/oom_csr/sales/sales.feature:238:5 features/feature_files/oom_end_user/account/user_profile.feature:40 features/feature_files/oom_end_user/dashboard/user_fax.feature:59 features/feature_files/oom_end_user/settings/user_call_handling.feature:66 features/feature_files/oom_end_user/settings/user_caller_id_preferences.feature:11 features/feature_files/oom_end_user/settings/user_voicemail_preferences.feature:103 features/feature_files/signupv3/signupv3_basic.feature:101:170:286:31:397:474:562:570:578:599:607:617:627:635:73 features/feature_files/signupv3/signupv3_nuarx.feature:75 features/feature_files/signupv3/signupv3_ooma.feature:216:57 features/feature_files/signupv3/signupv3_retailer.feature:103:125:19:191:268:27:296:405:50 features/feature_files/signupv3/signupv3_sfdc.feature:130:238:45 features/feature_files/signupv3/signupv3_wework_mobile.feature:50`

cucumber.yml:
```default: --expand --backtrace --format pretty
allure: --format AllureCucumber::CucumberFormatter --out=allure/results
parallel: --format message --out=reports/cucumber-messages<%=ENV['TEST_ENV_NUMBER']%>.ndjson
messages: --format message --out=reports/cucumber-messages.ndjson
html_report: -r features -b --format pretty --format html --out=reports/cucumber.html
json_report: --format json --out=reports/cucumber.json
```

I do not know how to reproduce this issue. It appears with random test cases in 1 thread (out of 8) only.

Is it possible to add some additional log info that may help to find a reason? Any other suggestions?

**Comment by aurelien-reeves** [comment]
Did you see that we had an open issue that seems to be similar to yours?
Could you check your features to see if the specified line numbers match the "Scenario:" line or not?

**Comment by VladimirGumenny** [comment]
Yes, I saw it. I checked all line numbers, they are correct and point to the Scenario or Scenario Outline.

**Comment by aurelien-reeves** [comment]
If you execute yourself and several times the long command generated by `parallel_cucumber`, does it always fails the same or not?

**Comment by mattwynne** [comment]
When you say "skipped" @VladimirGumenny can you show us the output you see from Cucumber? Does it ignore the scenario completely, as though it had not been requested for execution / does not exist? Or does it appear in the results with a `skipped` status?

**Comment by VladimirGumenny** [comment]
> If you execute yourself and several times the long command generated by parallel_cucumber, does it always fails the same or not?

Executed 3 times exact that command from above: got correct result all 3 times.

> When you say "skipped" @VladimirGumenny can you show us the output you see from Cucumber? Does it ignore the scenario completely, as though it had not been requested for execution / does not exist? Or does it appear in the results with a skipped status?

@mattwynne Sorry for unclear info. I meant that Scenario was completely ignored. 
Attached log. As example in line #5 was requested `accessories.feature:26`.
This is Scenario Outline:
```
@regression @store_accessories
Feature: Store Accessories

  Background:
    Given I go to OOM Login page
    And I login to OOM as "admin" with "US" account using Resource Manager
    When I click on "Store" on the top level navigation menu
    And I click on "Accessories" on the inner level navigation menu

  @store_accessories1
  Scenario Outline: Verify that Accessories are filtered based on search bar input
    When I enter "<search_string>" into search field in Store Page
    Then I verify that "<expected_result>" devices are displayed in Store Page
    When I clear the Search field in Store Page
    Then I verify that all "Accessories" are displayed in Store Page
    When I logout from OOM
    Examples:
      | search_string | expected_result                                                                 |
 #Search by full device name
      | Base Station  | Base Station                                                                    |
 #Partial search by name
      | Yea           | Yealink EXP20,Yealink W60B,Yealink YHS33 Headset,Yealink Wi-Fi Dongle           |
      | in            | Ooma Linx,Yealink EXP20,Yealink W60B,Yealink Wi-Fi Dongle,Yealink YHS33 Headset |
 # Search by description (case not sensitive)
      | Yealink       | Yealink EXP20,Yealink W60B,Yealink YHS33 Headset,Yealink Wi-Fi Dongle           |
      | Wi-Fi         | Yealink Wi-Fi Dongle                                                            |
      | connect       | Ooma Connect 460,Connect 100 ft IX Cable                                        |
      | switch        | Netgear 8-port Switch                                                           |
```

It's easy to see that all others Examples were executed, but :26 ( `| Wi-Fi | Yealink Wi-Fi Dongle |`) was ignored.

[log_532.log](https://github.com/cucumber/cucumber-ruby/files/6307553/log_532.log)

**Comment by aurelien-reeves** [comment]
> 
> 
> > If you execute yourself and several times the long command generated by parallel_cucumber, does it always fails the same or not?
> 
> Executed 3 times exact that command from above: got correct result all 3 times.
> 

Ok, so it looks like it is more related to your environment, your tests, or parallel_test, than to cucumber itself.

Do you share any kind of state between tests that may leak from one thread to another one while executing in parallel?
How are resources - CPU and RAM mainly - on the machine which executes the tests?

**Comment by VladimirGumenny** [comment]
Hmmm... interesting idea...

No, i do not share state or any other data between threads.

Test cases execute on the server in the docker with Selenoid:

```
# free -m
              total        used        free      shared  buff/cache   available
Mem:          15886        2629        7726         445        5530       12346
Swap:          8063        2026        6037
# cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 42
model name	: Intel Xeon E312xx (Sandy Bridge)
```
(8 cores at all)

I realized that 3 times may be not enough, since we have only 1 buggy thread from 8, will execute more times after today's regression execution.

**Comment by aurelien-reeves** [comment]
@VladimirGumenny 
I would like to close that issue as this seems not to be related to cucumber.
You executed the single cucumber command successfully, so cucumber is working well.

Still, I would like to continue helping you with your issue.

Where would you like to continue? I could suggest [slack](https://cucumberbdd-slack-invite.herokuapp.com/), or the [cucumber community on smartbear](https://community.smartbear.com/t5/Cucumber-Open/bd-p/CucumberOS), as suggested here: https://cucumber.io/docs/community/get-in-touch/#slack 

Or would you prefer somewhere else?

**Comment by luke-hill** [comment]
@mattwynne @aurelien-reeves Whilst I've only just come back I would posit this is related to the issues with the regression we had where line numbers need to be exact.

I can't guarantee that's the issue. but it would be a good place to start

**Comment by VladimirGumenny** [comment]
@aurelien-reeves 
I am able to use any tool (just joined to Slack Cucumber Community workspace).
Use what works better for you.

**Comment by aurelien-reeves** [comment]
I would suggest to start a thread on slack, in the #help or #help-cucumber-ruby channel

**Comment by VladimirGumenny** [comment]
ok, started thread
