### ISSUE TITLE
Built-in html formatter generates a blank html report

### ISSUE THREAD

**Issue by mangjoze** [cucumber/cucumber-ruby#1524]
**Describe the bug**
When running my test using built-in html formatter, it generates a blank HTML file. Viewing the source of the html, I see a bunch of css and license stuff.

**To Reproduce**
1. Execute cucumber --format HTML --out report.html
2. Open the html report and html file is blank.

**Expected behavior**
HTML report to be generated should not be blank.

**Context & Motivation**
I can't report my test runs.

**Environment**
cucumber 6.0.0.
ruby 2.7.0
Windows 10

**Comment by aurelien-reeves** [comment]
I tried to reproduce without success.

I have been able to generate a working HTML report.

![image](https://user-images.githubusercontent.com/24386780/114995985-ae3a2680-9e9e-11eb-84fc-c4ee001eefcf.png)

Would you have a minimal reproduction scenario?

**Comment by mattwynne** [comment]
@mangjoze you should know that the html formatter doesn't generate a static HTML document. Rather, it generates an HTML page containing JSON data about your test run, and some JavaScript that should be able to render that JSON data into a nice-looking report. If the page is blank then it's probably because the JavaScript is failing for some reason.

Can you check the developer tools console to see if there are any errors.

**Comment by mangjoze** [comment]
@aurelien-reeves @mattwynne
I should have mentioned in the ticket that I'm pretty new at cucumber so I might be doing things the wrong way.
I have tried googling for some kind of solution but to no avail hence the ticket here.

> Would you have a minimal reproduction scenario?
I'll try to make a minimal feature/step file and see if I could repro it.
I will try and provide the html file here (need to confirm if I could put it here due to confidentiality reasons)

> What is your browser?
Browser is Chrome/IE/Edge

> Do you have any kind of add-on which may block execution of javascript?
> Can you check the developer tools console to see if there are any errors?
Not that I am aware of but I will check as soon as I get back to the office.

Thank you guys for the help! Much appreciated.

**Comment by mattwynne** [comment]
A minimal example to reproduce would be perfect, thanks @mangjoze!

**Comment by mattwynne** [comment]
Also,

> I'm pretty new at cucumber

Welcome to the community 😄 👋 🎉

**Comment by mangjoze** [comment]
I did a minimal feature/step file using accuweather and it worked. So I'm not quite sure why it does not work on my work feature/step files. Also, on the accuweather feature file, the embed doesn't work for me. I get an **_undefined method 'embed' (NoMethodError)'_**.

**Comment by aslakhellesoy** [comment]
The `embed` method has been renamed to `attach`: https://github.com/cucumber/cucumber-ruby/blob/master/CHANGELOG.md#removed-1

I assume this will make it work for you. If not, please make an mcve[https://stackoverflow.com/help/minimal-reproducible-example] and we'll reopen this issue.

**Comment by mattwynne** [comment]
@aslakhellesoy I'm trying to understand why the OP got a blank HTML report due to this error of using the wrong method to add an attachment. Can you explain what you think was happening?

**Comment by aurelien-reeves** [comment]
I am not sure the blank report and the use of the embed method are related: it seems that with accuweather there were a "undefined" 'embed' method, but the report was not blank.

@mangjoze still, we would need a minimal reproducible scenario. Try to isolate the step responsible of your issue

**Comment by mangjoze** [comment]
@aurelien-reeves 
> @mangjoze still, we would need a minimal reproducible scenario. Try to isolate the step responsible for your issue
**_I'm still working on it, so I managed to make it work on my test feature files by creating a new project and only included the feature files with completed step definitions. What I noticed when I first logged this is that, I am only running the @wip profile but it seems to include in the html source, the other feature files I have written which has either incomplete or no step definitions. Is that something that would prevent the html report to load? When there are feature files with no step def/incomplete ones?_**

> Did you take a look in your browser console with a blank report if there are JavaScript errors?
No Javascript errors

**Comment by aurelien-reeves** [comment]
> I'm still working on it, so I managed to make it work on my test feature files by creating a new project and only included the feature files with completed step definitions. What I noticed when I first logged this is that, I am only running the @wip profile but it seems to include in the html source, the other feature files I have written which has either incomplete or no step definitions. Is that something that would prevent the html report to load? When there are feature files with no step def/incomplete ones?

That's a trail :)

> No Javascript errors

Ok, thanks

**Comment by marnen** [comment]
@mattwynne:
> Rather, it generates an HTML page containing JSON data about your test run, and some JavaScript that should be able to render that JSON data into a nice-looking report.

Unfortunately, the way that’s done makes the Cucumber HTML report much less useful than it used to be. Back in the day, Cucumber used to use a similar approach to RSpec: it wrote straight HTML as scenarios ran, so that the file would render something useful in the browser before it was completely written. That makes it ideal for monitoring a long run with lots of scenarios. 

Current Cucumber HTML output, though, renders nothing until the run is complete (I think because `window.CUCUMBER_MESSAGES` isn’t well-formed JSON/JS till the final closing bracket is written), which means I need to wait for the entire run to finish before I see *any* output. Is there an HTML formatter for current Cucumber that doesn’t have this drawback? I haven’t found one, and I really miss the old RSpec-like behavior. (And if this is off-topic, I’ll raise a new issue or ask on the list.)

**Comment by mattwynne** [comment]
> it wrote straight HTML as scenarios ran, so that the file would render something useful in the browser before it was completely written. That makes it ideal for monitoring a long run with lots of scenarios.

In fact, this kind of live monitoring of a test run from a browser should now be easier to do, given that the results are streamed out as little `ndjson` packets. The problem would be getting that stream from your Cucumber process to your browser. It's a really cool idea, but yes it is off-topic for this thread I think :) If you're interested in pursuing it, let's create a new issue (in https://github.com/cucumber/cucumber) and discuss it there.

**Comment by pgundlupetvenkatesh** [comment]
I was able to reproduce this using Cucumber `--tags`. `bundle exec cucumber -t '@<tag_name>' -f html -o report.html` would throw a blank report but when I ran it with a Cucumber file name `bundle exec cucumber features/<file_name>.feature -f html -o report.html` I was able to view the HTML report and was not blank.

Did a quick check in the DOM Console and found this
![chrome_XvO326a18A](https://user-images.githubusercontent.com/9060416/211929221-af07ee79-f7f1-4590-8179-a19efa094ab8.png) 

Cucumber v6.1.0
Ruby v2.6.0
Windows 11
Browsers tried - Chrome v108x, Edge, Firefox

**Comment by pgundlupetvenkatesh** [comment]
@mattwynne did you get a chance to look at my comment above?

**Comment by luke-hill** [comment]
Hi @pgundlupetvenkatesh the HTML reporter isn't globally broken. 

If this is still an issue, could you create a new issue request with a repo that we can clone and produce a failing report as an [MVCE](https://stackoverflow.com/help/minimal-reproducible-example).
