### ISSUE TITLE
Allow using a HTTP proxy to send results

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-ruby#1526]
We should allow users behind a HTTP(S) proxy to publish results. See https://ruby-doc.org/stdlib-2.7.3/libdoc/net/http/rdoc/Net/HTTP.html#class-Net::HTTP-label-Proxies

**Comment by aslakhellesoy** [comment]
We should make sure all implementations use the same environment variables to configure proxy settings.

* https://github.com/cucumber/cucumber-jvm/issues/2285
* https://github.com/cucumber/cucumber-js/issues/1644

**Comment by luke-hill** [comment]
This is now redundant as the reporting tool is being rewritten from the ground up at a later date
