### ISSUE TITLE
Restore dates in CHANGELOG.md

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-ruby#1543]
It's useful to know how old a release is by looking at `CHANGELOG.md`

We had them for a while, then we stopped. Let's put back the missing ones and doing for future releases.

**Comment by AudTheCodeWitch** [comment]
I would like to take this one as a Hacktoberfest PR, if possible.

**Comment by aslakhellesoy** [comment]
Thanks @AudTheCodeWitch - go ahead!
