### ISSUE TITLE
Not all results are shown in the Run-window, even as I follow the tutorial

### ISSUE THREAD

**Issue by BoWunder** [cucumber/cucumber-ruby#1556]
So I have recently started my journey with Cucumber and Ruby. To get started, I have used the tutorial on guru99.com (https://www.guru99.com/cucumber-tutorials.html). I am aware that the tutorial is for an older version, but I would still expect the same results to be shown in the Run-window.

**The Issue:** 
Based on the tutorial, I would expect to see three results; the results of the multiplication, the number scenario 'passed'/'failed', and the number of steps 'passed'/'failed'. Instead, I only get the result of the multiplication. I do not see the number of 'passed'/'failed' 'Scenario'/'Steps' anywhere.

**To Reproduce**
1. Go to 'https://www.guru99.com/cucumber-installation.html'
2. Scroll down to 'First Cucumber Script' and follow the tutorial.
3. Follow instructions to script 'CucumberFirstProject', with feature list and step definition.
4. Once scripted, Run multiplication.feature
5. Observe the error in the Run-window (the lack of 'Scenario' and 'Steps' as seen in the "Actual Result" screenshot).

**Expected behavior**
Run-window shows three results: The multiplication result, the number of Scenarios passed or failed, and the number fo steps passed or failed. (See the "Expected Result" screenshot taken from the tutorial)

**Context & Motivation**
As someone new to Cucumber, I rely heavily on the tutorials. Sadly, tutorials does not explain mistakes you've made, issues you can't identify, or changes between versions.

**Screenshots**

**Your Environment**
 - Versions used [2021.1.2]
 - Operating System and version [Windows 10 Pro]

**Additional context**
N/A
<img width="529" alt="Expected result" src="https://user-images.githubusercontent.com/86303765/122934197-9c2da600-d36f-11eb-9a71-83ad78e8810c.PNG">
<img width="891" alt="Actual Result" src="https://user-images.githubusercontent.com/86303765/122934219-a2238700-d36f-11eb-92d2-1304de72a431.PNG">

**Comment by luke-hill** [comment]
This is due to the Teamcity RubyMine formatter, it's nothing to do with either this tutorial, cucumber or possibly even the tutorial site you are using.

We have a 10 minute tutorial for cucumber available on our docs here: https://docs.cucumber.io/docs/guides/10-minute-tutorial/

The issue is the default formatter for RubyMine has changed now. If you just run that scenario from the CLI you will get the output you are looking for
