### ISSUE TITLE
undefined method `Before' for main:Object

### ISSUE THREAD

**Issue by hedgehog** [cucumber/cucumber-ruby#156]
Somehow these hooks methods are getting clobbered, or are not laoding as they should.
Two independent occurrences:

https://github.com/mattwynne/cucover/issues/3
https://github.com/hedgehog/cuken/issues/6

**Comment by qatoolist** [comment]
require File.expand_path(File.dirname(__FILE__) + '/http_responses.rb')

require 'watir-webdriver'
require 'rspec'
require 'page-object'

before do
  @browser=Watir::Browser.new
end

after do
  @browser.close
end
