### ISSUE TITLE
Cucumber School example: cannot make code working

### ISSUE THREAD

**Issue by BoWunder** [cucumber/cucumber-ruby#1560]
**Describe the bug**
So currently, I'm going through the Cucumber school for Ruby,. I've done the change to make Sean "just" shout ( at 1:40 and onward; https://school.cucumber.io/courses/take/bdd-with-cucumber-ruby/lessons/15974202-incidental-details ). Running the code via command promt does now yeld the same results as in the video, and i do not know why (This is what I see when I run the code ![image](https://user-images.githubusercontent.com/86303765/124885197-4e51a880-dfd3-11eb-9004-f99a4862e1dd.png) )

For additional details, I've gone through the course material (https://github.com/cucumber-school/bdd-with-cucumber/tree/main/content/05/code/ruby/05-location-specified-in-data-table), and with the exception of the spec-files (which I did not add to my project, since that caused issues that made the code unable to run), everything is as seen in the course material.

From what little I can gather, the "issue" supposedly is that "shout" is undefined, even through I got: it written as shown inboth the video and in the course material:
(step_definition)
When("Sean shouts") do
  @people['Sean'].shout("Hello, world")
end

Here's the code. Mind that I it may be a little different as i continued with the sessions in the hope, that a solution would present itself.:

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
**Feature-file: hear_shout.feature**
```ruby
Feature: Hear shout

  Shouty allows users to "hear" other users "shouts" as long as they are close enough to each other.

  Rule: Shouts can be heard by other users

    Scenario: Listener hears a message
      Given a person named Sean
      And a person named Lucy
      When Sean shouts "Free bagels at Sean's"
      Then Lucy should hear Sean's message

  Rule: Shouts should only be heard if listener is within range

    Scenario: Listener is within range
      Given the range is 100
      And people are located at
        | name      | Sean | Lucy |
        | location  | 0    | 50   |
      When Sean shouts
      Then Lucy should hear a shout

    Scenario: Listener is out of range
      Given the range is 100
      And people are located at
        | name      | Sean | Larry |
        | location  | 0    | 150   |
      When Sean shouts
      Then Larry should not hear a shout

  Rule: Listener should be able to hear multiple shouts

    Scenario: Two shouts
      Given a person named Sean
      And a person named Lucy
      When Sean shouts "Free bagels!"
      And Sean shouts "Free toast!"
      Then Lucy hears the following messages:
        | Free bagels! |
        | Free toast!  |

  Rule:  Maximum length of message is 180 characters
```
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
**Step Definitions: step_definition.rb**
```ruby
require "shouty"

DEFAULT_RANGE = 100

Before do
  @people = {}
  @network = Shouty::Network.new(DEFAULT_RANGE)
end

Given("the range is {int}") do |range|
  @network = Shouty::Network.new(range)
end

Given("a person named {word}") do |name|
  @people[name] = Shouty::Person.new(@network, 0)
end

Given("people are located at") do |table|
  p table.transpose.symbolic_hashes.each do |name: , location: |
    @people[name] = Shouty::Person.new(@network, location.to_i)
  end
end

When("Sean shouts") do
  @people['Sean'].shout("Hello, world")
end

When("Sean shouts {string}") do |message|
  @people['Sean'].shout(message)
  @message_from_sean = message
end

Then("Lucy should hear a shout") do
  expect(@people['Lucy'].messages_heard.count).to eq(1)
end

Then("Lucy should hear Sean's message") do
  expect(@people['Lucy'].messages_heard).to eq [@message_from_sean]
end

Then("Larry should not hear a shout") do
  expect(@people['Larry'].messages_heard.count).to eq(0)
end

Then "Larry should not hear Sean's message" do
  expect(@people['Larry'].messages_heard).not_to include(@message_from_sean)
end

Then("Lucy hears the following messages:") do |expected_messages|
  actual_messages = @people['Lucy'].messages_heard.map { |message| [message] }

  expected_messages.diff!(actual_messages)
end
```
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
**(lib\): shouty.rb**
```ruby
module Shouty
  class Person
    attr_reader :messages_heard, :location

    def initialize(network, location)
      @messages_heard = []
      @network        = network
      @location       = location

      @network.subscribe(self)
    end

    def shout(message)
      @network.broadcast(message, @location)#;
    end

    def hear(message)
      @messages_heard << message
    end
  end

  class Network
    def initialize(range)
      @range     = range
      @listeners = []
    end

    def subscribe(person)
      @listeners << person
    end

    def broadcast(message, shouter_location)
      @listeners.each do |listener|
        if (listener.location - shouter_location).abs <= @range
          listener.hear(message)
        end
      end
    end
  end
end
```

**Comment by aurelien-reeves** [comment]
Your snippet of codes are difficult to read.
Could you please try to format those in a cleaner way using [Github Flafoured Markdown](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)?

Or, even better, host it in a github repository, that way we could checkout it and test by ourselves.

From what I can see, I cannot spot any issues in what you have submited

**Comment by BoWunder** [comment]
Hopefully the format should work now. Also, as for spotting the issue, I don't know what to look for. As I said, I've not included spec_helper.rb, network_spec.rb or person_spec.rb, since that results in a LoadError (and have not been necessary in order to run the code prior).

**Comment by mattwynne** [comment]
The error says that you have a `nil` object that you're trying to call `shout` on, so the hash of `@people` somehow doesn't contain an entry for `Sean`.

Maybe try printing the `@people` hash to see what's in it?

**Comment by BoWunder** [comment]
Keep in mind that I'm still very new to ruby, so what you just said blew largely over my head. However, as you can see in the code above:

from step_definition, we have   
@people = {}

And it does contain Sean for the specific line of code;
When("Sean shouts") do
  @people['Sean'].shout("Hello, world")
end

**Comment by aurelien-reeves** [comment]
Did you consider studying Ruby and learning some basic in development before going deeper with Cucumber?

Even if cucumber and cucumber school both try to be as easy as possible, some basic development knowledge is a requirement. Cucumber remains an automation tool. 

The formulation part - writing feature files - does not required any skill and some collaboration tools like Cucumber Studio may even make that part easier. 

However the automation part - writing the code, the step definitions, which will execute the tests - remain a task that required some development knowledge.

You seem very interested into Cucumber, and that is great! You just need to get a step back and take a little time to be ready first. Once you have the basic understanding which are required - some very basic understanding of ruby development - it will be far easier for you.

**Comment by BoWunder** [comment]
I sadly do not have the time to learn Ruby at this moment.

To return to the issue, you say that I should print @people to see what's in it. Not sure what you mean by this, as I have posted the code here in the report. And all I get when making a **puts** is:

{"Sean"=>#<Shouty::Person:0x000001d1cfe6ab20 @messages_heard=["Free bagels!", "Free toast!"], @network=#<Shouty::Network:0x000001d1cfe6b4a8 @range=100, @listeners=[#<Shouty::Person:0x000001d1cfe6ab20 ...>, #<Shouty::Person:0x000001d1cfe69298 @messages_heard=["Free bagels!", "Free toast!"], @network=#<Shouty::Network:0x000001d1cfe6b4a8 ...>, @location=0>]>, @location=0>, "Lucy"=>#<Shouty::Person:0x000001d1cfe69298 @messages_heard=["Free bagels!", "Free toast!"], @network=#<Shouty::Network:0x000001d1cfe6b4a8 @range=100, @listeners=[#<Shouty::Person:0x000001d1cfe6ab20 @messages_heard=["Free bagels!", "Free toast!"], @network=#<Shouty::Network:0x000001d1cfe6b4a8 ...>, @location=0>, #<Shouty::Person:0x000001d1cfe69298 ...>]>, @location=0>}

Not sure what to look for

**Comment by luke-hill** [comment]
@BoWunder I assume you're doing this at work right? If so, speak to your line manager and say you need some time to do a course.

There are many free courses online. I have my own one in my github profile. And there are things like RubyKoans (Which I have a subset of on my github).

I would push back and try get some dedicated time to learning ruby first. For example in your debug trace, you actually have access to Sean in your people network. So something else is the matter

**Comment by BoWunder** [comment]
From what I can understand, @people is not the issue. Like it says in the first image, it considers "shout" to be undefined. The lines of code it reacts to, as far as I can tell, are:

**When("Sean shouts") do
  @people['Sean'].shout("Hello, world")
end**

The only thing I can think of is that it won't read "Hello, world", because it's not an actual message? (compared to another shout:) 
**When("Sean shouts {string}") do |message|
  @people['Sean'].shout(message)
  @message_from_sean = message
end** 

But that's the tutorial for that specific scenario; Sean does not need to say anything specific, we're just checking if Lura and Larry are within range or not.

So, yeah, the definition of "shout" should be the issue somehow?

**Comment by aslakhellesoy** [comment]
> I sadly do not have the time to learn Ruby at this moment.

Then you're not ready to learn Cucumber. You have to learn to walk before you can learn to run.

**Comment by aslakhellesoy** [comment]
I'm closing this since it's not about a bug in cucumber-ruby.
