### ISSUE TITLE
Which are the supported platforms?

### ISSUE THREAD

**Issue by aurelien-reeves** [cucumber/cucumber-ruby#1563]
On the README, we announce that the supported platforms are:

    - Ruby 3.0
    - Ruby 2.7
    - Ruby 2.6
    - Ruby 2.5
    - Ruby 2.4
    - Ruby 2.3
    - JRuby 9.2 (with some limitations)

But the CI actually checks only 

    - Ruby 3.0
    - Ruby 2.7
    - Ruby 2.6
    - Ruby 2.5
    - JRuby 9.2 (with some limitations)

So, do we support Ruby 2.3 and 2.4?

If so, we should add those in the CI.
If not, we should remove those from the README.

Caution: some dependencies like Rubocop do not support anymore Ruby <= 2.4 on Windows so such build won't work.

**Comment by aurelien-reeves** [comment]
Myself I think we should remove Ruby 2.3 and 2.4 from supported platforms

**Comment by luke-hill** [comment]
The reason for this is we did this, then aslak did some digging and found out that ruby 2.3 is still the most widely used ruby. I know the data was a bit rudimentary, but that's the reason for it

**Comment by aurelien-reeves** [comment]
We say we support it, but actually we do not test that support at all.
That would mean, eventually, if someone report an issue with Ruby 2.3, we would fix it?

**Comment by luke-hill** [comment]
Probably best to defer to @aslakhellesoy for that decision. 

I'm happy to remove ruby 2.3 and 2.4 from the support lifecycle, but it's not my decision.

**Comment by aslakhellesoy** [comment]
According to https://stats.rubygems.org/ almost 50% of users are on Ruby 2.3....

**Comment by aurelien-reeves** [comment]
I do not suggest preventing cucumber-ruby to work with ruby 2.3 and 2.4.

What about removing those Rubies from "supported platforms" list, and if issues are opened someday related to those version, we consider fixing those or not depending the issues? As I said, those versions are already not part of the CI. That would not make such difference.

But if we want to let those as part of the "supported platforms" list, we may consider bringing those back in the CI

**Comment by aurelien-reeves** [comment]
Actually we do not support ruby 2.3 and 2.4: https://github.com/cucumber/cucumber-ruby/blob/main/cucumber.gemspec#L21

Cucumber has been distributed to minimum ruby 2.5 since v5.0

**Comment by aurelien-reeves** [comment]
Continue here: https://github.com/cucumber/cucumber-ruby/issues/1467
