### ISSUE TITLE
Parametrised Scenarion Outline Definition 

### ISSUE THREAD

**Issue by poojaghosh47** [cucumber/cucumber-ruby#1605]
Was going through Specflow-How to pass parameter in scenario outline description and wonder how to pass parameter in Scenario outline description in watir?

Let's use the same example from other post.

```gherkin
Scenario Outline : Testing <Application>
    Given I navigate to <Application>
    Then I should see Home page

    Examples:
    | Application |
    | Test        |
    | Test1       |
    | Test2       |
```

This will be helpful when user generate the consolidate report with Report Builder to show each scenario outline as a separate scenario with the application name rather showing Testing <Application>.

Actual Sample Report: Without parameter updated to scenario outline enter image description here

Expected Sample Report: All we need is to update <Application> based on example table data

enter image description here

Appreciate any detailed explanation.

**Comment by jenisys** [comment]
@aurelien-reeves 
Mmh, I actually think that it is not related to the formatter.
I think that @poojaghosh47 means an aspect how the Scenarios are actually build from the ScenarioOutline template description. Meaning what is part of the template and what is not.

**QUESTION:** Is the example above currently possible in Cucumber (parameter/placeholder in the title) ?

In such a way that:

```gherkin
# — HINT: AFTER TEMPLATE EXPANSION (from example table rows):
Scenario Outline: Testing Test
   Given I navigate to Test
   …

Scenario Outline: Testing Test1
   Given I navigate to Test1
   …

Scenario Outline: Testing Test2
   Given I navigate to Test2
   …
```

**Comment by poojaghosh47** [comment]
Hi Team ,

I got solution for this . We can pass Examples data directly to scenarios outline using below format.

Seriously I am happy to try this and it worked .
It is helpful for understanding the combine report scenario wise .

Each scenario outline for example will have specific example data in scenario outline definition.

Scenario Outline : Testing “<Application>“
    Given I navigate to “<Application>“
    Then I should see Home page

    Examples:
    | Application |
    | Test        |
    | Test1       |
    | Test2       |

OUTPUT In report will be like:

Scenario Outline : Testing Test
    Given I navigate to Test
    Then I should see Home page

Scenario Outline : Testing Test1
    Given I navigate to Test1
    Then I should see Home page

**Comment by aurelien-reeves** [comment]
I was not sure that would work, so I did not suggest it
Happy it does! 🎉

**Comment by aurelien-reeves** [comment]
> 



> @aurelien-reeves Mmh, I actually think that it is not related to the formatter. I think that @poojaghosh47 means an aspect how the Scenarios are actually build from the ScenarioOutline template description. Meaning what is part of the template and what is not.
> 
> **QUESTION:** Is the example above currently possible in Cucumber (parameter/placeholder in the title) ?
> 
> In such a way that:
> 
> ```
> # — HINT: AFTER TEMPLATE EXPANSION (from example table rows):
> Scenario Outline: Testing Test
>    Given I navigate to Test
>    …
> 
> Scenario Outline: Testing Test1
>    Given I navigate to Test1
>    …
> 
> Scenario Outline: Testing Test2
>    Given I navigate to Test2
>    …
> ```

Thanks @jenisys 
I understood well its proposition. I was not sure for the formatting of the name and description of the scenario.
But reporting one test per example in the examples table actually concern the formatter
