### ISSUE TITLE
Terminal keeps show parameter undefined

### ISSUE THREAD

**Issue by ameliaanism** [cucumber/cucumber-ruby#1615]
I've updated some gem, and this is happens. I using regular expressions instead of cucumber expressions, so how to hint the "parameter undefined" in my terminal? how to remove the "parameter undefined" in my terminal?

<img width="550" alt="Screen Shot 2022-02-16 at 09 59 12" src="https://user-images.githubusercontent.com/22050144/154187818-5f605d5f-e58a-4e45-8adb-daed7052b171.png"

**Comment by aurelien-reeves** [comment]
Closing as this is a copy of the following: https://github.com/cucumber/common/issues/1907
