### ISSUE TITLE
Automatic dependency update PRs

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-ruby#1637]
### 🤔 What's the problem you've observed?

Renovate only looks at the `Gemfile` so most of our dependencies (which are in the `.gemspec`) are ignored.

### ✨ Do you have a proposal for making it better?

Take a look at https://github.com/marvin-bitterlich/renovate-gemspec-minimal-example and see if it works for us.

### 📚 Any additional context?

This is still an [open issue on renovate](https://github.com/renovatebot/renovate/issues/10616).

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/developer_experience.md)*

**Comment by mattwynne** [comment]
Doesn't seem to be working - If I run `scripts/update-gemspec` I can see that `capybara` has an update, so renovate should be picking that up.

I've enabled the [dependency dashboard](https://github.com/cucumber/cucumber-ruby/issues/1568) for now so we can trigger re-runs, and you can see detailed logging output from renovate at https://app.renovatebot.com/dashboard#github/cucumber/cucumber-ruby

at the moment it looks like it's ignoring the regex manager config:

```
INFO: Dependency extraction complete
{
  "baseBranch": "main",
  "stats": {
    "managers": {
      "bundler": {
        "fileCount": 1,
        "depCount": 8
      },
      "github-actions": {
        "fileCount": 4,
        "depCount": 10
      }
    },
    "total": {
      "fileCount": 5,
      "depCount": 18
    }
  }
}
```

**Comment by mattwynne** [comment]
Weird. [In the logs](https://app.renovatebot.com/dashboard#github/cucumber/cucumber-ruby/673070868) I do see the `regex` manager running, and detecting the `cucumber.gemspec` file:

```
DEBUG: Matched 1 file(s) for manager bundler: Gemfile
DEBUG: Matched 4 file(s) for manager github-actions: .github/actions/test-ruby/action.yml, .github/workflows/cucumber-ruby.yml, .github/workflows/release.yml, .github/workflows/rubocop.yml
DEBUG: Matched 1 file(s) for manager regex: cucumber.gemspec
```

But it then seems to ignore it:
```
DEBUG: Found bundler package files
DEBUG: Found github-actions package files
DEBUG: Found 5 package file(s)
```

**Comment by mattwynne** [comment]
From the [logs](https://app.renovatebot.com/dashboard#github/cucumber/cucumber-ruby/673070981):

```
DEBUG: Manager explicitly enabled in "enabledManagers" config, but found no results. Possible config error?
{
  "manager": "regex"
}
```

**Comment by mattwynne** [comment]
I'm continuing my experiments [in a fork of the minimal example](https://github.com/mattwynne/renovate-gemspec-minimal-example)

**Comment by mattwynne** [comment]
It looks to me like Dependabot might be a better candidate than Renovate. It's certainly able to [draw a dependency graph](https://github.com/cucumber/cucumber-ruby/network/dependencies) from the `.gemspec`, but at the moment our Gemfile (with these environment variable overrides for paths) breaks it.

**Comment by mpkorstanje** [comment]
I've added the example provided in https://github.com/renovatebot/renovate/issues/10616#issuecomment-1364595821 to https://github.com/cucumber/renovate-config

**Comment by mpkorstanje** [comment]
You can now replace dependabot with Renovate.

Please use the contents of https://github.com/cucumber/renovate-config/blob/main/renovate.json .

**Comment by mattwynne** [comment]
Done, thanks for your help with this Rien! 🙏🏻
