### ISSUE TITLE
Is that possible to run cucumber tests from my own gem

### ISSUE THREAD

**Issue by RayChenLDL** [cucumber/cucumber-ruby#1642]
### 🤔 What's the problem you're trying to solve?

I am build cucumber tests and build a new gem to pack everything in (including everything, such as cucmber.yml and all the files under folder /features). Wondering if it is possible to run the cucumber test from my new gem? For example to run: mygem "--profile example" "--tag @mytag"

the problem I have is, the cucumber will look for cucumber.yml as well as the folder "/features" from the current path where I run my command "mygem ......". Apparently there is no such files. So is it possible to run cucumber tests from inside of my gem? Looking forward to any advice.

to specify paths for "features" and cucumber.yml rather than using default

### 📚 Any additional context?

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by mitchgrout** [comment]
I've done some tinkering with the internals and found that it's indeed possible, depending on what you're aiming to achieve exactly. If your gem aims to wrap the behaviour of `cucumber` in some way, i.e. will still expose a `features/` directory, you could use `Cucumber::Cli::Main` to achieve this, e.g.

```ruby
require "cucumber/cli/main"

# Invokes cucumber, but in a custom directory
def run_tests(directory)
  # Assuming the target directory will have a `features/` directory in it
  Dir.chdir(directory) do
    # https://github.com/cucumber/cucumber-ruby/blob/main/lib/cucumber/cli/main.rb
    # for how you can override the stdout/stderr/kernel methods
    cli = Cucumber::Cli::Main.new(["--some-extra-args"])
    cli.execute!
  end
end
```

With a setup like this, you could also programmatically set up `features/` in the target directory, then use the above to invoke `cucumber` within your gem.

**Comment by RayChenLDL** [comment]
Thanks for the response I will try and let you know.

**Comment by aurelien-reeves** [comment]
You should definitely be able to work with cucumber-ruby programmatically.

It may still be rough for now, but we would be pleased to improve things in the future. So, feel free to submit any feedback at any point :)

Regarding your topic, we have recently bring a new hook dedicated to things like the one you are trying to do here. This is the [InstallPlugin hook](https://github.com/cucumber/cucumber-ruby/tree/main/features/docs/writing_support_code/hooks#installplugin). It should fit your needs. And if not, let us know, because it is what should help you customizing your cucumber programmatically at some point :)

**Comment by RayChenLDL** [comment]
Thank you both. I tried, not working. The main issue is I have wrapped up /feature folder in the new gem. When running the "cucumber" even inside of the gem, it is still looking for the /feature directory from where the gem command is run, which is some physical directory on the host. not from directory inside of the gem.

Maybe it is not possible to run cucumber this way at all?

**Comment by mitchgrout** [comment]
It should definitely be possible. I've managed to use the `Dir.chdir` approach in the past with no issues; could you provide a minimal example of how you're implementing this?

**Comment by RayChenLDL** [comment]
Made some progress with Dir.chdir

Here is the code to run cucumber. 
Dir.chdir(__dir__) do
      cli = Cucumber::Cli::Main.new(["profile local tag @test"])
      cli.execute!
end

not sure that is the right way to pass profile and tag? Because I got the error below:
**[error] No such file or directory - profile local tag @test. You can use `cucumber --init` to get started.**

**Comment by RayChenLDL** [comment]
Got an error with the way below to pass the profile and tag:
cli = Cucumber::Cli::Main.new(['-p local', '-t @test'])

**Comment by mitchgrout** [comment]
Arguments need to passed in the same format as `ARGV`, i.e. an invocation like `cucumber --foo 1 --bar 2 --baz 3` would need to become

```ruby
Cucumber::Cli::Main.new(["--foo", "1", "--bar", "2", "--baz", "3"])
# or, using word-arrray syntax
Cucumber::Cli::Main.new(%w[--foo 1 --bar 2 --baz 3])
```

Let me know how you get along with this

**Comment by RayChenLDL** [comment]
Yeah! working well, pretty excited to see the tests are running from inside of the gem. Thanks for the help.

Next thing I am thinking is...how I could get the cucumber report. as the test automation code itself is from gem inside, what is the  best way to deal with the report? I am pretty new to ruby gem. I am wondering if there is similar thing as volume mapping for docker container, which I could use to allow cucumber to produce html report outside of gem (though the test automation is running from inside of the gem.)?

**Comment by mitchgrout** [comment]
I'm assuming by 'report' you mean the output of the process? The constructor for `Cucumber::Cli::Main` in release `8.0.0` is

```ruby
def initialize(args, out = $stdout, err = $stderr, kernel = Kernel)
```

so you could do something like this: 

```ruby
class FakeKernel
  attr_reader :exit_code
  def exit(code)
    @exit_code = code
  end
end

output = StringIO.new
kernel = FakeKernel.new
args = ["--format", "html"] # or something similar
cli = Cucumber::Cli::Main.new(args, output, output, kernel) # roll stderr in with stdout
cli.execute!

raise "your tests failed!" unless kernel.exit_code.zero?
p output.string # your output is accessible via this variable
```

(note: you need to use a 'fake kernel' of sorts, since `execute!` will call `exit` when it's done, so your fake kernel needs to intercept that call)

**Comment by aurelien-reeves** [comment]
Do we need to keep that issue open?
Is there an actual ongoing issue that still need to be fixed?

@RayChenLDL have you been able to make it work as expected?

Can we close the issue?

**Comment by aurelien-reeves** [comment]
You're welcome :)
Thanks @mitchgrout for all the help!
