### ISSUE TITLE
AfterStep: Attach any generation methods (attach/embed), to specific step

### ISSUE THREAD

**Issue by RayChenLDL** [cucumber/cucumber-ruby#1645]
within my hook.rb, I capture screenshot under "AfterStep" which means I want to capture screen for each of the steps. When I check the html report after the run, all the attached screenshots just piles up at the end. Not very clear for the report audience to tell which screenshot is for which step. Is that possible to attach the screenshot right after each step (as shown in the attached picture.)?

### 📚 Any additional context?

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by RayChenLDL** [comment]
![image](https://user-images.githubusercontent.com/40652062/170638330-fcd8411a-698c-4ed7-99c7-2c14292abbba.png)

**Comment by davidjgoss** [comment]
Did a quick little test with [cucumber-js](https://github.com/cucumber/cucumber-js):

```js
AfterStep(async function() {
    await this.log('foo!')
});
```

<img width="351" alt="image" src="https://user-images.githubusercontent.com/3192745/170820788-6db6cf9f-6e6b-41d2-abaf-52694109746e.png">

So I think the formatter is behaving correctly. Could this be an issue with how cucumber-ruby is emitting the messages? i.e. it could be missing the `testStepId` that ties it to the step.

**Comment by luke-hill** [comment]
Also we're slightly behind the 8-ball. We only just did an update (Like 1/2 days ago). This user may be using the messages that are old.

**Comment by RayChenLDL** [comment]
Here it is
    cucumber (8.0.0)
      builder (~> 3.2, >= 3.2.4)
      cucumber-ci-environment (~> 9.0, >= 9.0.4)
      cucumber-core (~> 11.0, >= 11.0.0)
      cucumber-cucumber-expressions (~> 15.1, >= 15.1.1)
      cucumber-gherkin (~> 23.0, >= 23.0.1)
      cucumber-html-formatter (~> 19.1, >= 19.1.0)
      cucumber-messages (~> 18.0, >= 18.0.0)
      diff-lcs (~> 1.5, >= 1.5.0)
      mime-types (~> 3.4, >= 3.4.1)
      multi_test (~> 1.1, >= 1.1.0)
      sys-uname (~> 1.2, >= 1.2.2)

**Comment by RayChenLDL** [comment]
That is true the new version 8.0.0 was only published less than 2 weeks ago, which I am interested in give it a try when I am building up the test automation solution for frontend.

**Comment by RayChenLDL** [comment]
Any update on this issue please?

**Comment by luke-hill** [comment]
@RayChenLDL can you produce an MVCE ideally in the form of a github repo. If you're using v8 this "should" be working.

**Comment by RayChenLDL** [comment]
give me some time please, I will try again and produce MVCE

**Comment by luke-hill** [comment]
Hi @RayChenLDL are we any further with this. Can we close this as unactionable?

**Comment by RayChenLDL** [comment]
Yes,please.
