### ISSUE TITLE
In one feature, set a rule that all scenarios skipped if previous scenario failed. 

### ISSUE THREAD

**Issue by ouyangkui** [cucumber/cucumber-ruby#1646]
### 🤔 What's the problem you're trying to solve?
 I am a user of cucumber and need blow feature if cucumber owner can provide it. 

 In some features with many scenarios,  for example:
create , edit,  testing,  del
if create scenario fail, I would like to see remained scenarios skipped auto.
scenario A dependency scenario B

### 📚 Any additional context?

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by luke-hill** [comment]
Whilst this is possible. This is entirely antithetical to cucumber. This proposes that tests are isolated separate components.

TIL/TIP - Test isolation Law/Principle states that tests should not be coupled to one another.

A way in which you could do this "loosely" would be as follows

```
Before do |scenario|  
  skip_this_scenario 'We need to skip!' if $skip_all_others
end

After do |scenario|
  $skip_all_others = true  if scenario.failed?
end
```

**Comment by ouyangkui** [comment]
find method to resolve it.
add code in hooks
https://stackoverflow.com/questions/49824616/cucumber-java-fail-fast

**Comment by ouyangkui** [comment]
@[luke-hill](https://github.com/luke-hill)  thank you for your helps.
But I did not get your mean.
Could you provide details more?  appreciate
