### ISSUE TITLE
Cucumber Teamcity::Cucumber::Formatter

### ISSUE THREAD

**Issue by AllenAbolmaali** [cucumber/cucumber-ruby#1674]
When I try to Run a Scenario inside a feature file the system does not run the scenario and gives the below Error: 
--format Teamcity::Cucumber::Formatter

Process finished with exit code 0

How ever when I click on the name.feature file and run - it runs perfectly .  only happens on 1 project and ather project work as expected - I am using same SDK path

**Comment by mpkorstanje** [comment]
I'm guessing this issue belongs here, please feel free to close if it isn't actionable.

**Comment by luke-hill** [comment]
Ah yes. Sorry, this is definitely a cucumber ruby issue alone, not a poly issue.

Either way though this should be closed and fixed on the Jetbrains issue tracker.

Sorry for not closing this earlier. Top sleuthing though.

@AllenAbolmaali please create an issue on the Jetbrains tracker under the `RUBY-*` prefix.

The link is here: https://youtrack.jetbrains.com/newIssue
