### ISSUE TITLE
Drop ruby 2.6 support

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-ruby#1693]
### 🤔 What's the problem you've observed?

Ruby 2.6 is EOL. Some of our dependencies can't be upgraded until we do this.

### ✨ Do you have a proposal for making it better?

Remove support in our build process. Make a major release.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/developer_experience.md)*

**Comment by luke-hill** [comment]
So previously (as an FYI), we've done these updates in just minor releases. And I don't see any issues doing the same.

But if we wanted to roll it in with other big things I guess we can do that.

I'm all setup now so can chat to you on thursdays

**Comment by olleolleolle** [comment]
Related: https://github.com/cucumber/cucumber-ruby/pull/1689 luke-hill mentioned in this PR that it'd probably pass if we were on 2.7+.

**Comment by Kaushik-Iyer** [comment]
is this issue still open
