### ISSUE TITLE
VERSION constant cannot find version file in v9.0.0

### ISSUE THREAD

**Issue by p-linnane** [cucumber/cucumber-ruby#1728]
### 👓 What did you see?

Building cucumber-ruby from source for Homebrew. Running the application returns the following:

```
/opt/homebrew/Cellar/cucumber-ruby/9.0.0/libexec/gems/cucumber-9.0.0/lib/cucumber/platform.rb:10:in `read': No such file or directory @ rb_sysopen - /opt/homebrew/Cellar/cucumber-ruby/9.0.0/libexec/gems/cucumber-9.0.0/VERSION (Errno::ENOENT)
```

### ✅ What did you expect to see?

The application does not crash.

### 📦 Which tool/library version are you using?

Cucumber v9.0.0 build with Ruby 3.2 for Homebrew

### 🔬 How could we reproduce it?

1. Check out this PR: https://github.com/Homebrew/homebrew-core/pull/141026
2. Run `brew install --build-from-source --verbose cucumber-ruby`
3. After the build completes, run `cucumber`
4. Error appears

### 📚 Any additional context?

Relates to https://github.com/Homebrew/homebrew-core/pull/141026

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by matobinder** [comment]
I see same issue, after doing a `bundle update`(from cucumber 8 -> 9)

I just reproduced it in `irb`, to reduce confusion from my test stuff
Basically owned up irb and
```
require 'bundler/setup'
require 'cucumber/rake/task'
```
This was on Rube 3.1.2

That actually is the first require my stuff is doing of cucumber. Did the order of require's possibly change?

**Comment by parholmdahl** [comment]
I am experiencing the same issue with a bundle install in a docker container. 

Any workaround except setting a Gemfile.lock for the older verison?

**Comment by luke-hill** [comment]
This was the first release I did using the new methodology. I will triage this today but it might not be fixed until Monday.

**Comment by luke-hill** [comment]
I've renamed the issue as it's not directly finding the file (The location has to be set owing to our release toolset).

Can you try this branch please. It "should" fix things.

```
gem 'cucumber', git: 'https://github.com/cucumber/cucumber-ruby.git', branch: 'hotfix/sep_1'
```

**Comment by therve** [comment]
Confirmed that the branch works.

**Comment by parholmdahl** [comment]
I can not set this up, but it looks like it is problem with my environment and not your fix.. So i look forward to a patch-release..

**Comment by luke-hill** [comment]
A fix will be pushed out today at some point. I'll leave this open just incase other people visit.

**Comment by p-linnane** [comment]
Confirming that v9.0.1 resolved the issue for us on the Homebrew side. Thanks!
