### ISSUE TITLE
Terminal keeps show parameter undefined

### ISSUE THREAD

**Issue by ameliaanism** [cucumber/cucumber-ruby#1735]
I've updated some gem, and this is happens. I using regular expressions instead of cucumber expressions, so how to hint the "parameter undefined" in my terminal? how to remove the "parameter undefined" in my terminal?

<img width="550" alt="Screen Shot 2022-02-16 at 09 59 12" src="https://user-images.githubusercontent.com/22050144/154189934-b0f3d6a7-44ea-4b7a-b5da-7c3342a0759e.png">

**Comment by luke-hill** [comment]
Closing as not enough info provided.

@ameliaanism if this is still an issue please provide enough information to reproduce the error
