### ISSUE TITLE
Cucumber multiple profiles execution issue

### ISSUE THREAD

**Issue by mtahir** [cucumber/cucumber-ruby#207]
Multiple profiles with different tags doesn't work

I am struggling with multiple profiles execution.It shows following 
messages 
0 scenarios 
0 steps 
0m0.000s 
Example 
I have a feature file with two different tags and in my cucumber.yml 
file I have two profiles with each tag name like mentioned below but 
it doesn't work I think its cucumber issue.Suggest if any one knows 
@test 
Scenario 
............ 
...... 
.... 
@test2 
@Scenario 
cucumber.yml file is 
default: --profile a --profile b 
a: -r features -r features\step_definitions -r features\support --tags 
@test 
b: -r features -r features\step_definitions -r features\support --tags 
@test2 
Thanks

**Comment by mrityunjeyan88** [comment]
I am facing the same error even now. Any way I can run multiple profiles in cucumber?

**Comment by reach2jeyan** [comment]
@aslakhellesoy  I am having a rake file to run the cucumber profiles. I had want to run multiple cucumber profiles with a single command. Is there any way I can do that?

`cucumber -p` still gives me the same output what @mtahir mentioned
