### ISSUE TITLE
Extract #steps and #step into a separate plugin gem

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-ruby#401]
Born of #273. This would mean that Cucumber, out of the box, does not support this feature which many of us consider to be an anti-pattern. You'd have to opt-in to use it.

This might interest you @tooky, since you're all over those nested steps at the moment. :) How possible do you think it would be?

**Comment by nodo** [comment]
I would be happy to give this issue a go in order to progress the milestone. What do you think @mattwynne ? Is there anything more pressing?

**Comment by mattwynne** [comment]
@nodo I haven't updated the 3.0.0 milestone in a while and I think this issue was just hanging around there. It would be nice to do it sometime, but it's not high priority I don't think.

I'm playing around with the new "Projects" feature in GitHub, so look there to help you figure out priorities, or ping me on gitter. Thanks for all your efforts so far, it's great to have you on the team!

**Comment by nodo** [comment]
Thanks @mattwynne , will keep an eye on projects or ping you!

**Comment by ericgriffis** [comment]
@mattwynne Has work been done already to this end? I would love to help make this happen, since we have an app that needs to access the steps of failing scenarios, but I don't know where to start

**Comment by mattwynne** [comment]
Hi @ericgriffis can you tell me more about your use-case?

**Comment by mattwynne** [comment]
Ref: Ref: https://github.com/cucumber-attic/gherkin2/issues/178
