### ISSUE TITLE
Skip a scenario at runtime

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-ruby#474]
When a scenario is subject to random intermittent failures, and the steps can tell when that's happened, it would be useful if the step can communicate to cucumber that the scenario just needs to be skipped.

The use case is where the scenario depends on infrastructure (e.g. network latency) that might come and go. A simple FAIL doesn't enable you to distinguish between defects in the code, and environmental / infrastructure issues.

The implementation of this should be as simple as adding a new type of Exception (like Undefined or Pending) that allows you to cause Cucumber to skip the scenario.

**Comment by SeanFelipe** [comment]
exactly what I was looking for. `skip_this_scenario` works as expected. Thanks !
