### ISSUE TITLE
Cukes in subdirectories can't find steps

### ISSUE THREAD

**Issue by steveklabnik** [cucumber/cucumber-ruby#611]
I searched for a previous issue and didn't find one, apologies if I'm bad at that.

I previous had a bunch of cukes in `features/whatever.feature`, and steps in `features/step_definitions/whatever.rb`. It's all good. And when I `bin/cucumber`, everything runs. Peachy! (the bin is from Bundler's binstubs feature. It also happens with `bundle exec` and just a plain `cucumber` in a fresh gemset.)

In an effort to organize my junk drawer of features, I moved a feature into a folder. `features/foo/whatever.feature`. `bin/cucumber` runs everything just fine. So I organized them all nice and neatly into sub-directories.

Another member of my team complained that `bin/cucumber features/whatever.feature` used to work, but now `bin/cucumber features/foo/whatever.feature` doesn't. It can't find the step definitions. I get a whole bunch of yellow in my output.

I couldn't find anything that said anything about it directly, but I remember reading _something_ that said that putting `.feature` files anywhere should work. So, this seems to be a bug.

I can make a sample repository if it's helpful, but I figured it was pretty straightforward.

**Comment by mattwynne** [comment]
I want to push this back to 2.1, I think we can give some focus to the config generally in that release.
