### ISSUE TITLE
Rubinius support

### ISSUE THREAD

**Issue by tom025** [cucumber/cucumber-ruby#622]
Check to see how well the current code base supports. Add a TravisCI build if appropriate.

**Comment by danascheider** [comment]
I'm looking into this now.

**Comment by mattwynne** [comment]
👍  @danascheider

**Comment by danascheider** [comment]
This looks like it may be complicated because of some unresolved issues between Rubinius, Rubygems, and the standard library; using Rubinius 3.30, we are getting a lot of test failures with traces indicating a compiler error. I'll poke around at this some more and see what I can figure out.
