### ISSUE TITLE
Option to run a specific portion of tests

### ISSUE THREAD

**Issue by plaa** [cucumber/cucumber-ruby#683]
We parallelize test running between multiple Jenkins jobs so that our Jenkins slaves are properly utilized.  It would be very useful to have an option --chunk 2/4 (or something) which would run only a specific portion of the tests.

With --chunk n/m Cucumber would split the scenarios (or feature files) into m approximately equal chunks and run the scenarios in chunk n.  The order should of course be deterministic.  Running chunks 1/4, 2/4, 3/4, 4/4 with otherwise same options would cover all scenarios.

Currently we have to manually split the tests using profiles by defining directories and excludes in cucumber.yml.  Keeping these up to date and the test durations approximately equal is somewhat tedious.

**Comment by enkessler** [comment]
cuke_slicer is another gem that would help in dividing up your test suite for parallel execution.

https://github.com/grange-insurance/cuke_slicer
