### ISSUE TITLE
FeaturesLoader still supported?

### ISSUE THREAD

**Issue by willbryant** [cucumber/cucumber-ruby#733]
The Cucumber::Runtime::FeaturesLoader class from 1.3 is still present in lib/cucumber/runtime/features_loader.rb, but it no longer works:

Exception when running features/admin_mep_proposal.feature: `Cucumber::Ast` no longer exists. These classes have moved into the `Cucumber::Core::Ast` namespace, but may not have the same API./Users/will/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/cucumber-2.0.0.beta.2/lib/cucumber/ast.rb:10:in `const_missing'

This broke our cucumber parallelizer (nitra), so I started looking into what needs updating.  But I notice that it's not actually used by the runtime class any more.  Is it meant to still exist?

**Comment by willbryant** [comment]
Yeah :).

**Comment by mattwynne** [comment]
OK @willbryant if you still care about this can you raise a new issue (or ideally a PR with a failing scenario that describes the API you'd like) then we can go from there?
