### ISSUE TITLE
snippets only suggest 'Given' steps

### ISSUE THREAD

**Issue by richarda** [cucumber/cucumber-ruby#764]
The same feature file with undefined steps will suggest snippets with Given, When, or Then as used in the feature file with cucumber 1.3.17.  In 2.0.0.beta3, only Given snippets are generated and suggested.

@mattwynne I'd like volunteer to fork, write a failing scenario and attempt to fix this in a pull request if the team agrees this is in fact an issue.

**Comment by mattwynne** [comment]
Sorry @richarda I made a typo in that last comment - I meant to reference #765 which I believe is the PR to fix this issue - am I right? If so we don't need to keep both tickets open, the PR will do.

**Comment by richarda** [comment]
Yes, that's correct.  #765 is the PR that should fix this.  Thanks.
