### ISSUE TITLE
Using tags as runtime parameters and looping through Scenarios

### ISSUE THREAD

**Issue by emereyd** [cucumber/cucumber-ruby#834]
Hi, I'd like to Tag my scenarios, and iterate through my scenarios with the Tags, and depending on the Tag, have different config.

i.e. I'd like to Tag  my Scenarios as such:
>@tag1 @tag2 @tag3
>   Scenario: First scenario. I'd like to run this scenario multiple times with different config / profiles.
>...
>@tag1 @tag2
>  Scenario: Second scenario. I'd like to run this scenario multiple times with different config / profiles.
>...

Firstly, how can I run my tests for all 3 tags in one profile, and have the scenario execute for each of the Tags it has? i.e. Run First scenario 3 times, and the Second Scenario twice. Is this possible?

Secondly, how can I determine which tag is being executed? I'd like each Tag to have it's own custom browser configuration. I've tried in my hooks file
>scenario.feature.source_tag_names

but this returns all of the Tags  the scenario has.

**Comment by mattwynne** [comment]
Are you looking for [suites](https://github.com/cucumber/cucumber/issues/821)?
