### ISSUE TITLE
Unable to get status from Scenario in Cucumber 2.0.0

### ISSUE THREAD

**Issue by malandra12** [cucumber/cucumber-ruby#836]
I am unable to get the status from a scenario anymore in 2.0.0.  Previously in 1.3.19, I was able to call scenario.status in my After hook to get whether a scenario passed, failed, was undefined or was skipped. In 2.0.0, I can get whether a scenario passed or failed, but I cannot get the specifics, such as if the scenario was undefined or skipped.

**Comment by mattwynne** [comment]
Thanks for reporting. If anyone wants to get into fixing this, I suggest starting here:

https://github.com/cucumber/cucumber/blob/master/spec/cucumber/running_test_case_spec.rb

It would probably make sense to add a `status` or `to_sym` method to all the https://github.com/cucumber/cucumber-ruby-core/blob/master/lib/cucumber/core/test/result.rb subclasses.

**Comment by tiago-santos-rocket** [comment]
Hey Matt,
The same happens with scenario.source_tag_names :)

**Comment by mattwynne** [comment]
Fixed by #836
