### ISSUE TITLE
Missing call of "before_step_result" for background steps when several scenarios in file

### ISSUE THREAD

**Issue by avokin** [cucumber/cucumber-ruby#838]
before_step_result not called for background steps only for the first scenario

For example my feature file looks like: 

```cucumber
Feature: test   
  Background:     
    Given step 1     

  Scenario: test2     
    Given step 2     
  
  Scenario: test3     
    Given step 3 
```

I expect formatter method “before_step_result” to be called 4 times. 

before_step_result “step 1”
before_step_result “step 2”
before_step_result “step 1” before_step_result “step 3”

but I got

before_step_result “step 1”
before_step_result “step 2”
before_step_result “step 3”

**Comment by aslakhellesoy** [comment]
What Cucumber version?

**Comment by avokin** [comment]
Cucumber 2.0.0

**Comment by brasmusson** [comment]
@avokin In Cucumber v2.0.0 the background steps will be executed before each scenario, but the formatter methods will only be called the first time the background steps are executed [see this spec](https://github.com/cucumber/cucumber/blob/master/spec/cucumber/formatter/legacy_api/adapter_spec.rb#L339-396) (the responsibility for not displaying the background more than once, have been moved from the formatters to Cucumber). To get the formatter to be notified for _every_ step, use the new formatter api, see for instance [this comment](https://github.com/cucumber/cucumber/issues/824#issuecomment-88426798) and [this spec](https://github.com/cucumber/cucumber/blob/master/spec/cucumber/formatter/debug_spec.rb) (the latter shows both the calls to the old and the new formatter api methods).

**Comment by mattwynne** [comment]
@avokin did that make sense to you? You need to implement a `before_test_step` method in your formatter to hear this event.
