### ISSUE TITLE
Exit status is always 0 if I fork cucumber process

### ISSUE THREAD

**Issue by abezzub** [cucumber/cucumber-ruby#852]
I have this class in my codebase that I use to run background jobs during cucumber tests:
```
require "timeout"

class CucumberExternalWorker
  attr_accessor :worker_pid, :start_command

  def initialize(start_command)
    raise ArgumentError, "start_command was expected" if start_command.nil?

    self.start_command = start_command
  end

  def start
    puts "Trying to start #{start_command}..."
    self.worker_pid = fork do
      start_child
    end

    at_exit do
      stop_child
    end
  end

  private

  def start_child
    exec({ "RAILS_ENV" => "test" }, start_command)
  end

  def stop_child
    puts "Trying to stop #{start_command}, pid: #{worker_pid}"

    # send TERM and wait for exit
    Process.kill("TERM", worker_pid)

    begin
      Timeout.timeout(10) do
        Process.waitpid(worker_pid)
        puts "Process #{start_command} stopped successfully"
      end
    rescue Timeout::Error
      # Kill process if could not exit in 10 seconds
      puts "Sending KILL signal to #{start_command}, pid: #{worker_pid}"
      Process.kill("KILL", worker_pid)
    end
  end
end
```
This is how it is used:
```
$delayed_job_worker = CucumberExternalWorker.new("rake jobs:work")
$delayed_job_worker.start
```

My env.rb file:
```
require 'cucumber/rails'
require 'json_spec/cucumber'
require 'capybara-screenshot'
require 'capybara-screenshot/cucumber'

require "cucumber_external_worker"

# start delayed job
$delayed_job_worker = CucumberExternalWorker.new("rake jobs:work")
$delayed_job_worker.start

# always delay jobs in cucumber tests
Delayed::Worker.delay_jobs = true

ActionController::Base.allow_rescue = false

Cucumber::Rails::World.use_transactional_fixtures = false

begin
  # start off entire run with with a full truncation
  DatabaseCleaner.clean_with :truncation
  DatabaseCleaner.strategy = :truncation
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

Cucumber::Rails::Database.javascript_strategy = :truncation

Before do
  # clear redis database
  $redis.flushdb

  Rails.cache.clear

  load Rails.root.join('db','seeds.rb')
end
```

Now if I run any cucumber test that fails the exit status of the cucumber process will be 0 and our CI server assumes that all tests passed:
```
cucumber
echo $? <- this returns 0 even if there was a failing test
```
If I move my code in `env.rb` file before cucumber is required then everything works fine. Beginning of `env.rb`:
```
require "cucumber_external_worker"

# start delayed job
$delayed_job_worker = CucumberExternalWorker.new("rake jobs:work")
$delayed_job_worker.start

require 'cucumber/rails'
require 'json_spec/cucumber'
require 'capybara-screenshot'
require 'capybara-screenshot/cucumber'

# always delay jobs in cucumber tests
Delayed::Worker.delay_jobs = true
```
Run cucumber:
```
cucumber
echo $? <- this returns 1 if there is a failing test
```
Is this expected behavior? I would expect cucumber to always return non-zero exit status if any tests failed.

**Comment by mattwynne** [comment]
Just a guess, but this may have something to do with http://blog.arkency.com/2013/06/are-we-abusing-at-exit/

Things get complicated when you have multiple `at_exit` blocks. When I have time I can study this further for you, but hopefully this is a useful clue for you to investigate. We've definitely had issues like this before with other gems that added their own `at_exit` hooks and inadvertently over-wrote the exit status.

**Comment by abezzub** [comment]
I tested my code in isolation and it returns exit status correctly. Also it seems like the only way to have after all hooks in cucumber is to use `at_exit`:
```
  task exit_status: :environment do
    $delayed_job_worker = CucumberExternalWorker.new("rake jobs:work")
    $delayed_job_worker.start

    puts "started"
    Kernel.exit(1)
  end
```
Above code returns correct exit status: `1`

**Comment by abezzub** [comment]
I tried all workaround from https://github.com/cucumber/cucumber/issues/635 and none of them works, so this seems to be a separate issue

**Comment by abezzub** [comment]
Why does cucumber not have "after all" hook? It seems like insisting on using `at_exit` makes more issues like this possible

**Comment by aslakhellesoy** [comment]
I agree, I think an `AfterAll` is the way to go. We're adding it to Cucumber-JVM too.

**Comment by mattwynne** [comment]
So @abezzub is there any more we can do on this issue for you?

**Comment by abezzub** [comment]
Probably not. I guess it would be nice to know _why_ exactly this happens, but I am not sure anyone has enough time to go down the rabbit hole
