### ISSUE TITLE
AfterAll hook

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-ruby#853]
This would replace people's hand-crafted at_exit hooks [which sometimes do funny things](https://github.com/cucumber/cucumber/issues/852).

**Comment by abezzub** [comment]
If no one is working on this yet I would be interested in doing this. I am new to this repo, let me know if you have any ideas/suggestions about the best way to implement the hook.

**Comment by mattwynne** [comment]
Great!

The best way to start is with a `.feature` that describes the behaviour you want. Create a PR with that failing feature in it, and we can go from there.

**Comment by mattwynne** [comment]
Closing in favour of #858
