### ISSUE TITLE
Doc strings with """ in it

### ISSUE THREAD

**Issue by dg-ratiodata** [cucumber/cucumber-ruby#863]
I refactor the documentation/test suite of [cucumber/aruba](https://github.com/cucumber/aruba). I would like to use something like this https://gist.github.com/dg-ratiodata/7c1109061fdc5a82d08b here. Is there a suggestion what to do in such a case? 

The problem is the `"""` within the doc string.

Help is highly welcome. :smile:

**Comment by dg-ratiodata** [comment]
Ok. Found a solution. @mattwynne Do you want me to open a PR to add that to the cucumber documentation?

```cucumber
  Scenario: Detect subset of multiline output
    Given a file named "bin/cli" with:
    """
    #!/usr/bin/env ruby

    puts "hello\nworld"
    """
    And a file named "features/output.feature" with:
    """
    Feature: Run command
      Scenario: Run command
        When I run `cli`
        Then the output should contain:
        \"\"\"
        hello
        \"\"\"
    """
```

**Comment by mattwynne** [comment]
Great, thanks Dennis!

**Comment by brasmusson** [comment]
This will actually change with Gherkin3. There the way to have doc strings inside doc strings is to use both of the two doc strings separators of Gherkin3:
```
    And a file named "features/output.feature" with:
    """
    Feature: Run command
      Scenario: Run command
        When I run `cli`
        Then the output should contain:
        ```
        hello
        ```
    """
```
or:
```
    And a file named "features/output.feature" with:
    ```
    Feature: Run command
      Scenario: Run command
        When I run `cli`
        Then the output should contain:
        """
        hello
        """
    ```
```

**Comment by dg-ratiodata** [comment]
@brasmusson Ah, thanks... But looks a little bit like Markdown ;-)

**Comment by mattwynne** [comment]
I'm worried this will need a major version release as it's not backwards compatible.

Is there a good reason the backslash style is not supported in Gherkin3? Is it just an omission?

**Comment by aslakhellesoy** [comment]
It's an omission. Please file a bug

**Comment by mattwynne** [comment]
I'm going to try and fix it!
