### ISSUE TITLE
Puts in an after scenario hook doesn't display anything

### ISSUE THREAD

**Issue by tuxayo** [cucumber/cucumber-ruby#866]
With Cucumber 1.3.19 and Ruby 2.2.2

Is this dependent of some logging level(which I couldn't find)? Or is this a bug?

Kernel.puts works

**Comment by danascheider** [comment]
I can put together a PR for this if nobody is already working on one. Should I do that?

**Comment by tooky** [comment]
@danascheider please do! Shout if you need any help.

**Comment by danascheider** [comment]
Thanks, I'm on it.

**Comment by danascheider** [comment]
This seems to actually be working as expected in Cucumber 2.0.0 with Ruby 2.2.2, 2.0,0, and 1.9.3, although I was able to reproduce it in Cucumber 1.3.19/Ruby 2.2.2. Are there going to be more 1.x releases? If so, I'll keep trying to track down the problem, otherwise, I'm inclined to call this fixed and recommend that @tuxayo switch to version 2.x.

**Comment by brasmusson** [comment]
As the output from `puts` is sent to the formatters, which are expected to included the output from `puts` in their output (output from Kernel.puts is sent to stdout), the statement "Puts in an after scenario hook doesn't display anything" is incomplete - which formatter did not include the output from the hook in its output? Well, the progress formatter and the pretty formatter are most commonly used to print to stdout, so one of them presumably.

The progress formatter print output from `puts` in after hooks as expected in v1.3.x. The pretty formatter on the other hand is printing the output from `puts` in after hooks after the first step in the next scenario - which means the the output from the after hook after the last scenario is not printed at all. This deficiency occurs for regular scenarios and scenarios outlines with the `--expand` option, for scenario outlines without the `--expand` option the output from after hooks are printed as expected.

Just before @mattwynne released v1.3.20 a week ago, he stated ["I wasn't planning on doing another release in the 1.3 series"](https://github.com/cucumber/cucumber-ruby/pull/872#issuecomment-113630279), so the probability for yet another v1.3.x release in rather low, I think.

**Comment by danascheider** [comment]
Thanks for the information, @brasmusson. In that case I think the issue can just be considered fixed in v2.x. If @mattwynne changes his mind I can revisit.

**Comment by tuxayo** [comment]
I confirm it's resolved with cucumber 2.0
(We have to stay on v1.3.20 because of a dependency problem with cucumber-rails.)
Thanks for you help.

@brasmusson it was the pretty formatter.

**Comment by mattwynne** [comment]
Yay! Thanks everyone for looking into this so thoroughly.

@tuxayo what's the dependency problem? Can I help with that?

**Comment by tuxayo** [comment]
The latest version of the cucumber-rails gem doesn't support cucumber 2.0 but I haven't took the time to evaluate if it's safe to use their master branch. If we really need cucumber 2.0, it wont be a problem, don't worry.
Thanks :-)
