### ISSUE TITLE
"ensure" that code is run

### ISSUE THREAD

**Issue by dg-ratiodata** [cucumber/cucumber-ruby#874]
Hi,

is there a way to tell cucumber that a block of code needs to be run although an exception was raised?

Some like which results in something like

```ruby
begin
  # [code]
ensure
  # [see below]
end
```

```ruby
Ensure do
  all_commands.each { |c| c.terminate }
end
```

We need to make sure in `aruba` that all processes are killed which were started by the user after each example. Or is it sufficient to run that code in an `After`-block?

**Comment by mattwynne** [comment]
Yes, use an After block. They’re run whether or not the scenario failed.

**Comment by dg-ratiodata** [comment]
Ok. Thanks...
