### ISSUE TITLE
Scenario results are reported incorrectly when an Around hook does not call its block

### ISSUE THREAD

**Issue by abstiles** [cucumber/cucumber-ruby#880]
I'm working with a set of tests that can be run in parallel on multiple client machines, and I have a tag that can conditionally skip a scenario (represented by the `@die` tag here) based on whether the environment is appropriate for that particular test. The tag is implemented as an `Around` hook that only calls `block.call` when the client's environment (e.g., OS version) matches the Scenario's expectation. There are a couple of cucumber bugs I've noticed: the counts at the end are off, and the previous scenario is reported incorrectly if it uses any `After` hook. An example:

Feature file:
```cucumber
Feature: Some feature
  Scenario: A scenario before a dead scenario
    Given something happens

  @die
  Scenario: The first dead scenario
    Given something happens

  @after
  Scenario: A scenario with an after hook before a dead scenario
    Given something happens

  @die
  Scenario: Another dead scenario
    Given something happens
```

Step file:
```ruby
Given(/^(.*)$/) do |step_text|
  puts step_text
end

After('@after') do
  puts 'After hook'
end

Around('@die') do |scenario, block|
  puts 'Not running this scenario!'
end
```

Output:
```
Feature: Some feature

  Scenario: A scenario before a dead scenario # test.feature:2
    Given something happens                   # test.rb:1
      something happens

  @after
  Scenario: A scenario with an after hook before a dead scenario # test.feature:10
      Not running this scenario!
    Given something happens                                      # test.rb:1
      something happens
      After hook

  @after
  Scenario: A scenario with an after hook before a dead scenario # test.feature:10
 Not running this scenario!

4 scenarios (2 passed)
2 steps (2 passed)
0m0.046s
```

Note that the scenario "A scenario with an after hook before a dead scenario" is reported twice, but the second time it has no steps. Also notice that the output of the `Around` hook is attached to the wrong scenario each time. In addition, observe that it correctly reports 4 scenarios, but the breakdown only includes the 2 passing scenarios and ignores the skipped ones, where I would expect them to be marked "skipped."

The output is similar in other formats (e.g., `-f json`).

**Comment by mattwynne** [comment]
Hi, thanks for reporting this.

While we work on your issue, I suggest you work around it for the time being by using a `Before` hook that calls `skip_this_scenario` under the conditions where you don't want to run it. You should get the reporting you expect.

**Comment by abstiles** [comment]
Thank you, I've already modified the hook very similarly to your suggestion, though I wasn't aware of the specific `skip_this_scenario` function.

**Comment by mattwynne** [comment]
I'm going to close this because:

1) it's probably really complex to fix
2) it should get resolved naturally as the formatters are re-written
3) there's a workaround.
