### ISSUE TITLE
yard compatibility support

### ISSUE THREAD

**Issue by akostadinov** [cucumber/cucumber-ruby#881]
Hello, yard parsing is very useful but existing `yard-cucumber` plug-in does not work with v2. Can compatibility classes be implemented so that the plug-in works again? Or perhaps patch `yard-cucumber` if that's easier?

https://github.com/burtlo/yard-cucumber

**Comment by mattwynne** [comment]
ref https://github.com/burtlo/yard-cucumber/issues/60

**Comment by akostadinov** [comment]
The repo used is https://github.com/akostadinov/testcuke
With old cucumber:
```
testcucumber]$ yard
[warn]: Could not find extra file: doc/overview.html
Files:           4
Modules:         0 (    0 undocumented)
Classes:         0 (    0 undocumented)
Constants:       0 (    0 undocumented)
Methods:         0 (    0 undocumented)
 100.00% documented
```
Now with cucumber 1.3 removed:
```
testcucumber]$ gem uninstall cucumber

Select gem to uninstall:
 1. cucumber-1.3.20
 2. cucumber-2.0.0
 3. All versions
> 1

You have requested to uninstall the gem:
	cucumber-1.3.20

asciidoctor-1.5.2 depends on cucumber (~> 1.3.1, development)
yard-cucumber-2.3.2 depends on cucumber (~> 1.3)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  y
Successfully uninstalled cucumber-1.3.20
testcucumber]$ yard
[warn]: Error loading plugin 'yard-cucumber'
[warn]: Could not find extra file: doc/overview.html
[warn]: Syntax error in `features/3scenarios.feature`:(1,8): syntax error, unexpected ':', expecting end-of-input
Files:           0
Modules:         0 (    0 undocumented)
Classes:         0 (    0 undocumented)
Constants:       0 (    0 undocumented)
Methods:         0 (    0 undocumented)
 100.00% documented
```

**Comment by akostadinov** [comment]
I finally managed to get an actual error:
```
[2] pry(main)> require 'yard-cucumber'
LoadError: cannot load such file -- cucumber/parser/gherkin_builder
from /home/avalon/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```
That's from `lib/yard-cucumber.rb`.

**Comment by mattwynne** [comment]
That file is gone, and has been replaced by https://github.com/cucumber/cucumber-ruby-core/blob/master/lib/cucumber/core/gherkin/ast_builder.rb

I think if yard-cucumber is going that deep, it's going to need some fundamental changes in order to work with 2.0.

I'm happy to support that effort, but it will need to be done in the yard-cucumber repo. Let's continue this conversation in burtlo/yard-cucumber#60.
