### ISSUE TITLE
Formatter API: is there a way to access a feature that hasn't started execution yet?

### ISSUE THREAD

**Issue by abotalov** [cucumber/cucumber-ruby#887]
I wrote a custom formatter for Cucumber 1.3. That formatter has a quirk to display the executing features in the Web UI in a directory tree view. When all features in the particular folder get finished, the formatter immediately marks that folder as "Completed". It was possible due to `before_features` hook having a `features` argument. The `features` array was remembered and then used in `after_feature` method.

However, it looks like it's no longer possible to provide such functionality in Cucumber 2.0. `before_features` takes `nil` as an argument. Also I haven't found any alternative way to access a feature that hasn't started executing yet (to know if there are any). Is there some way?

**Comment by mattwynne** [comment]
Hi,

Right now there is no way to do this through a formatter. I'm not ruling it out, but currently the way Cucumber's core is now designed, we fire out `Cucumber::Core::Test::Case` instances and start executing them as the feature files are being parsed. The first result arrives before we've finished parsing all the features.

However that isn't always true.

All test cases go through a [chain of filters](https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/runtime.rb#L214) before being executed, and some of those filters (e.g. the [randomizer](https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/filters/randomizer.rb)) have to batch up all of the test cases before passing them on down the chain.

You could certainly get the information you're looking for by implementing a filter, but that's not very well documented yet and I'm not sure how you'd share the data with your formatter. But that would be your current workaround.

@tooky what are your thoughts on this? I'm reluctant to just add a `before_all` report API callback at this point though I can't put my finger on why. Performance? Elegance? If we implement https://github.com/cucumber/cucumber-ruby-core/issues/23 we'd know whether or not anyone was listening for the `before_all` event and could batch or not-batch accordingly...

**Comment by tooky** [comment]
I seem to remember that there's some difficulty with getting a reference to filter that is collecting information into the reporters, so trying to build something that would do this with a filter might be a good exercise to help us figure out how the formatter and filter extension points work together.

Perhaps with cucumber/cucumber-ruby-core#23 we could introduce an event bus. That way filters can signal events on to the bus and any interested formatters can register to receive them. We can provide a way for a custom formatter to always add a specific filter if it requires a non-standard event?

**Comment by mattwynne** [comment]
@abotalov I know this ticket is over a year old now, but you might like to know that the plan is for the new 3.0 release to include a`GherkinSourceRead` event: https://github.com/cucumber/cucumber-ruby/blob/0c36d3a909a90daf1cbf447293ebd98903beac5d/lib/cucumber/events/gherkin_source_read.rb

That should give you what you need, I think.
