### ISSUE TITLE
Background scenarios failing

### ISSUE THREAD

**Issue by xsmaster** [cucumber/cucumber-ruby#892]
So I'm using Selenium and if there is a failed step in the background then the test fails but there is no Stacktrace on why it fails. When I run the debugger I see why it fails but I don't see it output to the screen.

ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
cucumber: 2.0.1
cucumber-core: 1.2.0
gherkin: 2.12.2

-------= Feature File =-------

Feature: cucumber bug

  Background: Stuff
    Given I have an empty locator

  Scenario: Cucumber issue
    When cucumber fails
    Then I see a stack trace

-------= Step Def =-------
Given(/^I have an empty locator$/) do
  puts 'GIVEN'
  $driver.find_element('')
end

When(/^cucumber fails$/) do
  puts 'WHEN'
end

Then(/^I see a stack trace$/) do
  puts 'THEN'
end

-------= Results =-------

Testing started at 12:39 PM ...

GIVEN

Skipped step
Skipped step1 scenario (1 failed)
3 steps (1 failed, 2 skipped)
0m7.085s

Process finished with exit code 1
# 

If I change the step def to the below and the test fails then I see a stacktace as expected.

Given(/^I have an empty locator$/) do
  puts 'GIVEN'
end

When(/^cucumber fails$/) do
  puts 'WHEN'
  $driver.find_element('')
end

Then(/^I see a stack trace$/) do
  puts 'THEN'
end

-------= Results =-------

GIVEN

WHEN

ArgumentError: expected "":String to respond to #shift
./features/step_definitions/CucumberFailure.rb:7:in `/^cucumber fails$/'
./features/Old Project/Test.feature:14:in`When cucumber fails'

Skipped step1 scenario (1 failed)
3 steps (1 failed, 1 skipped, 1 passed)
0m7.254s

Process finished with exit code 1

Sorry for the long issue report but what should I do?

**Comment by mattwynne** [comment]
Can you tell me if you're using the progress or pretty formatter? It's not clear.

If you're using one, try using the other. It might be a problem localised to the formatter. That might give you a workaround for the time being, and will also give us some extra diagnostic info.

**Comment by xsmaster** [comment]
Let me check and I will Post back

**Comment by rosskevin** [comment]
@mattwynne  - I'm seeing this as well.  I have a switch that will run in webkit or selenium (for debugging).  Selenium tests skip backgrounds, the first step is in the scenario.

Here are my options:
```ruby
std_opts = "-r features/support/ -r features/step_definitions --quiet --format progress --format junit -o test-reports --strict --tags ~@wip --tags ~@todo"
```

**Comment by rosskevin** [comment]
It could definitely be formatter related.  As @xsmaster mentioned it is something breaking in `background` that fails silently.  

Here's my case:

1. comment out favicon reference in layout (selenium breaks on this, webkit doesn't)
2. run via command line with  `std_opts = "-r features/support/ -r features/step_definitions --quiet --format progress --format junit -o test-reports --strict --tags ~@wip --tags ~@todo"` works and reports `No route matches [GET] "/favicon.ico" (ActionController::RoutingError)`
3. run via rubymine (different formatter), it fails without reporting the error.

It does appear to be a formatter error.

**Comment by mattwynne** [comment]
OK, so it sounds as though this defect could be expressed as: *errors in background steps not displayed on progress formatter* - correct?

**Comment by xsmaster** [comment]
Sounds about right.

**Comment by dzzh** [comment]
I have currently catched this issue in one of my project that uses Calabash with Cucumber 1.3. After I removed an HTML formatter that was configured with ````--format 'Calabash::Formatters::Html' -o <%= html_report %>````, the issue was gone.

**Comment by danascheider** [comment]
@xsmaster @mattwynne What is the status of this issue?

**Comment by xsmaster** [comment]
I have not looked into this in awhile. Sorry all

**Comment by danascheider** [comment]
That's OK, anything I can do to help @xsmaster?
