### ISSUE TITLE
Error running FIRST Scenario Outlines when Background is used [cucumber 2.0.2]

### ISSUE THREAD

**Issue by vveliev** [cucumber/cucumber-ruby#899]
failing to get instance variable in the first scenario outline only.  

```structure: 
  Background:
      Given my first step                                 # create    '@myinsnace'
  Scenario:
      Then I do some action                           #  '@myinstance.do_this'                   
  Scenario Outline:
       Then I do another action <action>        # '@myinstance.do_that(<action>)'
  Examples:
  | action |
  | step1  |
  | step2  |
```
When executing '@myinctance' not available for first example, however it is available for second example and up.

**Comment by aslakhellesoy** [comment]
I think you're mixing up Gherkin with Ruby. You can't use Ruby code in Gherkin.

**Comment by vveliev** [comment]
I just wrote this way, to display meaning of the step .... let me correct it

**Comment by mattwynne** [comment]
Which version of Cucumber are you suing @vveliev?

**Comment by mattwynne** [comment]
Oh sorry I see you've put that in the ticket title.

**Comment by Summerwind1005** [comment]
Hi,
I tried to reproduce the bug and I can't find what could work wrong there. So I would suppose either the description is not full or there is no bug anymore. :)  Here is the link to the main files from my test: https://gist.github.com/Summerwind1005/a21081f8c8c6944b7b31
Everything works fine for me. 
So may be some more details or better description when it occurs would be nice.

**Comment by vveliev** [comment]
@Summerwind1005 , Thanks for looking into it. 

I cannot reproduce this error right now, and I cannot find code that was not working right now. 

If I will run into the same problem. I will provide more detailed example next time .

Thnaks !

**Comment by mattwynne** [comment]
Thanks for taking the time to close the issue for us.

**Comment by mattwynne** [comment]
Thanks for taking the time to close the issue for us.
