### ISSUE TITLE
Cucumber Truck Factor

### ISSUE THREAD

**Issue by gavelino** [cucumber/cucumber-ruby#904]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Cucumber** and obtained a value of **2**.

The developers responsible for this TF are:

Matt Wynne - author of 45% of the files
Aslak Hellesøy - author of 44% of the files

To validate our results, we would like to ask **Cucumber** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Cucumber**?

(b) Do you agree that **Cucumber** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Cucumber** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by mattwynne** [comment]
As interesting as your research is, I'd like to ask you to please take these questions to our [discussion forum](https://groups.google.com/forum/#!forum/cukes). This issue tracker is reserved for tracking changes to the codebase.

**Comment by gavelino** [comment]
Ok, I'll open a new topic in the forum. Thanks!
