### ISSUE TITLE
Rake task doesn't accept multiple profiles

### ISSUE THREAD

**Issue by jasonkarns** [cucumber/cucumber-ruby#905]
Cucumber can be executed with multiple profiles from the command line by specifying multiple `--profile` options. This feature is even nicely documented [on the wiki](https://github.com/cucumber/cucumber/wiki/cucumber.yml#executing-profiles):

> Even multiple profiles can be specified together.

However, the Rake task presently only accepts a single profile. Thoughts on also allowing the Rake task's `profile` argument to accept an array?

``` ruby
Cucumber::Rake::Task.new 'capybara:webkit' do |t|
  t.profile = %w[ capybara webkit ]
end
```

Which would run: 
``` sh
cucumber  --profile capybara --profile webkit
```

**Comment by jasonkarns** [comment]
There's already a workaround for this: specifying both profiles using `cucumber_opts`, but I would love to see proper support for multiple profiles.

``` ruby
Cucumber::Rake::Task.new 'capybara:webkit' do |t|
  t.cucumber_opts = "-p capybara -p webkit"
end
```

**Comment by jasonkarns** [comment]
Potential PR for this: https://github.com/cucumber/cucumber-ruby/compare/master...jasonkarns:rake-multiple-profiles

**Comment by mattwynne** [comment]
Can you see if you can work out a way to test this? I don't know this code very well and I'm a nervous about making too many changes to it without tests.

**Comment by jasonkarns** [comment]
Sure. I just wanted to make sure the PR would be received well before I
spent any more time on it.

**Comment by jasonkarns** [comment]
PR #907 submitted

**Comment by jasonkarns** [comment]
ping @mattwynne . I rebased #907 onto master. it's all green and ready for review
