### ISSUE TITLE
Step Regex with named captures

### ISSUE THREAD

**Issue by jasonkarns** [cucumber/cucumber-ruby#908]
I've looked for but not found any discussion around using named captures in the step definition regex.

Rather than positional args, I find named capture groups to be self-describing in the regex itself. It would also allow passing the named captures to the step definition block as a hash or even as keyword args.

Receiving the captured arguments as a hash (or keyword args) is even _more_ beneficial when the step definition body is provided as a method using the `on: -> {}` format. Since the body of the definition (and thus, the arguments) is defined as a method separate from the regex itself, a hash/kwargs is more stable than relying on position as they do now.

Has this idea been discussed before?

**Comment by tooky** [comment]
I don't think this has been discussed before. 

Could you give us an example of what a step def using named captures would look like please?

**Comment by jasonkarns** [comment]
Contrived example based on cucumber wiki examples:

``` ruby
Given /^I have (?<count>\d+) "(?<vegetable>.*)s" in my (?<location>belly|bag)$/ do |args|
  # Some Ruby code here
end
```
``` gherkin
Given I have 5 "cucumbers" in my bag
# args => { count: 5, vegetable: "cucumber", location: bag }
```

Alternatively, keyword args:

``` ruby
Given /^I have (?<count>\d+) "(?<vegetable>.*)s" in my (?<location>belly|bag)$/ do |count:, vegetable:, location:|
  # Some Ruby code here
end
```
 
There are a number of benefits to leveraging named captures.

1. self-documenting regex
As mentioned before, making the regex self-describing is important. `Given I have "(.*)"` doesn't explain in the slightest what "I have". Typically, this isn't a huge problem, because the block's arguments are named nearby. However, with the use of the step def `on: ->` feature for defining the step def lambda elsewhere, this is no longer the case. In such a case, the regex is completely obtuse.

2. optional captures put positional args out of order
```
Given /I(?: have (.*) and)? am logged (.*)/ do |x, y|
```
In this case, the first grouped clause is optional. So `Given I have credit and am logged in` results in `x: 'credit', y: 'in'`. But `Given I am logged out` results in `x: 'out'`. How should `x` be named given that it can take completely different roles?
This is, of course, a rather poor example because of the conjunction. But I've frequently had optional, non-capturing groups that contain a capture, which causes this problem with positional args. Named captures would avoid this entirely.

**Comment by jasonkarns** [comment]
This [step](https://github.com/dequelabs/axe-matchers/blob/master/lib/axe/cucumber/step_definitions.rb#L3) and its [crazy regex](https://github.com/dequelabs/axe-matchers/blob/master/lib/axe/cucumber/step.rb#L16-L41) are what most recently re-ignited my desire for named captures, but much more trivial and common scenarios would benefit as well.

**Comment by jasonkarns** [comment]
Taking it a step further, I could even see the named captures being generated for step definitions that use the string/$var syntax:

```
Given "I have $count cucumbers in my belly" do |count:|
```

The above string step could use the $var variable name as the name for the capture:

```
/^I have (?<count>.*) cucumbers in my belly$/
```

But this would clearly be an additional feature that depends on named captures being supported in the first place.

**Comment by mattwynne** [comment]
I like this idea, and I’d be keen to see a PR so we can discuss something concrete.


cheers,


Matt




—


matt@cucumber.io


m: +44(0)7974 430184
