### ISSUE TITLE
Dev environment should be friendly to Windows users

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-ruby#916]
In https://github.com/cucumber/cucumber-ruby/issues/915#issuecomment-142438357 @enkessler noted that Cucumber's build doesn't work on Windows.

This excludes Windows users from contributing to Cucumber.

Is anyone willing to help fix this? We can use https://ci.appveyor.com to add CI once we have a build that works.

**Comment by tomatobrown** [comment]
I have the cucumber-ruby gem working on Windows, maybe I'm not understanding your problem

**Comment by aslakhellesoy** [comment]
@tomatobrown this is about running cucumber's own build on Windows. Clearer?

**Comment by enkessler** [comment]
@mattwynne @aslakhellesoy PR #1116 has added a Windows build to the CI process. There is some remaining work in getting that build green, however.

All specs pass but there are still [failing features](https://ci.appveyor.com/project/enkessler/cucumber-ruby-u5iqh/build/1.0.1/job/1euuunkgnb6h2i7a).

**Comment by brasmusson** [comment]
It looks that some (all?) of the failing features would be fixed if Cucumber-Ruby also on Windows understood that `/` in the feature path argument means the path separator. Luckily for Cucumber-JVM, Java on Windows understands that, therefore Cucumber-JVM always output the `uri` with `/` as the path separator and it works on all platforms (for instance uri's with `/` in the `rerun.txt` file).

**Comment by enkessler** [comment]
@brasmusson Wouldn't that mean that we only use path separators in 1 in 3 of our tests? Additionally, several of those path errors go away when that command is invoked via backticks instead of through Aruba. Shouldn't the path error still be there if it were a Ruby on Windows problem?

**Comment by aslakhellesoy** [comment]
We have an Appveyor build, it just isn't passing. Closing this in favour of #1215 which has a more specific acceptance criterion (make the build pass)
