### ISSUE TITLE
Cucumber implicitly requires all gems provided by Gemfile.lock

### ISSUE THREAD

**Issue by JeanMertz** [cucumber/cucumber-ruby#929]
I haven't found the code snippet responsible for this issue yet, but I've noticed that cucumber implicitly requires all gems when running our tests.

This is unwanted behaviour, because we run our application using:

```ruby
require 'bundler'
Bundler.setup
```

(see [bundler.io](http://bundler.io/v1.10/bundler_setup.html) and *["Use Bundler.setup Instead of Bundler.require"](http://anti-pattern.com/use-bundler-setup-instead-of-bundler-require)*)

This means Ruby files in our codebase explicitly require a library when it needs access to this library. However, we've noticed several times that Cucumber happily loads all gems, and the tests pass, but when we run the application (in production or otherwise), it fails because some library wasn't required yet in some Ruby file that needed access to it.

Is there a way to disable this behaviour (note the `--require` flag does not control this specific instance of library requires)?

**Comment by JeanMertz** [comment]
I'm closing this issue, as I suspect this is actually being triggered by one of the dependencies loaded through the `support/` directory. I haven't confirmed this yet, but I also haven't found any code related to auto-loading of libraries in Cucumber.

Will reopen if it turns out I was wrong, but I doubt that Cucumber is the culprit.

**Comment by mattwynne** [comment]
Thanks for tidying up and good luck figuring it out!



cheers,


Matt




—


matt@cucumber.io


m: +44(0)7974 430184
