### ISSUE TITLE
Don't filter backtrace for internal exceptions

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber-ruby#934]
Ran into an interesting edge case in a test suite where I can changing the working directory.
I end up in a case where a test fails and `Dir.pwd` errors.
This results in this [line](https://github.com/cucumber/cucumber-ruby/blob/34760f7286d6ce5c2f4291e09e29335e6dcb1e8c/lib/cucumber/formatter/backtrace_filter.rb#L21) erroring.

The result is just an error message is printed, without a backtrace, and cucumber dies. 

Using `-b` helped bring the issue to light but I believe it would be benefial to not filter the backtrace if the first line is in cucumber code instead of user code.

**Comment by mattwynne** [comment]
Oh good idea! Yeah this gets me occasionally too.
