### ISSUE TITLE
Cucumber 2.1.0 - `block in process_args': invalid option: --tags (OptionParser::InvalidOption)

### ISSUE THREAD

**Issue by ghost** [cucumber/cucumber-ruby#935]
Cucumber 2.1.0
Ruby 2.1.6
gherkin (2.12.2)
gherkin3 (3.1.2)

Running a feature with the "--tags" or "-t" option the error with "minitest" appears even after the feature passes without any errors.

I have gem minitest (5.8.2, 4.7.5)
This is what I get on terminal:

/Users/XYZ/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/minitest/unit.rb:1044:in `block in process_args': invalid option: --t (OptionParser::InvalidOption)
    from /Users/XYZ/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/minitest/unit.rb:1023:in`new'
    from /Users/XYZ/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/minitest/unit.rb:1023:in `process_args'
    from /Users/XYZ/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/minitest/unit.rb:1073:in`_run'
    from /Users/XYZ/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/minitest/unit.rb:1066:in `run'
    from /Users/XYZ/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/minitest/unit.rb:802:in`block in autorun'

Can someone please help me with this?

Thanks

**Comment by angeliaw** [comment]
i have the same issue, how it works now?
