### ISSUE TITLE
Upgrade to gherkin 3.2.0

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-ruby#943]
See cucumber/gherkin#147 and https://github.com/cucumber/gherkin/blob/master/CHANGELOG.md for details (note the gem+module name change)

**Comment by brasmusson** [comment]
Both cucumber-ruby-core and cucumber-ruby has been updated to use gherkin 3.2.0 on their master branches. Releasing them will have to wait, I've got not time to do that today.

**Comment by brasmusson** [comment]
The gems cucumber v2.3.0 and cucumber-core v1.4.0 using gherkin 3.2.0 are now released.

**Comment by akostadinov** [comment]
thanks a lot!
