### ISSUE TITLE
Preventing postgres invoke by cucumber

### ISSUE THREAD

**Issue by manuraj17** [cucumber/cucumber-ruby#944]
I am having cucumber tests for my rails app. Currently I require to test against a remote server and do not require to invoke my local app. Whenever I try to run it is asking for postgres database to be up as well. I want only cucumber to be running and testing the remote app, so I do not require local app or the database to be started. Is that even possible? 

I have made the following config settings in env.rb, no result. 

config.run_server = false
config.app_host = ENV['URL']

**Comment by aslakhellesoy** [comment]
Please take your question to https://cucumber.io/support

This is a bug tracker
