### ISSUE TITLE
Before hook never runs

### ISSUE THREAD

**Issue by seanlinsley** [cucumber/cucumber-ruby#947]
When the cucumber-rails gem released a new version (1.4.2 -> 1.4.3) which removed the `< 2` limitation on the cucumber gem, `Before` hooks seemed to stop working completely.

I specifically noticed this through the Active Admin repo, who [has tests that shouldn't run on Rails 3.2](https://github.com/activeadmin/activeadmin/blob/7c1e64264167680afaffc4dab1a1338e7ca25d84/features/strong_parameters.feature#L1), so [we skip them with a tag](https://github.com/activeadmin/activeadmin/blob/7c1e64264167680afaffc4dab1a1338e7ca25d84/features/support/env.rb#L143-L145). Once 1.4.3 was released, that `Before` hook stopped being run. Adding this to the project's Gemfile fixes the issue temporarily:

``` ruby
gem 'cucumber', '1.3.20'
```

Here's the Travis build where this started happening: https://travis-ci.org/activeadmin/activeadmin/builds/104775499

`Before` hooks with no tags don't work either, but `Around` hooks still work.

You can reproduce with with the Active Admin repo by doing this:

``` sh
export RAILS=3.2.22
bundle
cucumber features/strong_parameters.feature
```

**Comment by mattwynne** [comment]
Thanks for reporting. That's puzzling as all our tests for hooks work, and this is the first time anyone has reported the problem. I wonder what's going on in your case.

**Comment by tooky** [comment]
@seanlinsley you're using `scenario.skip_invoke!` which is going to be [deprecated](https://github.com/cucumber/cucumber-ruby/blob/c22c19ffed5e39697201fbfa65b33cb9b2be445a/features/docs/defining_steps/skip_scenario.feature). Could you try the new syntax just rule out anything strange happening with the old API, please?

```ruby
Before('@rails4') do
 skip_this_scenario if Rails::VERSION::MAJOR < 4
end
```

**Comment by seanlinsley** [comment]
@tooky that wouldn't be the issue -- with a `puts` or a `binding.pry` inside of the block, it never gets reached.

**Comment by marinalimeira** [comment]
I'm having a issue very similar... I just put 5 tags in a `Before` and it's not working as it was supposed to.
