### ISSUE TITLE
Use the new issue and pull request templates of Github.

### ISSUE THREAD

**Issue by maxmeyer** [cucumber/cucumber-ruby#956]
Hi,

some weeks ago Github introduced PR and issue templates (https://github.com/blog/2111-issue-and-pull-request-templates).

I created this issue to discuss how a good template for each might look like. Since both files are somewhat specific to github I suggest to go for github's suggestion an place them into `.github`-directory in <project root>.

* `.github/ISSUE_TEMPLATE.md`
* `.github/PULL_REQUEST_TEMPLATE.md`

**Comment by maxmeyer** [comment]
I found those templates here: https://github.com/TalAter/open-source-templates

Template PR - suggestion

~~~markdown
<!--- Provide a general summary of your changes in the Title above -->

## Description
<!--- Describe your changes in detail -->

## Motivation and Context
<!--- Why is this change required? What problem does it solve? -->
<!--- If it fixes an open issue, please link to the issue here. -->

## How Has This Been Tested?
<!--- Please describe in detail how you tested your changes. -->
<!--- Include details of your testing environment, and the tests you ran to -->
<!--- see how your change affects other areas of the code, etc. -->

## Screenshots (if appropriate):

## Types of changes
<!--- What types of changes does your code introduce? Put an `x` in all the boxes that apply: -->
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
<!--- Go over all the following points, and put an `x` in all the boxes that apply. -->
<!--- If you're unsure about any of these, don't hesitate to ask. We're here to help! -->
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
~~~

Template for issues

~~~markdown
<!--- Provide a general summary of the issue in the Title above -->

## Expected Behavior
<!--- If you're describing a bug, tell us what should happen -->
<!--- If you're suggesting a change/improvement, tell us how it should work -->

## Current Behavior
<!--- If describing a bug, tell us what happens instead of the expected behavior -->
<!--- If suggesting a change/improvement, explain the difference from current behavior -->

## Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

## Steps to Reproduce (for bugs)
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:
~~~

**Comment by danascheider** [comment]
@maxmeyer @dg-ratiodata Don't you have something similar to this in the Aruba repo? I found that extremely useful when I was filing an issue report (even though it would've been my inclination to be much lazier than that about what information to include!). I think these are a great idea.

**Comment by mattwynne** [comment]
Yeah I totally agree, I just haven't had time to review the exact content. Maybe we should just merge them as they are and we can always iterate?

**Comment by danascheider** [comment]
I think that's a good idea. I copied and pasted the template from Aruba to Rambo, at least for issue requests - haven't had a chance to look at the one for PRs yet.

**Comment by dg-ratiodata** [comment]
@danascheider Sorry for being unresponsive. I did a climbing trip at the (long) weekend.

> Don't you have something similar to this in the Aruba repo?

Yes, I added those files and modified them at a few places, e.g I added this snippet:

~~~html
<!-- This sections are meant as guidance for you. If some doesn't fit, skip them. In general: Please provide as much information as you can to help us solving your problem -->
~~~

I can create a PR if you like. So it's easier to review them. 

BTW: Not sure if I mentioned it, but @dg-ratiodata is my coporate account, @maxmeyer is my private one. So please don't be confused, when you see me answering questions etc. with both of them.

**Comment by danascheider** [comment]
I remember your saying that, yeah. And no worries about the unresponsive thing, I tend to drop off the earth for months at a time, so it's all good.
