### ISSUE TITLE
Prevent documentation feature tests to make the whole test suite fail

### ISSUE THREAD

**Issue by maxmeyer** [cucumber/cucumber-ruby#964]
We've got an angoing discussion at https://github.com/cucumber/aruba/issues/362 about removing dependencies of aruba's test suite. Although this is normally a good thing, it's more "difficult" in this case. It's mainly about this [feature](https://github.com/cucumber/aruba/blob/master/features/getting_started/run_commands.feature) which demonstrates that you can run any command with `aruba`.

The problem is this: If a developer does not have zsh, java and the like installed, the test will fail and this is a "bad" developer experience.

I see the following options:

1. Exclude tests from normal test suite, say tag them as `@documentation` and run them only on CI
2. Remove them
3. Tag them as WIP

The most reasonable one seems to be "1.". What would you suggest? Another option would be to add a switching telling cucumber to allow failing of arbitrary tagged features.

Thanks a lot.

Cheers,
Dennis

**Comment by tooky** [comment]
> Exclude tests from normal test suite, say tag them as @documentation and run them only on CI

If you wanted to be more selective you could tag each scenario with a command for the dependency, and check for the dependency in a before hook, and skip the scenario if it’s not there.

**Comment by dg-ratiodata** [comment]
That sounds good. Thanks @tooky.

**Comment by jenisys** [comment]
That is what "active tags" are normally about :smile:

**Comment by danascheider** [comment]
@dg-ratiodata Does this issue require any action in this repo? If not, I'm thinking it should be closed. @tooky what do you think?

**Comment by tooky** [comment]
@danascheider agreed, @dg-ratiodata please reopen it if we've missed something that needs to be done.

**Comment by maxmeyer** [comment]
@danascheider @tooky I'm fine with closing it. I followed @tooky's recommendation and added before hooks.
