### ISSUE TITLE
Seeded order is platform-dependent

### ISSUE THREAD

**Issue by threedaymonk** [cucumber/cucumber-ruby#971]
When using `--order=random` with a seed, the order is determined by Ruby's `Array#shuffle` method.

Seeded `Random` produces consistent results across different versions of Ruby and JRuby, but `shuffle` is implemented differently in different interpreters:

Ruby 2.2.4:

```
[1,2,3].shuffle(random: Random.new(4))
=> [2, 1, 3]
[1,2,3].shuffle(random: Random.new(5))
=> [1, 2, 3]
```

Ruby 1.9.3 and JRuby 1.7.23:

```
[1,2,3].shuffle(random: Random.new(4))
=> [1, 2, 3]
[1,2,3].shuffle(random: Random.new(5))
=> [3, 2, 1]
```

As I discovered whilst working on #970, this makes it difficult to write specifications that will work across all supported platforms. The current [`randomize.feature`](https://github.com/cucumber/cucumber-ruby/blob/7f917e5795021557eaa7312091c961463ff5089a/features/docs/cli/randomize.feature) effectively works only by accident because it shuffles only two items.

This also means that it's not always possible to replicate a particular seeded order on a different interpreter.

RSpec has a similar random ordering feature that uses a platform-independent [sort on a hash of the item index and the seed](https://github.com/rspec/rspec-core/blob/243c08d83fe81887aabace8ea34a9a1ee445585e/lib/rspec/core/ordering.rb#L25-L59). This seems like a more robust thing for `cucumber-ruby` to do, although it would come at the cost of invalidating any existing use of seeds.

**Comment by myronmarston** [comment]
FWIW, I didn't realize that `Array#shuffle` is platform-dependent.  The reason we switched to sorting by `hash(item + seed)` is to provide _stable_ random ordering. `%w[ a b c d ].shuffle` may order `c` before `b`, but `%w[ b c d ].shuffle` may order `c` after `b` even if you use the same random seed.  When you are trying to isolate an ordering dependency, it's essential that the examples are always ordered the same relative to each other, even as the user runs smaller and smaller subsets of the whole suite.  Our `--bisect` feature would be impossible without it.

**Comment by mattwynne** [comment]
Thanks for the insight Myron. I covet your bisect feature, so this is worth bearing in mind. Thanks!

**Comment by threedaymonk** [comment]
That's really interesting. Thanks @myronmarston.

@mattwynne I'll add a scenario to cover stability. The scenario path/line is one obvious candidate as a basis for ordering, but it might need a bit of tweaking to ensure that it's not affected by the delimiter (i.e. that it works the same on Windows).

**Comment by mattwynne** [comment]
That's great, thanks @threedaymonk
