### ISSUE TITLE
step transformations

### ISSUE THREAD

**Issue by akostadinov** [cucumber/cucumber-ruby#986]
Hello, right now I see that cucumber does:
1. step regular expression matching
2. step transformation

I am trying to understand why that has been chosen. To me it makes more sense to do it the other way around. i.e. first transform and then match the steps.

In our test suite we decided to make <%= ... %> expressions expand to some ruby expression inside. Issue is that if step for example matches \w+ then using such expression in place doesn't work. It is not such a big deal as quotes can be used for parameters. Just a little harder to write the quotes.

But I thought to propose making transformation happen before matching unless there are good reasons to keep current approach.

Thank you.

**Comment by mattwynne** [comment]
Can you show us a concrete example please @akostadinov? I'm struggling to visualise exactly what you mean.

**Comment by akostadinov** [comment]
e.g. a step like `/^I delete the(?: (\W+?))? project$/`

And then this call will not be matched:
```
Given I delete the <%= project(-2).name %> project
```

Step needs to be modified to this for such use case to work:
`/^I delete the(?: "(\W+?)")? project$/`

But now I read 
https://github.com/cucumber/cucumber/wiki/Step-Argument-Transforms

It looks like the transform step is matching individual matches instead of whole step string. I guess that this feature just can't work this way. Maybe another transform hook is needed if whole step string is to be transformed.
